### ISSUE TITLE
missing IPTs

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1165]
**missing IPTs**

Hello,

There are some  IPTs that are missing on the map :

GBIF France IPT 
MNHN Géologie CP48
43 rue Buffon
75005 Paris
ipt.gbif.fr

Burkina Faso IPT
hosted by GBIF France (`http://ipt-burkinafaso.gbif.fr/).`

GBIF Guinée IPT
hosted  by GBIF France (`http://ipt-guinee.gbif.fr/).`

Côte d'Ivoire IPT
hosted by GBIF France (`http://ipt-cotedivoire.gbif.fr/).`

MadBif IPT
hosted by GBIF France (`http://ipt.madbif.mg/).`

GBIF Togo IPT
hosted by GBIF France (`http://ipt-togo.gbif.fr/).`

GBIF Uganda IPT
hosted by GBIF France (`http://ipt-uganda.gbif.fr/).`

Do you need the coordinates of each GBIF node or institution to add to the map (like you did with GBIF Benin and GBIF Cameroon) ?

Thanks for your help !
Best regards,
Marie

-----

User provided contact info: @melecoq
System: Chrome 63.0.3239 / Mac OS X 10.11.6
User: [See in registry](https://www.gbif.org/api/feedback/user/129b2b06a28ae6d041d7c426c7e7be21:8791c65933a472c475983684ee5161098a599801a05b60a7ed477d5cc7df7e1e6d879ddaa6484a329d2d76e30d68c37d6f3ba846327225d214164492c2734d9b)
Referer: https://www.gbif.org/ipt
Window size: width 1232 - height 960
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-15T12:30:37.056Z',mode:absolute,to:'2018-02-15T12:36:37.056Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-02-15T12:30:37.056Z',mode:absolute,to:'2018-02-15T12:36:37.056Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
Thanks for reporting this! To put the IPTs on the map, we will indeed need the geographical coordinates. I would debate whether this should show the location that the installation is actually running from, rather than the node or institution it is nominally attached to, but it seems that with IPT Benin, Gabon and Cameroon, that has already been decided (?)
If you could send us the coordinates for each node institution, we’ll add them to the registry.

**Comment by MattBlissett** [comment]
This requires adding latitude and longitude for the hosting publisher for each IPT, for the first one that is https://www.gbif.org/publisher/9764f31c-f399-4912-97fd-01ebf8b8141c (I have just guessed the coordinates).

**Comment by melecoq** [comment]
Thanks for your answers.

For the GBIF France IPT, coordinates (in decimal): 48.842005, 2.359355.
I will look for the other ones.

**Comment by ahahn-gbif** [comment]
Dear Marie, sorry I dropped the ball on this! The Paris entry has been updated with the coordinates you sent, and FasoBIF still stands at the (preliminary?) entry the Matt added, but the other ones are still missing. Would you happen to have the coordinates for us to add? Otherwise we can use an estimate based on the institution name.

**Comment by ManonGros** [comment]
I tried my best to add the missing coordinates based on the name of organization and address provided.
