### ISSUE TITLE
no citation count on download pages

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal-feedback#1222]
Something appears broken. gbifDownloadKey appears to be the way to get the info:

e.g. for https://www.gbif.org/occurrence/download/0003948-150922153815467
count is here: https://www.gbif.org/api/resource/search?contentType=literature&gbifDownloadKey=0003948-150922153815467
and should link to
https://www.gbif.org/resource/search?contentType=literature&gbifDownloadKey=0003948-150922153815467

**Comment by MortenHofft** [comment]
@dnoesgaard please just label it as portal + whatever label you find appropriate. Then Thomas (and others) will have a chance to find and fix it as well :)

**Comment by MortenHofft** [comment]
Thanks Daniel
So far we have been using free text search for this feature. That has been very fragile as any change to improve search in general could break (and have been breaking) this.

Search on downloadKey has since been added to the index, but the interface haven't been updated to use it. it does so now.
