### ISSUE TITLE
Sensitive species data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1235]
**Sensitive species data**

I've found occurrence information for a sensitive species that I feel has not been adequately generalized. Occurrence data for this species IS generalized if I download it directly from the contributor (Australia's Virtual Herbarium) but IS NOT generalized when I download it from gbif. 
Who should I contact?

-----

User provided contact info: @sastuart
System: Firefox 58.0.0 / Mac OS X 10.13.0
User: [See in registry](https://www.gbif.org/api/feedback/user/1e173a1da2beb8a70d0c5222c4606ef5:66959ea10e9367f5a83df4549ab4dfd0b58f5140fe7b255abd235e835ca382d5a65ca09fa138895fe3270149df4b40255648fc0081260e3f6a50113bc1f1f17e)
Referer: https://www.gbif.org/dataset/19491596-35ae-4a91-9a98-85cf505f1bd3
Window size: width 1357 - height 752
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-07T00:02:54.811Z',mode:absolute,to:'2018-03-07T00:08:54.811Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-03-07T00:02:54.811Z',mode:absolute,to:'2018-03-07T00:08:54.811Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Hi @sastuart,

You can contact the data publisher directly, contact details should be on the dataset's page.  They should ensure the sensitive records are absent or obscured in the data export they provide to GBIF, and ensure the dataset is being successfully ingested by GBIF.

Please also CC helpdesk@gbif.org. If the publisher is unable to remove/obscure the sensitive records in a reasonable time, we can delete them directly.

**Comment by ManonGros** [comment]
It seems that [this dataset](https://www.gbif.org/dataset/19491596-35ae-4a91-9a98-85cf505f1bd3) doesn't have any occurrence. It was modified on March the 8th and only the metadata is remaining.

**Comment by MattBlissett** [comment]
That Red List is a checklist dataset, and it never had either occurrences or names.

Without more information, we don't know what this user was looking at. They probably made this issue after searching "threatened species" or similar.

**Comment by sastuart** [comment]
Just to clarify -- I was not doing a general search. My post is light on details to protect the species. I searched for a specific rainforest tree from NSW, and I am happy to provide more detail where it can be treated confidentially. Sensitive data was erroneously published by Australia's Virtual Herbarium (this issue has been fixed by the data provider.) Additional sensitive information is still available for the species from large international herbaria (e.g. Kew, Paris, Missouri Botanical Garden.) 

We are working with our local delegates to petition the gibf secretariat to review the way sensitive species data is handled within gbif. I can share details of the request if it is of interest here.
