### ISSUE TITLE
Crawl Frequency Question

### ISSUE THREAD

**Issue by jrdh** [gbif/portal-feedback#1294]
Is there a schedule for external dataset crawling? Looking at our [crawl history](https://management-tools.gbif.org/crawl-history?uuid=7e380070-f762-11e1-a439-00145eb45e9a) I can't see any obvious patterns. We're aware that we can trigger crawls manually, and have done recently, but it would be good to know if there is a schedule defined anywhere.

Thanks!

**Comment by MattBlissett** [comment]
Hi Josh,

The general aim is for datasets to be crawled weekly, although there are times we disable crawling. I also fixed a few bugs with the scheduling process in recent months, so it shouldn't be as erratic as before.

I've updated the FAQ, since it wasn't entirely correct: https://www.gbif.org/faq?question=how-often-does-gbif-reindex-my-dataset

**Comment by jrdh** [comment]
Great, thanks for the clarification @MattBlissett
