### ISSUE TITLE
IPT republishing did not update index completely

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1310]
**IPT republishing did not update index completely**

While checking to see if year and month information appeared in the GBIF index after republishing a data set including that information newly added, we discovered this issue.

The records for this data set have year and month in the data from the IPT after publishing version 1.7 on 17 Apr 2018. The year and month did not appear in the data on GBIF - not in the record summary, the record detail, nor in the search result download, in fact, not even in the verbatim record. It is as if the publishing event did not trigger an indexing by GBIF for version 1.7. 

Further, the citation for the dataset as given in the citations.txt file in the GBIF download is: 

Hakaumotu V (2018). Invasive Species in the Toloa Rainforest. Version 1.5. Department of Environment, Government of Tonga. Occurrence Dataset `https://doi.org/10.15468/suj1kg` accessed via GBIF.org on 2018-04-18. 10.15468/suj1kg

This is very odd, as the title only changed to "Invasive Species in the Toloa Rainforest" in version 1.7. Before that, including in version 1.5, the title was "Toloa Rainforest".

Finally, the data on GBIF include coordinates and taxon changes that were published in version 1.6 on 16 Apr 2018. 

We are ready to publish again, just to see if we can get the data to be correct in GBIF, but thought it might be worth leaving the state as is for debugging purposes. 

The only things we can think of so far suggest some kind of timing issue. We are publishing on the IPT at SPREP in Samoa, which was a day ahead of Copenhagen time each time we published. Seems strange, but could this have had an effect. If so, this is serious, as it could be very common that a data set update event like this would be lost. 

We DO want the data to be updated to be correct. We will try again in about 10 hours to see if the update goes through.

-----

User provided contact info: @tucotuco
System: Chrome 64.0.3282 / Mac OS X 10.10.3
User: [See in registry](https://www.gbif.org/api/feedback/user/31a52901f48d5e4d3c8181b395b92175:b5599bfdd99625449d7c39e39e5d02150f3e9d671431120a1959eded365bdda7067b0e2144fab445f3cc320411b343458b2cfa975e806552d60609599b34be3f)
Referer: https://www.gbif.org/dataset/11f7be1d-fdf3-4753-bfb0-c61ddbde3303
Window size: width 1129 - height 607
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-18T08:56:25.398Z',mode:absolute,to:'2018-04-18T09:02:25.398Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-04-18T08:56:25.398Z',mode:absolute,to:'2018-04-18T09:02:25.398Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Hi,

(All times UTC; I'm not worried about timezones having any effect here, except to confuse me when I cross-reference the dates displayed in the IPT with the times in our logs ­— I assume your server is set to Samoa time?)

I see a request at 2018-04-16 21:25:57 for reindexing, which was processed and caused 36 records to be updated. (Your webserver should have a request for the archive at that instant.)

At 21:26:59 another request was received. That can be the IPT updating the registry in two steps, though it usually doesn't take a whole minute. This request was denied, as it was too close to the previous one.

Another request came in at 2018-04-17 10:49 for reindexing. This request was also denied, although I think this was due to an intermittent [bug with our system](https://github.com/gbif/crawler/issues/2) which is proving difficult to track down.

I have just requested a reindex (2018-04-18 09:55), and it has updated the metadata and 36 occurrences. Does it now appear as you would expect?

If you register a GBIF account with an email address matching the dataset, installation or publishing organization contacts, then you will see an "Ingest now" button when you look at the dataset page. This triggers a reindexing in most cases. Alternatively, ask the helpdesk to add your contact details as a "Technical contact" or similar to the [installation](https://www.gbif.org/installation/6b459ded-20ca-46f2-8323-5f4eed4b9fde).

You would also see links to the [ingestion history](https://management-tools.gbif.org/crawl-history?uuid=11f7be1d-fdf3-4753-bfb0-c61ddbde3303), although that doesn't need a password. (The web interface seems to try and be clever and show local times, the "..." button expands to show the UTC time.)

**Comment by tucotuco** [comment]
OK that's a clear explanation and the reindexing did go through. All seems
well now.  Thank you!

Until the bug is eradicated, would you say the best course is always to
check that the publishing event went through to indexing?

What should we tell people about how long to expect the results to be
visible for small data sets (<10k records)?

**Comment by MattBlissett** [comment]
The bug is usually only a problem for datasets being published then re-published soon after, so routine publication (e.g. daily or weekly auto publication) isn't affected.

If someone has made metadata or data structure changes, then for the moment checking those changes have been processed makes sense. Use the "history" view, or the last ingested date on a dataset page.

The [ingestion monitor](https://management-tools.gbif.org/crawling-monitor) is the best place to look if you're waiting for something to be indexed. (Tick "live view".) Small datasets should start being indexed within 2 minutes, large ones (10s millions) can take up to about 15 minutes to download and validate. Indexing then runs at around 500 records/second (new or modified records) or 5000/s (unmodified records); after it's finished it can take up to 10 minutes for the result to show on the website.

Delays are either because a very large (10 million+) dataset is ahead in the queue, in which case you'd see it in the monitor, or because we've temporarily paused processing. The latter is less likely to happen during the Pacific working day.

**Comment by tucotuco** [comment]
Though we may have seen this phenomenon again during the SPREP workshop, I am satisfied with the explanation. Thank you.

**Comment by MattBlissett** [comment]
The intermittent bug was fixed (I hope!) a couple of weeks ago, so I can now close this. Thanks.
