### ISSUE TITLE
AntWeb occurrences matched only to higher taxon rank

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1379]
**AntWeb occurrences matched only to higher taxon rank**

For many occurrences in this otherwise fantastic dataset, the taxon matching only makes it to order (Hymenoptera). Looking at the verbatim Taxon data, it is difficult to see why this should be the case - for example in this record,  Anochetus mixtus Radchenko, 1993  is an accepted species in the backbone (`https://www.gbif.org/species/1319553)` . It seems to be a general bug (sorry) across the dataset, and it would be great to work out why we are not able to interpret the species names correctly.

-----

User provided contact info: @timhirsch
System: Chrome 66.0.3359 / Mac OS X 10.13.4
User: [See in registry](https://www.gbif.org/api/feedback/user/13264138d63e0abb2b544ef33ee0f507:bcba8804c35a2ade82318e72e1d2506341861e2266b74c5530bc2344f2358c242bb63dd1b595574b05e4f0eb9ea5a3e5790139628c54e930a2e0488a7a9d3738)
Referer: https://www.gbif.org/occurrence/1569610646
Window size: width 1800 - height 868
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-03T11:11:35.791Z',mode:absolute,to:'2018-06-03T11:17:35.791Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-03T11:11:35.791Z',mode:absolute,to:'2018-06-03T11:17:35.791Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Surprisingly, it's because the generic epithet doesn't start with a capital letter in the verbatim name.

http://api.gbif.org/v1/species/match?name=anochetus%20mixtus&kingdom=animalia&phylum=arthropoda&class=insecta&order=hymenoptera&family=formicidae&genus=Anochetus&verbose=true

http://api.gbif.org/v1/species/match?name=Anochetus%20mixtus&kingdom=animalia&phylum=arthropoda&class=insecta&order=hymenoptera&family=formicidae&genus=Anochetus&verbose=true

@mdoering, is there any reason not to upper-case the first letter of the scientific name? Probably in the match service.

**Comment by mdoering** [comment]
I recall we spotted that behavior before, but I cannot recall why exactly that should be. At least not for true bi/trinomials. It appears to be linked to the name parser which treats such names as if they are indetermined infraspecific names missing a genus:

http://api.gbif.org/v1/parser/name?name=abies%20alba

At least if the entire string is lower case this should not be an issue and we should Capitalize the potential genus?

**Comment by MattBlissett** [comment]
@timhirsch, this is now fixed. Markus deployed the new species match service, and I've reprocessed AntWeb. There are still lots of higher taxon matches, but there are also lots of names like "pogonomyrmex raj-ayma".

![Ant](https://api.gbif.org/v1/image/unsafe/https%3A%2F%2Fwww.antweb.org%2Fimages%2Fcasent0922556%2Fcasent0922556_p_1_high.jpg)

**Comment by mdoering** [comment]
most of these higher taxon occurrences look very suspicous:
https://www.gbif.org/occurrence/search?dataset_key=13b70480-bd69-11dd-b15f-b8a03c50a862&issue=TAXON_MATCH_HIGHERRANK

@timhirsch @ahahn-gbif Maybe its worth reporting back to them?
Looks like we could match to the genus instead of the family at least: https://github.com/gbif/checklistbank/issues/61

**Comment by mdoering** [comment]
Well, they at least have that exact name in AntWeb, so its not a bad mapping:
https://www.gbif.org/occurrence/1841338409
https://www.antweb.org/images.do?species=mg04&genus=lioponera&rank=species

**Comment by timhirsch** [comment]
Thanks for fixing, guys. However as you say there is still a huge volume (>100k) matched to higher taxon rank. I suggest the rest of the fix should really be at source rather than forcing you into much more work, and @laurarussell suggested she could get back to the AntWeb folks requesting them to look into it. She's busy at a workshop in China right now, so not expecting instant response ...

**Comment by ManonGros** [comment]
@laurarussell let me know if you are too busy to contact them and I will do it.
