### ISSUE TITLE
absence records apparently showing up among species occurrence searches

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1405]
**absence records apparently showing up among species occurrence searches**

We have apparently gone back to the situation where a large number of absence records submitted by e.g. the EBCC Atlas of European Breeding Birds are showing up when you search for particular species - albeit with an 'absent' label at the top of each occurrence record page. See e.g. this search for birds in Svalbard, which I suspect are nearly all absence records. 
`https://www.gbif.org/occurrence/search?country=SJ&dataset_key=c779b049-28f3-4daf-bbf4-0a40830819b6&taxon_key=212&advanced=1` . I guess this is a first step towards being able to deal better with absence records, but as it stands I think this produces a confusing picture as it appears to inflate the occurrence range of all European bird species ...

-----

User provided contact info: @timhirsch
System: Chrome 67.0.3396 / Mac OS X 10.13.5
User: [See in registry](https://www.gbif.org/api/feedback/user/78906c88114edcfaa945a5da849568c0:b1221b8c3b237616af2ba01340920599cf31e4ccbc17c718096a5944e8bf564258090f641d65352373fc882299ad3b1a3c429f72ac8900d7129cfacc4f4d868e)
Referer: https://www.gbif.org/occurrence/search?country=SJ&dataset_key=c779b049-28f3-4daf-bbf4-0a40830819b6&taxon_key=212&advanced=1
Window size: width 2451 - height 1378
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-14T13:44:02.026Z',mode:absolute,to:'2018-06-14T13:50:02.026Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-06-14T13:44:02.026Z',mode:absolute,to:'2018-06-14T13:50:02.026Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
There is no meaningful data "cleaning" we can do to keep this from happening. The records are valid, and very explicitly not only give individualCount=0, but also occurrenceStatus=absent. In a combination as this, we really should change processing and visualization so that these records 
- are filtered from map views
- do not contribute to occurrence counts (or contribute in a separate category of documented absences)
- are excluded from search results by applying a default facet filter that limits the result to presence data and includes absences only at explicit request
- do not contribute to metric, unless in a separate category
- are not included in downloads, unless explicitly requested and clearly marked as absences

**Comment by MortenHofft** [comment]
See also https://github.com/gbif/portal16/issues/308
