### ISSUE TITLE
GBIF Node for Herbarium GJO Austria

### ISSUE THREAD

**Issue by mmalicky** [gbif/portal-feedback#1453]
Dear GBIF People!

The access point for the Dataset from the Herbarium GJO in Austria has changed. The new adress is:

http://131.130.131.9/biocase/dsa_info.cgi?dsa=gbif_gjo

sincerely yours

Michael Malicky

**Comment by MattBlissett** [comment]
Dear Michael,

I've updated the dataset, which has brought it back online, but unfortunately this dataset doesn't have a license.  Since August 2016, we require one of three standard licenses for all datasets; those without a license were removed at that time.  There's some background information here: http://www.gbif.org/terms/licences

Is the dataset now licensed under one of the three supported licenses?

Thanks,

**Comment by mmalicky** [comment]
Dear Matt!

After my Summer holydays I got the info from GJO. The dataset should have a license by now.

sincerely yours

Michael

Von: Matt Blissett [mailto:notifications@github.com]
Gesendet: Montag, 23. Juli 2018 10:40
An: gbif/portal-feedback <portal-feedback@noreply.github.com>
Cc: Malicky, Michael <M.Malicky@landesmuseum.at>; Author <author@noreply.github.com>
Betreff: Re: [gbif/portal-feedback] GBIF Node for Herbarium GJO Austria (#1453)


Dear Michael,

I've updated the dataset, which has brought it back online, but unfortunately this dataset doesn't have a license. Since August 2016, we require one of three standard licenses for all datasets; those without a license were removed at that time. There's some background information here: http://www.gbif.org/terms/licences

Is the dataset now licensed under one of the three supported licenses?

Thanks,

**Comment by ahahn-gbif** [comment]
Dear Michael,
I was checking at http://131.130.131.9/biocase/utilities/queryforms/qf_manual.cgi?dsa=gbif_gjo, but it seems that the license information does not yet make it through the wrapper and into the public XML version. What we would like to find in the metadata section of an "ABCD2 search" operation is a section like this:
 ````
<abcd:IPR>
   <abcd:Licenses>
    <abcd:License language="en">
      <abcd:Text>CC 0</abcd:Text>
      <abcd:URI>http://creativecommons.org/publicdomain/zero/1.0/</abcd:URI>
    </abcd:License>
  </abcd:Licenses>
</abcd:IPR>
````
This may be a technical glitch - the diagnostic messages at the very end of a wrapper response indicate that elements were dropped due to missing parent elements. Please also be aware, though, that the license requirements are a bit stricter than in the past. The available choice is one out of the three CC0, CC-BY and CC-BY NC.

Best regards,
Andrea

**Comment by ahahn-gbif** [comment]
Checking again, the license information is now available with the metadata, but reads
 ````
<abcd:Licenses>
  <abcd:License language="en">
     <abcd:Text>CC BY-SA 3.0</abcd:Text>
     <abcd:URI>http://creativecommons.org/licenses/by-sa/3.0/</abcd:URI>
   </abcd:License>
</abcd:Licenses>
 ````
Share-alike licenses are not supported for GBIF occurrence data, since their terms cannot be applied to search results and downloads running across a range of different datasets. Please consider whether CC BY (or CC BY-NC) could be an option, as otherwise the dataset will remain excluded from indexing.

**Comment by ahahn-gbif** [comment]
Appears fixed on last checking at https://www.gbif.org/dataset/5830fa3c-497c-4d37-b771-bd6c84997f2c - closing
