### ISSUE TITLE
API query for species lists

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1495]
**API query for species lists**

Hi,

I'm trying to use the GBIF API to generate a species list using a WKT.

What I want returned is a table with 2 columns, the first 'species name', the second 'count of observations'. I want to add to the query a specified year range and WKT to search within.

Currently I have to pull down all the data and then summarise which takes a very long time.

Tom

-----

User provided contact info: tomaug@ceh.ac.uk
System: Chrome 68.0.3440 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/ec7037cde0b41d9afc4e633a795cb8d2:af53d2d7a7583ba70e7abf5253e352661c644b41756fa0d0997a6c451503e98e31886d6596a77bb74be773c3629b85259dc1b9b0bd961830a0d659c59412a35b)
Referer: https://www.gbif.org/developer/occurrence
Window size: width 1920 - height 943
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-16T15:59:14.043Z',mode:absolute,to:'2018-08-16T16:05:14.043Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-16T15:59:14.043Z',mode:absolute,to:'2018-08-16T16:05:14.043Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
For the wkt and year filter you can do something similar to this:

https://www.gbif.org/occurrence/taxonomy?has_geospatial_issue=false&year=1993,2018&geometry=POLYGON((10.96753%2054.6813,11.98977%2054.69842,10.99045%2055.04086,10.96753%2054.6813))

just on the API:
https://api.gbif.org/v1/occurrence/search?has_geospatial_issue=false&year=1993,2018&geometry=POLYGON((10.96753%2054.6813,11.98977%2054.69842,10.99045%2055.04086,10.96753%2054.6813))

That will give you the all the occurrences in that area (paginated). But as I understand it you want the distinct list of species and with counts. To do so you add a facet:
facet:speciesKey and since we don't care about the individual occurrences we set limit:0

https://api.gbif.org/v1/occurrence/search?has_geospatial_issue=false&year=1993,2018&geometry=POLYGON((10.96753%2054.6813,11.98977%2054.69842,10.99045%2055.04086,10.96753%2054.6813))&limit=0&facet=speciesKey

This will give you the distinct species (by their id) and their count. You can page through them with facetLimit and facetOffset

https://api.gbif.org/v1/occurrence/search?has_geospatial_issue=false&year=1993,2018&geometry=POLYGON((10.96753%2054.6813,11.98977%2054.69842,10.99045%2055.04086,10.96753%2054.6813))&limit=0&facet=speciesKey&facetLimit=10&facetOffset=10

To get the pretty name from the species IDs you need to use the species API
https://api.gbif.org/v1/species/2498255

So from the facet calls on the occurrence API you can get all the species IDs and their counts.
And from their you can look up the names of the species using the species API.

Hope that helps

**Comment by MortenHofft** [comment]
If you need to cite this, then you need a DOI. the only way to get that is to [trigger a download](https://www.gbif.org/occurrence/download?has_geospatial_issue=false&year=1993,2018&geometry=POLYGON((10.96753%2054.6813,11.98977%2054.69842,10.99045%2055.04086,10.96753%2054.6813))) with the initial filter. You don't have to download the data, but by generating the archive we issue a DOI for that subset of the data that you can quote.
