### ISSUE TITLE
Inspecting Occurrence Records

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1500]
**Inspecting Occurrence Records**

Are any of the occurrence records in GBIF for which the location data is based simply on a centroid?  That is, the taxon is known to exist within a region or geopolitical boundary so coordinates are based on a centroid within that boundary.  If so, is there anyway to identify such records so it is easier to exclude them?  If an organism exists mainly in coastal areas, occurrence records showing it existing many kilometers inland would be confusing.

-----

User provided contact info: @jameshansen91
System: Chrome 68.0.3440 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/685017b6ac16867bd5f798ebb021658b:e4f5201ce48094906d58a317a8a99a9bd05fa896adb52446a5262816733e00543c3714ce97e17b13143dd53bf38e03195126b3bf75c2ee86f8fc2ea6d10986e7)
Referer: https://www.gbif.org/occurrence/map?has_coordinate=true&has_geospatial_issue=false&taxon_key=5332004
Window size: width 1600 - height 763
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-20T17:19:17.021Z',mode:absolute,to:'2018-08-20T17:25:17.021Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-08-20T17:19:17.021Z',mode:absolute,to:'2018-08-20T17:25:17.021Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
I believe there are many such examples. Either centroids from countries, regions are sampling plots. In some cases it will be indicated by coordinate uncertainty. In others the [footprintWKT](https://www.gbif.org/occurrence/1658187592) reflects the actual (non-point) area. In others still the publisher have provided no such information.

I don't know of any good way to remove these records aside from looking at coordinateUncertainty and footprintWKT (which can be done after downloading). And that will only catch some of those cases you mention. It is up to the publisher to indicate it if an occurrence location is imprecise/centroid/obscured.

If you see examples that are obviously wrong, many publishers will appreciate being informed so they can fix it.

**Comment by MattBlissett** [comment]
@dschigel, do you have a link to the person who did some analysis and presented it at the GBIF user club?

**Comment by dschigel** [comment]
Antonelli and Zizka from Gotherburg; after ther closedown of the community site I need to dig into archives to find the slides; e-mails are easier. How urgent?

**Comment by dschigel** [comment]
A better idea - I think Zizka won ENC 2016 II place with this https://devpost.com/software/sampbias-7cigz5. Check this and other ENC2016 winners and submissions; a lot of good stuff.

**Comment by jhnwllr** [comment]
The short answer is that there are probably many records that are based simply on a country or regional centroid. 

There are some solutions available using R for removing such points. 
https://github.com/ropensci/CoordinateCleaner

But in general the CoordinateCleaner approach is to wholesale remove coordinates within a certain threshold of a potential centroid, which might be too conservative for certain purposes.

**Comment by ManonGros** [comment]
I think John's blogpost is addressing these questions: https://data-blog.gbif.org/post/country-centroids/

**Comment by abubelinha** [comment]
I have a question quite related to this issue, so I doubt I should open a new one.
(I have also looked at John's blogpost)

I have to publish an occurrence dataset with almost no georreferences. 
It only contains UTM grid coordinates for a few records (which I could convert to a combination of values for decimalLatitude, decimalLongitude, geodeticDatum and coordinateUncertaintyInMeters).

But for the vast majority of records, it only has a verbatim locality description. As it uses to be an administrative unit with well known boundaries (usually a county or province), I think I could calculate a WKT polygon and use the footprintWKT DwC concept.

My question is: would that footprintWKT alone be enough for the record to show up when a GBIF user searches occurrence data using a georreference bounding box?

I would prefer NOT to provide a centroid-based latitude and longitude because of all the reasons you mentioned in this issue.

If footprintWKT (plus datum) is enough, I would also like to know how GBIF portal compare boundingbox queries against footprintWKT, in order to solve if a occurrence record has to be shown or not.

- Does user-defined polygon need to fully enclose footprintWKT?
- Is a WKT intersection enough?
- Perhaps portal calculates footprintWKT centroids, which need to be inside the user-defined polygon? (although I don't think this would be correct)

Thanks

**Comment by ManonGros** [comment]
Hi @abubelinha, thanks for your questions!
Unfortunately, our system is not able to use the footprintWTK for searching by locations. In other words, without coordinates, users wouldn't be able to access the records when using bounding boxes and polygons on the [search map](https://www.gbif.org/occurrence/map?occurrence_status=present).

The best would be to provide the centroid coordinates together with the coordinate uncertainty as well as the footprintWTK.
You might be interested into checking this geo referencing best practise guide:
* https://docs.gbif-uat.org/georeferencing-best-practices/1.0/en/#polygons
* https://docs.gbif-uat.org/georeferencing-best-practices/1.0/en/#shape-method

**Comment by abubelinha** [comment]
Thank you @ManonGros

That's a shame. I am very concerned against providing centroids myself (at least for big areas), just because of all the reasons exposed.
- Unexperienced users expect GBIF coordinates to be exact occurrence points. I am tired of people complaining about "GBIF occurrence maps being inaccurate".
- Experienced users will surely know how to process WKT (calculating centroids, or whatever) to solve if a certain record matches or not their region of interest.

My previous question was as a data provider, bu I have also a related question as a final user.
If I want to find occurrence records which do provide footprintWKT, is it possible?
I mean, make queries to find only occurrences where footprintWKT contains some data.
(I am happy with doing it using the API, but I don't know if that is possible or not)

Also, I see data portal has a coordinateUncertaintyInMeters filter, which lets user provide upper and lower values for that field:
coordinateUncertaintyInMeters=910,9750
coordinateUncertaintyInMeters=0,9750

But is there any way to find only records where coordinateUncertaintyInMeters is null? 

Thanks a lot

**Comment by ManonGros** [comment]
Hi @abubelinha 

As far as I am aware, publishers don't often provide footprintWTK. [This dataset](https://www.gbif.org/dataset/bb30e03a-b746-49e4-bab9-decbf27abdf1) provides very detailed footprint as well as coordinates and coordinate uncertainty. It is a sampling-event dataset and not an occurrence dataset but they "performed validation procedures (Chapman, 2005a; 2005b) (geographic coordinate format, coordinates within provincial/county boundaries, absence of ASCII anomalous characters in the dataset) with Darwin Test (3.3) software (Pando, Lujano & Cezón, 2017)." so it might be worth checking it out.

For your other questions, it is possible to use the [occurrence download API](https://www.gbif.org/developer/occurrence#download) to query for NULL or NOT NULL values for specific fields by using the predicates `isNotNull` and `not`.
For example, you should be able to select records with non null coordinate uncertainty with this predicate:
```
{
  "creator":"userName",
  "notificationAddresses": ["userName@example.org"],
  "predicate":
  {
    "type":"isNotNull",
    "parameter":"coordinateUncertaintyInMeters"
  }
}
```
For more information, you can check the documentation.
Please let us know if you have any question or encounter any issue.

**Comment by ManonGros** [comment]
@abubelinha 
There is an other way to select for records with non-Null coordinate uncertainty in the web interface. You can choose the "Greater than or equal" option for coordinate uncertainty (which will select records for which the coordinate uncertainty is filled):
![Screenshot 2020-11-25 at 13 45 28](https://user-images.githubusercontent.com/7677271/100229571-bd86fa80-2f24-11eb-8812-671f97155170.png)
See this example: https://www.gbif.org/occurrence/search?coordinateUncertaintyInMeters=20,*&occurrence_status=present
