### ISSUE TITLE
SCAR associate participant page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1533]
**SCAR associate participant page**

Hi Currently on 
`https://www.gbif.org/participant/306`
the GBIF region is listed as Europe, could this be changed to Antarctica?

The same for 
`https://www.gbif.org/publisher/104e9c96-791b-4f14-978c-f581cb214912`

Country or area United Kingdom
could this be changed to Antarctica?

Kind Regards
Anton Van de Putte

-----

User provided contact info: antonarctica@gmail.com
System: Safari 11.1.2 / Mac OS X 10.13.6
User: [See in registry](https://www.gbif.org/api/feedback/user/d6f2071b380953f80446d6889a8756d5:133abfbb21ae31f2e6a9e755441b5ca93dfd3a6d05d0298273015cf0a281db222f685c640474b9a3a9c8ec2f7866cdca72484bf9a053ad3f13f537c387736f1a)
Referer: https://www.gbif.org/participant/306
Window size: width 1438 - height 764
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-09-04T08:26:16.187Z',mode:absolute,to:'2018-09-04T08:32:16.187Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-09-04T08:26:16.187Z',mode:absolute,to:'2018-09-04T08:32:16.187Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by timhirsch** [comment]
Anton - the region listed for GBIF participants, and the country listed for data publishers, refer to the location of the institutions themselves, rather than the location of data they deal with. For the regional affiliation, the only relevance is with regard to GBIF collaborations at regional level e.g. through regional node managers' meetings. Obviously an Antarctica affiliation would not make sense in this context. GBIF regions currently include only Europe, Africa, Asia, Oceania, Latin America and the Caribbean, and North America. Similarly, the 'country or area' location of the data publisher refers to the location of the institution sharing the data, rather than the country of origin of the data itself.
