### ISSUE TITLE
Bad fuzzy matching

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1540]
**Incorrect synonym**

Papilio rumiko records from iNaturalist appear to be classified as Zerynthia (Papilio) rumina, which is a different species. e.g.

`https://www.gbif.org/occurrence/1291103883`

is from iNaturalist:

`https://www.inaturalist.org/observations/3612214`

-----

User provided contact info: @jcoliver
System: Firefox 61.0.0 / Ubuntu 0.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/50c1da2598e49bcb209989f8d4497a18:1ee8ca89fc4a906a142af208ce978da667006a0d7a4ee6e8d68488e17a4461656c0d907fd083d9a1df59b08b9c2a9deaed162a2ac9e39007978930dbe710be82)
Referer: https://www.gbif.org/search?q=papilio%20rumiko
Window size: width 1366 - height 593
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-09-11T22:59:15.854Z',mode:absolute,to:'2018-09-11T23:05:15.854Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-09-11T22:59:15.854Z',mode:absolute,to:'2018-09-11T23:05:15.854Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by mdoering** [comment]
This is due to over eagerly fuzzy matching. In this case combining the scientific name normalization with a generic 1 char fuzzy match.

**Comment by mdoering** [comment]
There is not much room for tuning anymore if we want to avoid any false matching since even a single character can be a valid different name - usually in the same genus so the classification is identical too. The strict matching allows for some minimal normalization which I would consider very safe, so some minimal "fuzzy" matching would still be applied. This is very specific to latin names and covers frequent misspellings we know about - a lot like Tony Rees Taxon Match and IPNIs string cleaning routines. We use that also for fuzzy matching and on top of that we also allow for a single char difference - in this example the final o and a are removed and thus a single transposition is left which is picked up by the fuzzy matching. The [scientific name normalization](https://github.com/gbif/checklistbank/blob/master/checklistbank-common/src/main/java/org/gbif/checklistbank/utils/SciNameNormalizer.java#L37) is mostly folding to ASCII including normalization of ligatures, removal of double letters and silent "h" after a t or g and gender stemming of the terminal epithet. It is not applied at all to the genus of binomials or monomials, just species & infraspecific epithets. Arbitrary differences even of a single letter are not allowed. Some tests to showcase the behavior:
https://github.com/gbif/checklistbank/blob/master/checklistbank-common/src/test/java/org/gbif/checklistbank/utils/SciNameNormalizerTest.java#L11

I think thats safe to use, avoids false positives and gives us at least some minimal fuzzy awareness.
It is btw also what we use in the current CoL+ name matching implementation.

**Comment by ManonGros** [comment]
both Sabulina rosei and Papilio rumiko are in the new backbone (https://www.gbif.org/species/7450431 and https://www.gbif.org/species/10038125)

**Comment by jhnwllr** [comment]
This is fixed. The record is **no longer a fuzzy match** or  **Zerynthia (Papilio) rumina** 

https://www.gbif.org/occurrence/1291103883
