### ISSUE TITLE
Downloading Data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1596]
**Downloading Data**

I am trying to download the data I found, and the response says "Download is only supported for structured search-not free queried text search".  What does this mean?  I followed the prompts from the discussion board but I still get this response.  I am trying to find White River Group fossils with coordinate information attached to the data.  Can you please help?

-----

User provided contact info: evanoff@usc.edu
System: Chrome 69.0.3497 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/da1b014910502819abf683062c03697c:410b554d4187d023a0cbfbc3ecfb9860a14515d799214a8b03d46355d1591d375ce8f0be0f78563ef9c54854b5f895e8e30636830770bf52dbbc8d99db05483bddd4ac29101c5491068cd92f909c135e)
Referer: https://www.gbif.org/faq?q=why%20cant%20I%20download%20data
Window size: width 1920 - height 938
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-28T21:12:21.669Z',mode:absolute,to:'2018-10-28T21:18:21.669Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-10-28T21:12:21.669Z',mode:absolute,to:'2018-10-28T21:18:21.669Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
It means that searching for an arbitrary text string can give you results, but to download you have to limit your search using the filters. The reason is an annoying technical one. 

If you are looking for occurrences from a specific place in the world, you should use the location filter to draw or enter your location area (geometry)

For example like this:
https://www.gbif.org/occurrence/map?basis_of_record=FOSSIL_SPECIMEN&has_geospatial_issue=false&advanced=1&geometry=POLYGON((-108.00728%2043.49515,-107.57049%2044.24163,-106.83681%2044.32029,-106.26457%2043.97274,-107.40046%2043.15392,-107.51032%2042.13502,-106.98409%2042.13719,-106.83028%2042.88923,-106.22749%2043.38765,-105.4642%2043.95977,-106.16827%2044.66316,-107.67769%2044.72564,-108.75435%2043.82895,-108.00728%2043.49515))&geometry=POLYGON((-107.57418%2041.29941,-107.00014%2041.29941,-107.00014%2041.77342,-107.57418%2041.77342,-107.57418%2041.29941))

Hope that helps
