### ISSUE TITLE
Halimium alyssoides K.Koch under Cistus

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1705]
**Halimium alyssoides K.Koch under Cistus**

The species `Halimium alyssoides K.Koch` is marked as accepted [7331240](https://www.gbif.org/species/7331240) but has as parent `Cistus L.` [2874026](https://www.gbif.org/species/2874026). I would expect it to be listed under the accepted genus `Halimium` (`https://www.gbif.org/species/8277691).` Is this a bug?

-----

User provided contact info: @peterdesmet
System: Chrome 71.0.3578 / Mac OS X 10.14.1
User: [See in registry](https://www.gbif.org/api/feedback/user/ea18bdf34fde6f359eecd70ad7ca6fcd:5dafb39c06256ce503c77f327edf887c8154656ce5ff03de4fc8227c67d03d44a21c9ed4e82ae6d7388f2826213466675ceaf80f3bb47b5090526be595a92a56)
Referer: https://www.gbif.org/species/7331240
Window size: width 1354 - height 797
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-21T16:32:59.659Z',mode:absolute,to:'2018-12-21T16:38:59.659Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-12-21T16:32:59.659Z',mode:absolute,to:'2018-12-21T16:38:59.659Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
@mdoering: Could you verify this is rather a backbone issue?

**Comment by mdoering** [comment]
Yes, thats why it has the issue `Name parent mismatch`.
It comes from the GRIN dataset which has it like that: https://www.gbif.org/species/101344908
But also because of some data problem: 

> Parent relation taken from synonym Halimium (Dunal) Spach

In that case the verbatim GRIN data is like this:

taxonID | acceptedID | parentID | scientificName
--- | --- | --- | --- 
f266 |  | | Cistaceae Juss., nom. cons.
g2633 |  | f266 | Cistus L.
g5324 | g2633 | f266 | Halimium (Dunal) Spach
450954 |  | g5324 | Halimium alyssoides (Lam.) K. Koch

So we have Halimium alyssoides being an accepted child of genus Halimium which is considered a synonym of Cistus. The normalizer then moves the species under the accepted genus which is weird in this case and gets flagged. Synonyms cannot have accepted children in CLB for good reasons. What would you expect, should the species instead be moved under the family in this case?

**Comment by peterdesmet** [comment]
No, given the fact that `Halimium` is considered a synonym of `Cistus` the current action - listing it under `Cistus` but marking it with `Name parent mismatch` - makes sense.

**Comment by ManonGros** [comment]
Could you let me know if this issue can be closed?

**Comment by peterdesmet** [comment]
Yes, can be closed.
