### ISSUE TITLE
failure in downloading csv file

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1729]
**failure in downloading csv file**

-----

User provided contact info: anaipz@live.com.mx
System: Chrome 71.0.3578 / Windows 8.1.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/15f76bdc0a39cbe61c5af30c97638ef5:64c1216350a92fa0e9b436943ee0262ffc9d9c643d3572b5dd189ec1247bf716e47719325d8c8e33c75130fd56c6e3bc4bea9426f067dab6789be8f9a62fbcbf)
Referer: https://www.gbif.org/occurrence/download?taxon_key=2826838
Window size: width 1366 - height 626
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-14T19:22:31.964Z',mode:absolute,to:'2019-01-14T19:28:31.964Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-01-14T19:22:31.964Z',mode:absolute,to:'2019-01-14T19:28:31.964Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
Cannot reproduce, download works as expected at the time of testing. Contacting the user with the functional download URL, requesting more detail in case the issue persists.

**Comment by MattBlissett** [comment]
Yesterday evening downloads had reached deadlock, this has happened once before.

We limit the cluster to running 8 simultaneous download jobs, but it's possible for those 8 jobs to be waiting for sub-jobs to complete -- and the sub-jobs are waiting for a chance to run, since there are 0/8 free slots.  I'm going to 

- [ ] improve the monitoring for deadlock / many "accepted" but not "running" cluster tasks.

I think it's likely this user reached the limit of 3 simultaneous downloads per user, and was blocked from making further downloads.
