### ISSUE TITLE
How frequently are new occurrence records added?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1848]
**How frequently are new occurrence records added?**

-----

User provided contact info: asanders@mobot.org
System: Chrome 72.0.3626 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/387628b885c148b679e55a9d73fa0805:d56304d574cfc2f85cee63c5a4ec9c9f5b71a01aa9254e24490ebe18ec1c558f4d0fbb8a4d56a02633ead7854b6bb435b1173f621bd8f293042c11d34ca60ff0)
Referer: https://www.gbif.org/health
Window size: width 1920 - height 1009
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-19T13:37:25.808Z',mode:absolute,to:'2019-03-19T13:43:25.808Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-19T13:37:25.808Z',mode:absolute,to:'2019-03-19T13:43:25.808Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by MattBlissett** [comment]
Hi,

I'm not exactly sure of the question, so I will answer several possible questions:

1) There are two ways GBIF knows about new or updated occurrence datasets:

- A publisher notifies us of a new or updated dataset.  For example, five minutes ago this dataset: https://www.gbif.org/dataset/989f6285-841c-47a4-991b-3d3396427f02 was updated with 99 new and 26 modified records.

- We check every 7 days or so for updates to datasets, in case we haven't been notified, or the software doesn't support notifying us directly.

Most publishers (including MOBOT) use the first method, so we know very quickly if there are new or updated occurrence records available to GBIF.

2) Either way, the dataset then enters a queue for processing of its occurrence records.  Datasets vary in size, but we can update or import around 500 occurrences per second.

3) In the last month, there have been about 15 million new occurrence records, and about 47 million updates to existing occurrence records.  Statistics on the total number of records in GBIF are calculated quarterly, and charts shown here: https://www.gbif.org/analytics/global — we can provide the raw numbers if you need them.

4) MOBOT's dataset, Tropicos Specimen Data https://www.gbif.org/dataset/7bd65a7a-f762-11e1-a439-00145eb45e9a , has previously notified GBIF of updates approximately weekly, although we haven't seen any update since June last year, and no new records since June 2016: https://management-tools.gbif.org/crawl-history?uuid=7bd65a7a-f762-11e1-a439-00145eb45e9a

5) Most datasets are either static (never change once published) or updated approximately weekly.

6) Occasionally, all of this is paused while we upgrade servers, software or data (like our taxonomic backbone).  Usually the pause is for under an hour, but for major upgrades it can be several days or around a week.

I hope that helps!

Matt Blissett

On 19/03/2019 14:42, gbif-portal wrote:

How frequently are new occurrence records added?

________________________________

User provided contact info: asanders@mobot.org<mailto:asanders@mobot.org>
System: Chrome 72.0.3626 / Windows 7.0.0
User: See in registry<https://www.gbif.org/api/feedback/user/387628b885c148b679e55a9d73fa0805:d56304d574cfc2f85cee63c5a4ec9c9f5b71a01aa9254e24490ebe18ec1c558f4d0fbb8a4d56a02633ead7854b6bb435b1173f621bd8f293042c11d34ca60ff0>
Referer: https://www.gbif.org/health
Window size: width 1920 - height 1009
API log<http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-19T13:37:25.808Z',mode:absolute,to:'2019-03-19T13:43:25.808Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc))>
Site log<http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-03-19T13:37:25.808Z',mode:absolute,to:'2019-03-19T13:43:25.808Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc))>
System health at time of feedback: CRITICAL
