### ISSUE TITLE
occurrences from Plazi do not show up

### ISSUE THREAD

**Issue by myrmoteras** [gbif/portal-feedback#1865]
Why do occurrences in recent uploaded DWCA by Plazi not show up? The acceppted names show up, e.g. https://www.gbif.org/dataset/5eacc4c2-0f72-4ac8-8ba6-66814d99ba96 or https://www.gbif.org/dataset/67b19f09-43b9-45ce-9455-a3f7b84207cc

**Comment by MortenHofft** [comment]
I believe this is due to the ingestion delay as ebird is being indexed (despite the message only mentioning occurrence datasets). The delays are expected to last until Tuesday.

This has been added as a discreet notification on the website
<img width="674" alt="Screen Shot 2019-03-28 at 20 31 46" src="https://user-images.githubusercontent.com/6759267/55187163-9baa0300-5198-11e9-91e3-3a91d9d36f67.png">
