### ISSUE TITLE
dead image links

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#1921]
**dead image links**
Most of the images on https://www.gbif.org/occurrence/gallery?dataset_key=5c1fdaf6-4a18-4c5d-a84b-a4ba41f077c9&year=1800&advanced=1&network_key=1f2c0cbe-40df-43f6-ba07-e76133e78c31 are dead links

-----

User provided contact info: @MortenHofft
System: Chrome 73.0.3683 / Mac OS X 10.11.6
User: [See in registry](https://www.gbif.org/api/feedback/user/8a7f1d8576843832748e4a51faf9b523:c4f1b2d9ada90e7b3dbf0b92788c007fef31e5dac9aafd907720097bda803792efc1cb7a5ad438bdef4840ccbc6e40089526e4804929ca05e9cff07036b5227a)
Referer: https://www.gbif.org/occurrence/gallery?dataset_key=5c1fdaf6-4a18-4c5d-a84b-a4ba41f077c9&year=1800&advanced=1&network_key=1f2c0cbe-40df-43f6-ba07-e76133e78c31
Window size: width 1593 - height 1257
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-01T06:14:07.499Z',mode:absolute,to:'2019-05-01T06:20:07.499Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-01T06:14:07.499Z',mode:absolute,to:'2019-05-01T06:20:07.499Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
I haven't found a link that was unresponsive.

However, I think that the problem comes from the fact that some some associated media are mapped in the `associatedMedia` field without any format specified. For example, for [this occurrence](https://www.gbif.org/occurrence/1146321809) (which is displayed as a broken link), the two images from the multimedia file are displayed properly but there is a third link `http://arctos.database.museum/MediaSearch.cfm?collection_object_id=23609549` which is included in `associatedMedia` field in the occurrence file. There is no file extension in the URL so we don't know what type of media it is.

It might be a good idea to have all the associated media in the multimedia file instead.

**Comment by MattBlissett** [comment]
Sorry, I never commented.

We were blocked *again* by Arctos, and I've changed the IP address we use, again.  At some point, they will probably block the whole IP range again. (There are still 450k images in Arctos which we don't have cached, we have about 80k cached.)

See also https://github.com/gbif/portal16/issues/343
