### ISSUE TITLE
different numbers of rows (query results and download file)

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2012]
**different numbers of rows (query results and download file)**

I don't understand why the number of rows differs between the query results (510 000), the download page (4.6 million) and the actual csv file downloaded (1.04 million). This is the download information: `https://www.gbif.org/occurrence/download/0019538-190415153152247`

-----

User provided contact info: w.coetzer@saiab.ac.za
System: Chrome 74.0.3729 / Windows 7.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/5d0eae52adbb17c105f7b5a802430f67:e11446163d533e12cf8a548d66f5df6cfabafeb1367657f4369799010f2186f162713b9046d6373c44b4aa12764ac49fd3ca9c43a35cf92d4fbb8251d236c708)
Referer: https://www.gbif.org/occurrence/download/0019538-190415153152247
Window size: width 1920 - height 926
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-28T15:58:50.359Z',mode:absolute,to:'2019-05-28T16:04:50.359Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-05-28T15:58:50.359Z',mode:absolute,to:'2019-05-28T16:04:50.359Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
Query results: https://www.gbif.org/occurrence/search?taxon_key=4334&taxon_key=7905&taxon_key=7908&taxon_key=7911&taxon_key=4345&taxon_key=7901 — 4,642,239

Download: https://www.gbif.org/occurrence/download/0019538-190415153152247 — 4,642,239

```
$ unzip -p 0019538-190415153152247.zip 0019538-190415153152247.csv | wc -l                                                                                                                                                                                           
4,642,249
```

9 extra records (plus one header line), which have presumably been deleted since last night.

1.04 million is 1024² or 2²⁰, which is the row limit in Excel and LibreOffice.

I have *not* replied by email, as I don't know what our usual advice is on software for processing large downloads.

**Comment by ManonGros** [comment]
Replied by email.
