### ISSUE TITLE
plazi: treatment data: materialsCitation wrong

### ISSUE THREAD

**Issue by myrmoteras** [gbif/portal-feedback#2035]
in this case, https://www.gbif.org/species/157436051  too many observation records are shown, and the New species has no space between the new species and taxonomic name

![image](https://user-images.githubusercontent.com/4609956/59159734-5a09d280-8ace-11e9-9ee9-f546aad31514.png)

![image](https://user-images.githubusercontent.com/4609956/59159760-a1905e80-8ace-11e9-8ccb-d7a7348dd35e.png)

**Comment by MortenHofft** [comment]
**regarding the map**
@thomasstjerne I don't believe there is a way to filter the occurrences based on the verbatim taxonKey or taxonID or similar, so I suspect there is no way we can show this map without post filtering, but since it is a geojson map this should be fine.

**The missing spaces**
There is no space provided in the verbatim description in the API. If it is published with a space, then there is an API bug.
```
"http://purl.org/dc/terms/description": "<div><p>Probolomyrmex kelleriNew species</p><p> ( Figs. 20 , 21 , 22 , 23) </p><p> ..."
```

**Comment by MortenHofft** [comment]
Notice that this also relates to the long standing feature request to be able to search occurrences by their verbatim taxonKey, verbatim ScientificName etc. 
https://github.com/gbif/portal16/issues/365
