### ISSUE TITLE
ABCD archive triplet duplicates → occurrenceid, collectioncode, institutioncode and catalognumber 

### ISSUE THREAD

**Issue by muttcg** [gbif/portal-feedback#2052]
There is an ABCD dataset -> https://www.gbif.org/dataset/8130e5c6-f762-11e1-a439-00145eb45e9a

The dataset contains - **116_893** records

Now when we run the same dataset for current production and "pipelines" project we get a different number of records.

The normal way how we identify duplicate is occurrenceid or triplet (collectioncode, institutioncode and catalognumber), ABCD archive doesn't have occurrenceid, so we use triplet to get gbifId, but for this archive, I found thousands of records with the same triplet:

SELECT SUM(sub.cc) FROM
(
    SELECT 
        count(*) AS cc
    FROM occurrence_hbase oh 
    WHERE oh.datasetkey = '8130e5c6-f762-11e1-a439-00145eb45e9a'
    GROUP BY 
        oh.occurrenceid, 
        oh.collectioncode, 
        oh.institutioncode, 
        oh.catalognumber
    HAVING count(*) > 1
) AS sub

The result is **12_591** records, it means 2 or more identical values for a group of fields -> occurrenceid, collectioncode, institutioncode and catalognumber

Could you please investigate this archive, why do we have so many duplicated triplets?

**Comment by MattBlissett** [comment]
1) Adding `AND oh.crawlid = 85` excludes many duplicates. See https://github.com/gbif/pipelines/issues/184

2) There are duplicate UnitIDs (the ABCD term mapped to catalogNumber) in this dataset.

```
cd storage/xml/8130e5c6-f762-11e1-a439-00145eb45e9a/85
grep 'UnitID>' */* | wc -l
grep 'UnitID>' */* -h | sort | uniq | wc -l
```

Example record:
* https://api.gbif.org/v1/occurrence/1837883188
* https://api.gbif.org/v1/occurrence/1838273209

The lookup records for those records:
```
 54:8130e5c6-f762-11e1-a439-00145eb45e9a|Institute of Geology at TUT|GIT|537-1692-1|Trypanites? isp. column=o:i, timestamp=1553906941888, value=\x00\x00\x00\x00m\x8B\xDF4
 56:8130e5c6-f762-11e1-a439-00145eb45e9a|Institute of Geology at TUT|GIT|537-1692-1|Sanctum? isp. column=o:i, timestamp=1553906941888, value=\x00\x00\x00\x00m\x91\xD2\xB9
```

For keys from XML datasets, we set the property `unitQualifier` to the scientific name.

Now it gets weird, the fragments are the same: https://api.gbif.org/v1/occurrence/1837883188/fragment -- https://api.gbif.org/v1/occurrence/1838273209/fragment

I will investigate further later; Tim suspects an inconsistency in handling the unitQualifier.

**Comment by MattBlissett** [comment]
The example record has two identifications: *Trypanites? isp.* and *Sanctum? isp.*:

```
<Unit>
  <SourceInstitutionID>Institute of Geology at TUT</SourceInstitutionID>
  <SourceID>GIT</SourceID>
  <UnitID>537-1692-1</UnitID>
  <UnitIDNumeric>301048</UnitIDNumeric>
  <DateLastEdited>2018-04-09T16:34:47</DateLastEdited>
  <Identifications>
    <Identification>
      <Result>
        <TaxonIdentified>
          <HigherTaxa>
            <HigherTaxon>
              <HigherTaxonName>Ichnofossils</HigherTaxonName>
              <HigherTaxonRank>unranked</HigherTaxonRank>
            </HigherTaxon>
          </HigherTaxa>
          <ScientificName>
            <FullScientificNameString>Sanctum? isp.</FullScientificNameString>
          </ScientificName>
        </TaxonIdentified>
      </Result>
      <PreferredFlag>1</PreferredFlag>
    </Identification>
    <Identification>
      <Result>
        <TaxonIdentified>
          <HigherTaxa>
            <HigherTaxon>
              <HigherTaxonName>Ichnofossils</HigherTaxonName>
              <HigherTaxonRank>unranked</HigherTaxonRank>
            </HigherTaxon>
          </HigherTaxa>
          <ScientificName>
            <FullScientificNameString>Trypanites? isp.</FullScientificNameString>
          </ScientificName>
        </TaxonIdentified>
      </Result>
      <PreferredFlag>1</PreferredFlag>
    </Identification>
  </Identifications>
  …
```

They both have `PreferredFlag` set, so our system creates that as two occurrences, https://api.gbif.org/v1/occurrence/1837883188 and  https://api.gbif.org/v1/occurrence/1838273209.

The duplicate UnitIDs are presumably because we do a BioCASe search by scientific name. The record is returned when we search for S* and for T*.

Adding that to the Hive query:
```
SELECT
count(oh.gbifid) AS cc, oh.occurrenceid,
oh.collectioncode,
oh.institutioncode,
oh.catalognumber,
oh.unitqualifier
FROM occurrence_hdfs oh
WHERE oh.datasetkey = '8130e5c6-f762-11e1-a439-00145eb45e9a'
and oh.crawlid = '86'
GROUP BY
oh.occurrenceid,
oh.collectioncode,
oh.institutioncode,
oh.catalognumber,
oh.unitqualifier
HAVING count(oh.gbifid) > 1
```

Shows some even stranger cases… (TBC).

**Comment by MattBlissett** [comment]
We are left with some occurrences with null institution, collection and catalogue numbers, for example these:

```
1 | 1228055347 | NULL | NULL | NULL | NULL | Entelophyllum ex gr. roemeri Wedekind, 1927
2 | 1228055348 | NULL | NULL | NULL | NULL | Entelophyllum ex gr. roemeri Wedekind, 1927
3 | 1228055349 | NULL | NULL | NULL | NULL | Entelophyllum ex gr. roemeri Wedekind, 1927
4 | 1228055350 | NULL | NULL | NULL | NULL | Entelophyllum ex gr. roemeri Wedekind, 1927
```

Picking https://api.gbif.org/v1/occurrence/1228055350/fragment, the same fragment is also used for the occurrence https://api.gbif.org/v1/occurrence/1098954127/fragment

The lookup keys are fine:

```
 74:8130e5c6-f762-11e1-a439-00145eb45e9a|Institute of Geology at TUT|GIT|713-5|null column=o:i, timestamp=1553905943910, value=\x00\x00\x00\x00A\x80\xB5\x8F
 24:8130e5c6-f762-11e1-a439-00145eb45e9a|Institute of Geology at TUT|GIT|713-5|Entelophyllum ex gr. roemeri Wedekind, 1927 column=o:i, timestamp=1553907430351, value=\x00\x00\x00\x00I2\xA36
```

But the verbatim occurrence for the second occurrence is empty: https://api.gbif.org/v1/occurrence/1098954127/verbatim and https://api.gbif.org/v1/occurrence/1228055350/verbatim

The problem is here:
https://github.com/gbif/occurrence/blob/000837e8c9860a3213dda44d5b924bee4753462a/occurrence-parser/src/main/java/org/gbif/occurrence/parsing/xml/XmlFragmentParser.java#L132-L141

The `unitQualifier` can be null, as in this case (there is no `FullScientificNameString` on one of the identifications).
1. For the uq:null record, the method returns the first (random) record
2. For the uq:not-null record, the method (randomly) hits an NPE, if the null record is first in the loop.

I'm testing a fix.
