### ISSUE TITLE
Excluding Aves from occurrence downloads

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2053]
**Excluding Aves from occurrence downloads**

Dear GBIF,  Is there a possibility of looking at providing a way of excluding certain classes of organism from occurrence downloads. The biggest problem is for Aves under Animalia with 888 million occurrence records. When data is downloaded for a particular country or other set, the bird data accounts for the majority of the data. For those of us who do not work with this data it has to be filtered out. The option to exclude Aves under Animalia or others when spinning up an occurrence download would be really helpful and reduce download sizes significantly. If I have missed some way of filtering out in the interface then please ignore this!. All the best, Paul Oldham

-----

User provided contact info: @poldham
System: Chrome 74.0.3729 / Mac OS X 10.14.4
User: [See in registry](https://www.gbif.org/api/feedback/user/6e04f5f93931b931443f0728fb63f3e5:6731eb208b8e5819fe23aedb69e3032ebb595eb2e6aa1fb9bd6f6b82647af08a5afc4b89fed4af770d4fb14412b96ca7a6aec7b8e90e594e3d7e24b2bdfb0c1a)
Referer: https://www.gbif.org/occurrence/download
Window size: width 1534 - height 1049
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-19T11:48:33.233Z',mode:absolute,to:'2019-06-19T11:54:33.233Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-19T11:48:33.233Z',mode:absolute,to:'2019-06-19T11:54:33.233Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by jhnwllr** [comment]
Hi @poldham 

Right now there is no simple way to do exclusion downloads.  

However, I thought the problem was interesting and might be useful for others, so I decided to construct the query you would need in order to get no birds. 

#  **no birds** query

```
https://www.gbif.org/occurrence/search?taxon_key=119&taxon_key=120&taxon_key=121&taxon_key=131&taxon_key=133&taxon_key=134&taxon_key=135&taxon_key=136&taxon_key=137&taxon_key=139&taxon_key=140&taxon_key=143&taxon_key=144&taxon_key=146&taxon_key=158&taxon_key=159&taxon_key=175&taxon_key=176&taxon_key=199&taxon_key=203&taxon_key=204&taxon_key=205&taxon_key=206&taxon_key=207&taxon_key=209&taxon_key=210&taxon_key=211&taxon_key=213&taxon_key=214&taxon_key=215&taxon_key=216&taxon_key=221&taxon_key=222&taxon_key=224&taxon_key=225&taxon_key=226&taxon_key=229&taxon_key=235&taxon_key=236&taxon_key=238&taxon_key=239&taxon_key=247&taxon_key=248&taxon_key=249&taxon_key=250&taxon_key=251&taxon_key=252&taxon_key=253&taxon_key=254&taxon_key=255&taxon_key=256&taxon_key=276&taxon_key=277&taxon_key=278&taxon_key=281&taxon_key=290&taxon_key=307&taxon_key=308&taxon_key=309&taxon_key=345&taxon_key=346&taxon_key=347&taxon_key=350&taxon_key=351&taxon_key=352&taxon_key=353&taxon_key=354&taxon_key=355&taxon_key=356&taxon_key=358&taxon_key=359&taxon_key=360&taxon_key=361&taxon_key=365&taxon_key=367&taxon_key=5964034&taxon_key=5967490&taxon_key=7188530&taxon_key=7188589&taxon_key=7194193&taxon_key=7375758&taxon_key=7496922&taxon_key=7664204&taxon_key=7742773&taxon_key=7774442&taxon_key=7799559&taxon_key=7920181&taxon_key=8066236&taxon_key=8246594&taxon_key=8355438&taxon_key=8365233&taxon_key=9238047&taxon_key=9251154&taxon_key=9273948&taxon_key=9304242&taxon_key=9312928&taxon_key=9421786&taxon_key=9424764&taxon_key=9455590&taxon_key=9632402
```

This is all of the taxon keys for classes that are **not birds**. 

This strategy only works for ranks with **less than 200 species** as that is the upper limit for taxon keys in the system. Fortunately for the case of animals, there are only [100 non-bird classes](https://www.gbif.org/species/search?rank=CLASS&highertaxon_key=1&status=ACCEPTED&status=DOUBTFUL)

You can also look at the [gallery](https://www.gbif.org/occurrence/gallery?taxon_key=119&taxon_key=120&taxon_key=121&taxon_key=131&taxon_key=133&taxon_key=134&taxon_key=135&taxon_key=136&taxon_key=137&taxon_key=139&taxon_key=140&taxon_key=143&taxon_key=144&taxon_key=146&taxon_key=158&taxon_key=159&taxon_key=175&taxon_key=176&taxon_key=199&taxon_key=203&taxon_key=204&taxon_key=205&taxon_key=206&taxon_key=207&taxon_key=209&taxon_key=210&taxon_key=211&taxon_key=213&taxon_key=214&taxon_key=215&taxon_key=216&taxon_key=221&taxon_key=222&taxon_key=224&taxon_key=225&taxon_key=226&taxon_key=229&taxon_key=235&taxon_key=236&taxon_key=238&taxon_key=239&taxon_key=247&taxon_key=248&taxon_key=249&taxon_key=250&taxon_key=251&taxon_key=252&taxon_key=253&taxon_key=254&taxon_key=255&taxon_key=256&taxon_key=276&taxon_key=277&taxon_key=278&taxon_key=281&taxon_key=290&taxon_key=307&taxon_key=308&taxon_key=309&taxon_key=345&taxon_key=346&taxon_key=347&taxon_key=350&taxon_key=351&taxon_key=352&taxon_key=353&taxon_key=354&taxon_key=355&taxon_key=356&taxon_key=358&taxon_key=359&taxon_key=360&taxon_key=361&taxon_key=365&taxon_key=367&taxon_key=5964034&taxon_key=5967490&taxon_key=7188530&taxon_key=7188589&taxon_key=7194193&taxon_key=7375758&taxon_key=7496922&taxon_key=7664204&taxon_key=7742773&taxon_key=7774442&taxon_key=7799559&taxon_key=7920181&taxon_key=8066236&taxon_key=8246594&taxon_key=8355438&taxon_key=8365233&taxon_key=9238047&taxon_key=9251154&taxon_key=9273948&taxon_key=9304242&taxon_key=9312928&taxon_key=9421786&taxon_key=9424764&taxon_key=9455590&taxon_key=9632402) and enjoy the absence of birds :).

**Comment by poldham** [comment]
Many thanks John,  I would not have thought of that strategy and so really interesting to see. I like birds, just not 888 million! Thanks again, Best, Paul
