### ISSUE TITLE
Is Grapholita pruinvorana supposed to be G. prunivora

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2059]
**Is Grapholita pruinvorana supposed to be G. prunivora**

Hi GBIF, 
the entry for Grapholita lobarzewskii has it present in the United States and Canada under the synonym Grapholita prunivorana. However, I can't find other sources saying G. prunvorana is in the US and Canada. Is G. prunivorana being confused with G. prunivora in the database. G. prunivora is present in the US and and Canada.

Thanks!

-----

User provided contact info: glenn.fowler@aphis.usda.gov
System: Edge 17.17134.0 / Windows 10.0.0
User: [See in registry](https://www.gbif.org/api/feedback/user/9a5383177055a89460ef140978e28c9e:8f3ac844f8ae553f93d9aad983987ee077982c83f851d1d4d5f7a3feae3a139fbfbad4fe6d89741ecd63a24ccfbbcc444d2bf4ff26e23ab1cb82462f6518365e)
Referer: https://www.gbif.org/faq?question=opening-gbif-csv-in-excel
Window size: width 1133 - height 507
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-24T17:11:34.148Z',mode:absolute,to:'2019-06-24T17:17:34.148Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-06-24T17:11:34.148Z',mode:absolute,to:'2019-06-24T17:17:34.148Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
It looks like [all the occurrences of G. prunivorana that we have](https://www.gbif.org/occurrence/search?taxon_key=4529991) are fuzzy matches. By clicking around it seems that these are in fact Grapholita prunivora (see [this example](https://www.gbif.org/occurrence/1847253295)).

[Apparently we are missing Grapholita prunivora in the backbone](https://www.gbif.org/species/search?q=Grapholita%20prunivora), which is why we get this result.
