### ISSUE TITLE
[Occurrence] button link slightly confused

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#206]
**[Occurrence] button link slightly confused**

The [occurrence] link on the RBG, Kew dataset takes you to a search for all occurrence datasets.  Given that this originates from an installation page, I had anticipated seeing all occurrence datasets from the installation, or perhaps the hosting organisation.

-----
fbitem-b575683b032fd6f6cf463f9d32dfa742d06986e6
Reported by: @timrobertson100
System: Chrome 58.0.3029 / Mac OS X 10.11.5
Referer: https://demo.gbif.org/installation/996e30f8-f762-11e1-a439-00145eb45e9a
Window size: width 1246 - height 1063
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-07T15:18:04.005Z',mode:absolute,to:'2017-06-07T15:24:04.005Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-07T15:18:04.005Z',mode:absolute,to:'2017-06-07T15:24:04.005Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Basically it is the same styling for displaying all datasets results and the idea was that those grey links were used as tags for search. But I see what you mean. We could style these results differently. I just liked that they always looked the same and did the same. 

Searching occ datasets by installation is not something the API provides i believe. But if we expanded the API it would make sense. In that case i would porbably just link to the search results instead of showing a list.

**Comment by gbif-portal** [comment]
Closed and transferred to  https://github.com/gbif/portal16/issues/447
