### ISSUE TITLE
Invalid country code for GRIIS keyword

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2113]
**Invalid country code for GRIIS keyword**

The agreed convention for Griis has been to use keywords to tag countries. But country_IC isn't a valid country code (according to us). It should be country_ES-IC perhaps?

-----

User provided contact info: @MortenHofft
System: Chrome 75.0.3770 / Mac OS X 10.14.5
User: [See in registry](https://www.gbif.org/api/feedback/user/edd3d54c73ea7e3e249db14f9d6367ed:f7b5ff1aca113ed642805878d757a644660a26a7f0c7a6ca853662fea717aabe0088f18ed34d913d775b50768823a63b5708a9981c1827270bffaabe77b3e157)
Referer: https://www.gbif.org/dataset/aaa48ec4-fd8c-466c-ae23-6cf72184ddb0
Window size: width 1715 - height 1303
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-19T11:39:08.893Z',mode:absolute,to:'2019-07-19T11:45:08.893Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-07-19T11:39:08.893Z',mode:absolute,to:'2019-07-19T11:45:08.893Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
Notified by email

**Comment by kcopas** [comment]
Looks like `ES-CN`—See entry for Canarias here: 
https://www.iso.org/obp/ui/#iso:code:3166:ES

Can't see that Tenerife has a separate one of its own. We managed with the likes of Saba and Sint Eustatius, but I think they had valid ISO 3166-2 codes…

**Comment by ahahn-gbif** [comment]
Fixed by the publisher and now showing correctly, also for the following:
(two-letter ISO codes only marking territories without a country code)

Country | Country or Territory | ISO code
-- | -- | --
France | French   Southern and Antarctic Lands Terres australes et antarctiques françaises   (TAAF) | FR-TF
France | French Southern and   Antarctic Territories (TAAF) - Scattered Islands -Îles Éparses | FR-TF
France | Mayotte | FR-YT
France | New   Caledonia | FR-NC
France | Saint   Barthelemy | FR-BL
France | Wallis and Futuna | FR-WF
Netherlands | Aruba | NL-AW
Netherlands | Bonaire | NL-BQ1
Netherlands | Curaçao | NL-CW
Netherlands | Saba | NL-BQ2
Netherlands | Sint   Eustatius | NL-BQ3
Netherlands | Sint Maarten | NL-SX
United   States of America | Alaska | US-AK
United States of America | American Samoa | AS
Portugal | Azores | PT-20
Spain | Canarias- El Hierro | ES-CN
Spain | Canarias- Fuerteventura | ES-CN
Spain | Canarias- Gran Canaria | ES-CN
Spain | Canarias- La Gomera | ES-CN
Spain | Canarias- La Palma | ES-CN
Spain | Canarias- Lanzarote | ES-CN
Spain | Canarias- Tenerife | ES-CN
United Kingdom | Cayman Islands -Cayman   Brac | KY
United Kingdom | Cayman Islands -Grand   Cayman | KY
United Kingdom | Cayman Islands -Little   Cayman | KY
Federated States of   Micronesia | Chuuk | FM-TRK
Denmark | Faroe Islands | FO
Ecuador | Galapagos | EC-W
United   States of America | Hawaii | US-HI
Chile | Juan Fernandez Islands | CL
Federated States of   Micronesia | Kosrae | FM-KSA
Portugal | Madeira | PT-30
Comoros | Mwali (Mohéli) | KM-M
Comoros | Ndzuwani (Anjouan) | KM-A
Comoros | Ngazidja (Grande Comore) | KM-G
United   States of America | Northern Mariana Islands | MP
Federated States of   Micronesia | Pohnpei | FM-PNI
Chile | Rapa Nui - Easter   Islands | CL
Yemen- Soqotra | Soqotra | YE-SO
Norway | Svalbard | SJ
New Zealand | Tokelau | TK
Federated States of   Micronesia | Yap | FM-YAP
United Kingdom | Anguilla | AI
United Kingdom | Cayman Islands | KY
United   Kingdom | Pitcairn Island,   Henderson, Ducie and Oeno Islands | PN

**Comment by MattBlissett** [comment]
Many of those places *do* have a two-letter code, and I don't think they should have been changed to the sub-codes above.

TF, YT, NC, BL, WF, AW, CW, SX.

BQ is a code for Bonaire, Saba and Sint Eustatius together.

We don't index data to sub-regions, so "Recorded as introduced in 20 countries and islands" won't get any results for FR-YT, and it shows up as "France" rather than "Mayotte".

https://www.gbif.org/species/5274863

**Comment by ahahn-gbif** [comment]
Updated overview
(two-letter-ISO-codes-only marking territories without a country code)

Country | Country or Territory | ISO code
-- | -- | --
France | French Southern and Antarctic   Lands Terres australes et antarctiques françaises (TAAF) | TF
France | French Southern and Antarctic Territories (TAAF) -   Scattered Islands -Îles Éparses | TF
France | Mayotte | YT
France | New Caledonia | NC
France | Saint Barthelemy | BL
France | Wallis and Futuna | WF
Netherlands | Aruba | AW
Netherlands | Bonaire | BQ-BO
Netherlands | Curaçao | CW
Netherlands | Saba | BQ-SA
Netherlands | Sint Eustatius | BQ-SE
Netherlands | Sint Maarten | SX
United States of America | Alaska | US-AK
United States of America | American Samoa | AS
Portugal | Azores | PT-20
Spain | Canarias- El Hierro | ES-CN
Spain | Canarias- Fuerteventura | ES-CN
Spain | Canarias- Gran Canaria | ES-CN
Spain | Canarias- La Gomera | ES-CN
Spain | Canarias- La Palma | ES-CN
Spain | Canarias- Lanzarote | ES-CN
Spain | Canarias- Tenerife | ES-CN
United Kingdom | Cayman Islands -Cayman Brac | KY
United Kingdom | Cayman Islands -Grand Cayman | KY
United Kingdom | Cayman Islands -Little Cayman | KY
Federated States of Micronesia | Chuuk | FM-TRK
Denmark | Faroe Islands | FO
Ecuador | Galapagos | EC-W
United States of America | Hawaii | US-HI
Chile | Juan Fernandez Islands | CL
Federated States of Micronesia | Kosrae | FM-KSA
Portugal | Madeira | PT-30
Comoros | Mwali (Mohéli) | KM-M
Comoros | Ndzuwani (Anjouan) | KM-A
Comoros | Ngazidja (Grande Comore) | KM-G
United States of America | Northern Mariana Islands | MP
Federated States of Micronesia | Pohnpei | FM-PNI
Chile | Rapa Nui - Easter Islands | CL
Yemen- Soqotra | Soqotra | YE-SU
Norway | Svalbard | SJ
New Zealand | Tokelau | TK
Federated States of Micronesia | Yap | FM-YAP
United Kingdom | Anguilla | AI
United Kingdom | Cayman Islands | KY
United Kingdom | Pitcairn Island, Henderson, Ducie and Oeno Islands | PN
