### ISSUE TITLE
License "unspecified" even though given as CC-BY in a valid EML.xml

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2138]
**License &quot;unspecified&quot; even though given as CC-BY in a valid EML.xml**

The license on this dataset page shows as "Unspecified". The apparent cause is that both the meta.xml file and the configuration of the data files have issues that prevent the indexing of taxon and occurrence data. The eml.xml file, though, appears to be valid (`https://www.gbif.org/tools/data-validator/1562926582912),` has its own registered endpoint at  `http://gbif-chile.mma.gob.cl/ipt/eml.do?r=poliporos_de_chile,` and gives the license as CC-BY.

We have observed the same effect with other datasets before. Unless the license statement section cannot be interpreted, it looks as though the metadata update is skipped at the same time as the data update fails. If so, this does not appear plausible.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/94991eeeb062da8b9ea85a75547c14db:45c40865891c077285a7fc542ffb6b886d2b4099f2960957286b3d0dea5aa88bed27e14506f183a4915e59835428bd8b7922e7179711265738bfc9d6147cb1d6)
System: Firefox 68.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/9ecb75dc-ee2e-45aa-867e-637a067540fc
Window size: width 1149 - height 800
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-01T07:42:11.061Z',mode:absolute,to:'2019-08-01T07:48:11.061Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-01T07:42:11.061Z',mode:absolute,to:'2019-08-01T07:48:11.061Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
![LicenseUnspecified](https://user-images.githubusercontent.com/13435656/62275070-6f9dd780-b441-11e9-9239-9df1a6c2d3a7.JPG)

**Comment by ahahn-gbif** [comment]
Currently two other such cases at https://www.gbif.org/dataset/search?type=OCCURRENCE&license=UNSPECIFIED

**Comment by timrobertson100** [comment]
The process first validates the archive then updates the registry with the metadata and then indexes data. In this instance the validation fails - due to missing `occurrenceID` in the extension records  -  and the update of the registry is skipped because of that. 

This could be changed to always attempt the metadata update even thought the archive is considered invalid for GBIF indexing purposes. One argument to update would be that uniqueness of occurrenceID is a GBIF requirement but not a DwC-A one and so the publisher can argue the dataset is actually valid. The reason not to might be that an un-indexable archive could be an indication of other mistakes.

@ahahn-gbif can you confirm your preference is to always attempt to update?

**Comment by ahahn-gbif** [comment]
I confirm that my preference is to always to attempt to update the metadata.

We do want to catch unindexable archives and fix the issues, but it is not plausible to an outside observer (data publisher, node manager) why that should impact correct representation of the metadata.
