### ISSUE TITLE
Present the download options as a table

### ISSUE THREAD

**Issue by dnoesgaard** [gbif/portal-feedback#2150]
Ideally, I'd like to present the download options as a table, e.g.

|  | Raw data | Interpreted data | Images | Format | Download |
|---------------------|----------|------------------|------------|-------------------|----------------------------------------------------|
| Simple CSV |  | ✓ |  | Tab-delimited CSV | [button](https://www.gbif.org/occurrence/download) |
| Darwin Core Archive | ✓ | ✓ |  ✓ (links) | Tab-delimited CSV | [button](https://www.gbif.org/occurrence/download) |
| Species list |  | ✓ |  | Tab-delimited CSV | [button](https://www.gbif.org/occurrence/download) |

It's easier to manage than trying to align descriptions. Also much easier to add new format, options, etc. What do you think?

_Originally posted by @dnoesgaard in https://github.com/gbif/portal-feedback/issues/531#issuecomment-519429909_

**Comment by ManonGros** [comment]
Note that I got a few times some users wondering why their download didn't have any coordinates although they could see them on GBIF.
After investigation, it turned out that they they had downloaded the Species list.

Would it be worth adding a column "coordinates" to this list?

|  | Raw data | Interpreted data | Images | Coordinates | Format | Download |
|---------------------|----------|------------------|------------|------------|-------------------|----------------------------------------------------|
| Simple CSV |  | ✓ | | ✓ (if available) | Tab-delimited CSV | [button](https://www.gbif.org/occurrence/download) |
| Darwin Core Archive | ✓ | ✓ |  ✓ (links)| ✓ (if available) | Tab-delimited CSV | [button](https://www.gbif.org/occurrence/download) |
| Species list |  | ✓ | | | Tab-delimited CSV | [button](https://www.gbif.org/occurrence/download) |

**Comment by dnoesgaard** [comment]
Good point, and this table was just to illustrate the idea. We will need to work on the columns to make it clear and concise.

(btw note the need description of species list that we [just implemented](https://github.com/gbif/portal-feedback/issues/531#issuecomment-519824603))

**Comment by dnoesgaard** [comment]
Very nice!

One small correction: species lists **don't** have coordinates

**Comment by dnoesgaard** [comment]
Thanks. Also, I'm not allowed to edit the translation

downloadOptions -> tableValues -> no

because it's an empty string and thus hidden?

**Comment by MortenHofft** [comment]
> because it's an empty string and thus hidden?

That is a setting in Crowdin I believe.

**Comment by dnoesgaard** [comment]
ok, thanks
