### ISSUE TITLE
Taxon mismatch

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2155]
**Taxon mismatch**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/cf70d0fa5842ff1275eafc8bc7c6fed0:42706ffdbdd4d950f3a6e4dbe233d402e18f92271d8edc4691755da0f7e796137acba22115da3658db904a189643503b51ebe04c7c9765decfc8c385f1491fbc)
System: Firefox 68.0.0 / Windows 7.0.0
Referer: https://www.gbif.org/occurrence/1838286604
Window size: width 1891 - height 1079
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-13T05:37:01.473Z',mode:absolute,to:'2019-08-13T05:43:01.473Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-13T05:37:01.473Z',mode:absolute,to:'2019-08-13T05:43:01.473Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL
datasetKey: 9668b676-f762-11e1-a439-00145eb45e9a
publishingOrgKey: c76cf030-2a95-11da-9cc1-b8a03c50a862

**Comment by aallspac** [comment]
the correct assignment:
https://www.gbif.org/species/2216767

**Comment by ahahn-gbif** [comment]
Thank you for reporting! This appears to be an ill-chosen homonym partner, placing the record into fungi instead of animalia. Part of the reason is that the indexing process has no higher taxon information available to go by, not recognizing the family name (Pontogeneiidae). In this specific case, setting a registry default for the dataset as a whole suggesting phylum=Arthropoda should prevent the misinterpretation. In cases where a different phylum is explicitly named in the dataset, this default would be overridden. Alternatively, or in addition, supplying this value in the data might help other digesters of the dataset from similar misinterpretations.
