### ISSUE TITLE
changes vs data changes

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2162]
**changes vs data changes**

What's the difference between

> Last ingestion with changes

and

> Last ingestion with data change

in the "Because you are a trusted contact" box

-----

Github user: @dnoesgaard
User: [See in registry](https://www.gbif-uat.org/api/feedback/user/992833de49db3f70e11e340fc217c455:7138150424b4034ea0760ce2910b7844e9e31584630d2239465ee9f6b1ab6fc5547fdf4ca32d0a9c0b9ef981868dd9f38fbe47995fec89c9e86fa359380a3cfb)
System: Chrome 76.0.3809 / Mac OS X 10.14.5
Referer: https://www.gbif-uat.org/dataset/740df67d-5663-41a2-9d12-33ec33876c47
Window size: width 1440 - height 696
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-20T06:15:59.439Z',mode:absolute,to:'2019-08-20T06:21:59.439Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-20T06:15:59.439Z',mode:absolute,to:'2019-08-20T06:21:59.439Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Be aware that this is intended for the very much so tech audience.
That said, better names are still much welcomed and was also a discussion at the time.

**background**
We crawl datasets on a regularly basis. They might have changed. might not. might fail. might have changed EML metadata but not occurrences, sampling data, checklist data etc.



**Last ingestion with changes**
Will be the date of the latest attempt that finished `NORMAL`
will only show if there has since been crawls that finished with not modified.

**Last ingestion with data change**
Is the last attempt where `rawOccurrencesPersistedNew > 0` or `rawOccurrencesPersistedUpdated > 0`
So based on the API naming this only reflect changes in occurrences. Not in checklists and sampling events. @MattBlissett will know if this is the correct interpretation of the API fields.

**Comment by dnoesgaard** [comment]
> Be aware that this is intended for the very much so tech audience.

If I'm not able to understand and explain what these mean, I think there's room for improvement ;)

I think I understand **Last ingestion with data change** now, but still not quite clear on what the "with changes" part of **Last ingestion with changes** refers to.

@MattBlissett can you help?

**Comment by MortenHofft** [comment]
Many other things can change than occurrences. Say a dataset description.
