### ISSUE TITLE
wrong date

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2177]
**wrong date**

`https://www.gbif.org/species/2444876`

The date can't be 1802. Coluber nasicornis was described in Volume 3 of Shaw's Miscellany (February 1792).

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/34016bed645736e03d80ded547294d5c:b758e0fb07a4fcd68a9845245b7409af1fd14233400e1cab475b51e1de0f814dfc3bcbae06deec6f4209f5c068ce1885d26e6c71537ade86d9637efc53196a10)
System: Firefox 68.0.0 / Mac OS X 10.9.0
Referer: https://www.gbif.org/species/2444876
Window size: width 1232 - height 782
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-24T17:58:40.652Z',mode:absolute,to:'2019-08-24T18:04:40.652Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-08-24T17:58:40.652Z',mode:absolute,to:'2019-08-24T18:04:40.652Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by ahahn-gbif** [comment]
The Catalogue of LIfe, 2019 edition, lists Coluber nasicornis Shaw, 1802 as a synonym of Bitis nasicornis (Shaw, 1802), according to the Reptile Database (ReptileDB), version 2015 (http://www.catalogueoflife.org/annual-checklist/2019/details/species/id/23d5f2ef898a9b68e9062b1df0683c76/synonym/1c9ed707a48b508f1805e81f19d5173e). ReptileDB 2019 (http://reptile-database.reptarium.cz/species?genus=Bitis&species=nasicornis&search_param=%28%28search%3D%27Coluber+nasicornis%27%29%29) still offers the same information. We will forward the feedback to them.

**Comment by ahahn-gbif** [comment]
Forwarded via http://reptile-database.reptarium.cz/contactus

**Comment by ahahn-gbif** [comment]
Response received Sep 11: 
"Not sure if I can solve this, but I did look up the “original” description in Shaw 1792: 94:
https://biodiversitylibrary.org/page/44484275
It is true that Shaw had an illustration and a description but I am unable to see a binomial — he only calls it “The horn-nosed snake”,
so I assume that this description is not valid. I cc: Roy McDiarmid, maybe he can comment.
McDiarmid et al. 1999: 364 also give Shaw 1792 as author but the say that 
"Even though we have not seen the original description, we attribute the authorship to Shaw [1792] rather than Shaw and Nodder, based on Shaw's (1802:397) comment that "I shall therefore repeat, with very slight variations, my former description.” — which is correct except that he didn’t give the species a binomial name in 1792.
 
I’ll add a note to the Reptile Database as well."

**Comment by ahahn-gbif** [comment]
User informed - closing
