### ISSUE TITLE
Empty download file supposedly containing 800.000+ records

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2222]
**Empty download file supposedly containing 800.000+ records**

Hello,

For the past few days I've been trying to download variations on the following dataset: `https://doi.org/10.15468/dl.ez1tny.` About half the time I get an error message when trying to set up the parameters, so I have to start with a new query. If I can proceed to downloading the data, it always results in an empty dataset - however, according to the accompanying email, there should be records in it: "845301 records from 0 published datasets".

I suspect this has to do with the geographic polygon I use, as this is where the error message pops up (if there is one). Using the same parameters for different parts of the globe works fine.

Is possible that I'm doing something wrong, or have I encountered a bug?

Many thanks in advance,
Jens Ringelberg

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/66203d9acb2c4fab374da4e89377930c:0255e8072de0f5fd228484d68824c6c1dffd2c7c3b8dde2705a29bf1228a29aab6777cd2014c9a715cab5aa91ecc2ca01ce938afb3287b1e0bd42657adaaa3f1)
System: Firefox 69.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/health
Window size: width 1920 - height 938
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-30T08:27:53.080Z',mode:absolute,to:'2019-09-30T08:33:53.080Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-09-30T08:27:53.080Z',mode:absolute,to:'2019-09-30T08:33:53.080Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
Trying to re-run the download reproduces the error. The data files contain the headers, but no data.

**Comment by ahahn-gbif** [comment]
Additional tests show that
- a download with a(n outer) bounding box instead of the polygon returns data: 
https://www.gbif.org/occurrence/download/0008717-190918142434337
- a download with a polygon in a different area of the world (same number of edges) returns data: 
https://www.gbif.org/occurrence/download/0008731-190918142434337
- a download that repeats the given polygon from https://doi.org/10.15468/dl.ez1tny returns empty, regardless of whether it is defined clockwise (https://www.gbif.org/occurrence/download/0009265-190918142434337) or counter-clockwise (https://www.gbif.org/occurrence/download/0009263-190918142434337)
- a download with the same polygon, but a different taxonomic group (Lamiaceae) returns empty as well:
https://www.gbif.org/occurrence/download/0009269-190918142434337

Apparently not relevant, just an observation: the direction the polygon was defined in is no longer highlighted in the search interface. By design, or a regression?

**Comment by MortenHofft** [comment]
> Apparently not relevant, just an observation: the direction the polygon was defined in is no longer highlighted in the search interface. By design, or a regression?

It should still highlight if it it clockwise. Are you sure it is clockwise?

**Comment by ahahn-gbif** [comment]
Odd - thanks, and sorry, not sure what I did there. Thought I had started in the upper left position and traced twice in different directions, but apparently not.

**Comment by MortenHofft** [comment]
the interface cleans it up if you draw it. It can only be wound clockwise if you paste it.

**Comment by MortenHofft** [comment]
Changing the geometry slightly to not cross the dateline will make it work
https://www.gbif-uat.org/occurrence/download/0000335-190802075855554

I notice that above links are using prod - the problem can be also be reproduced in uat https://www.gbif-uat.org/occurrence/download/0000336-190802075855554

**Comment by ahahn-gbif** [comment]
contacted reporter by email from helpdesk

**Comment by MortenHofft** [comment]
Downloads on the solr uat environment seem to have the same issue for what it is worth. But that makes sense given that there is more than 100.000 records.

**Comment by daijiang** [comment]
I came to the same issue; it says xxx records, but the downloaded file is only 19 kb.
Any solutions?

**Comment by MattBlissett** [comment]
Hi @daijiang, 

Thanks for reporting this.

You have found a bug in our API, where an invalid polygon is not rejected immediately, but instead returns zero occurrences.  We are working on fixing the bug (today), but the fix is to reject the query as invalid.

Your queries are using MULTIPOLYGONs with overlapping rectangles, which is not allowed by the [OGC specification (§6.1.14)](https://www.ogc.org/standards/sfa).  You could either union these rectangles into polygons first, or separate them into several within predicates.

I have killed the three downloads you have running, as they will fail in the same way.

**Comment by daijiang** [comment]
Thanks @MattBlissett for the information! I did not know that overlapping rectangles are not allowed. Do you have examples about how to separate multipolygon into several within predicates? I have a stack overflow question [here](https://stackoverflow.com/questions/66922817/how-to-use-rgbif-to-download-occurrence-data-from-multiple-polygons-at-once); if you can take a look at it and give some suggestions, that would be great!! Thanks again!

**Comment by daijiang** [comment]
@MattBlissett I saw your answer to the stack overflow question. Thanks! But the `st_union` returns clockwise polygon while GBIF asks for counter-clockwise ones, rights? Do you know any quick solution to change a clockwise polygon to counter-clockwise?

**Comment by MattBlissett** [comment]
```
st_as_text(st_reverse(u))
```

This seems to produce a counterclockwise polygon. (NB I've never used the R Spatial library before.)
