### ISSUE TITLE
GBIF Number

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#230]
**GBIF Number**

I was using the new GBIF website and was wondering where do I find the GBIF number for species I locate.

-----
fbitem-3fc2452e42c851d70896794fb026acd0f4db0c4f
Reported by: peterbucksutton@gmail.com
System: Edge 14.14393.0 / Windows 10 0.0.0
Referer: https://demo.gbif.org/search?q=Swainson's%20Hawk
Window size: width 1920 - height 964
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-29T20:55:57.862Z',mode:absolute,to:'2017-06-29T21:01:57.862Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-29T20:55:57.862Z',mode:absolute,to:'2017-06-29T21:01:57.862Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
> sent per email

Thanks for your feedback

I’m afraid I don’t understand the question. Could you please expand?

What GBIF number are you referring to? What information are you looking for and how do you plan to use it? Thanks for reporting usability issues, it isn’t always easy to figure out how to best provide the information.

**Comment by timrobertson100** [comment]
I understood this as the GBIF taxonKey which is only in the URL I think. It's not something we'd want to promote too widely as it's slightly volatile.

**Comment by peterbucksutton** [comment]
We are building up a controlled vocabulary of bird species based on the GBIF backbone taxonomy and we are keeping the GBIF ID Since we want to provide a link to the authoritative source. Looking at the JSON file, this number corresponds to the “specieskey” property. Since we are only keeping data on the species level, this number also corresponds to the “key”, “nubkey” and “taxonID”. Eventually we are planning to use the Species API to automatically retrieve the data, but currently this is done manually. 
 
On the former taxonomy user interface, this number was available on the “overview” section as GBIF ID. On the new interface, this ID number is not available anymore and we were wondering why the decision has been taken and how could we access to this number directly from the interface.
 
Following up to timrobertson100 comment, I would like to hear a little bit more about the “volatility” of this number. If it is not an persistent ID, what other options do you recommend for using in our controlled vocabulary as reference to the GBIF taxonomy. Is GBIF planning to use URIs of some form?

**Comment by MortenHofft** [comment]
@mdoering is the best to describe how volatile and the plans for that API i believe.

Depending on your needs, the match api might be useful. We use that a lot internally to match names to ids. 
http://api.gbif.org/v1/species/match?name=Buteo%20swainsoni%20Bonaparte,%201838
http://api.gbif.org/v1/species/match?name=oenanthe&verbose=true

The ID is available in the last part of the URL https://demo.gbif.org/species/2480562 , but is - as Tim mentions - not intended for use without considerations of its volatile nature.

**Comment by mdoering** [comment]
The backbone taxon keys are stable, not volatile. They are intended to be stored for use. There might still be a few edge cases  with unstable ids, but these are below 1%. One needs the id to work with our API and doing a lookup each time might not be ideal as it is quite some overhead and might even need manual curation/decisions.

And yes, I would recommend the backbone taxon key as the reference to store, no URLs

**Comment by MortenHofft** [comment]
Hi @peterbucksutton 
To summarize: they are now only available in the URL and they are fairly stable.

As you can hear we are deabting amongst ourselves how to think of our IDs. Sounds like they are stable in the sense they work 99% of the time. They are volatile in the sense that they won't work 1% of the time. Hopefully that can help you decide on an approach that fits your needs. I have created a [related issue](https://github.com/gbif/portal16/issues/367)
