### ISSUE TITLE
Map interactions

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#233]
**Map interactions**

I find the occurrence search a nuisance on the maps.  To get a mouse scroll wheel to enable zoom rather than page scroll, requires a map click.  This first click though starts a search.  I often find clicking to take control of the map does searches I don&#39;t intend (which pop up 5 secs later).

I&#39;d suggest considering alternatives.  Perhaps ignoring the first click, and also changing the cursor to something that gives a clue that further clicks will issue a search, or perhaps putting the search behind a button you explicitly enable. 

Haven&#39;t thought about the implications of mobile on this, but on a desktop I do this on almost every map view

-----
fbitem-dataset4fa7b334-ce0d-4e88-aaae-2e0c138d049e
Reported by: @timrobertson100
System: Chrome 58.0.3029 / Mac OS X 10.11.5
Referer: https://demo.gbif.org/dataset/4fa7b334-ce0d-4e88-aaae-2e0c138d049e
Window size: width 1490 - height 1099
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-30T13:02:26.585Z',mode:absolute,to:'2017-06-30T13:08:26.585Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-06-30T13:02:26.585Z',mode:absolute,to:'2017-06-30T13:08:26.585Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Seems reasonable. We could also not disable the scroll zoom - but that seems a shame. On the other hand I haven't seen anyone complain on the old site that the map would "catch" scroll.

I think I will try to keep it as i find it annoying myself, but the move click search to a tool. Another approach than click to activate zoom, could be only activate if scroll initiaited over map, but that is more tricky

**Comment by MortenHofft** [comment]
Well we cannot have you finding such a central component a nuisance. I've disabled the first click https://github.com/gbif/portal16/commit/d4433834d853cb42500445bc2248fa5d5ffd0294 for starters. 

Seems reasonable to move it to a tool. it makes it an additional click to use it, but that might well be better anyhow. In general it would be worth revisiting the layout and information of the search. I added it because it seemed an obvious feature to try for performance etc. And I liked it enough to keep it. But that doesn't  mean that we should keep it nor that I consider it perfected. Other information on search could also be relevant. If we decide to keep it, then it might be worth some more consideration on what it should do and how it should behave and look. Similar for disabling scroll zoom per default. No one has ever complained about it. Asking around the office no one has ever been annoyed by it. So it might just be one of those cases of invented needs.

So an obvious question becomes - do we need search (I know Rod has asked for it, but he might be the only one). do we need zoom disabled (I might be the only one finding it annoying).

**Comment by timrobertson100** [comment]
Thanks for looking.  

Disabling the first click I think was probably the most important thing and enough to not be a nuisance.  Other ideas I'd suggest holding on until we get more user feedback, and the occurrence search is probably welcomed by many - IIRC several folks had asked for it in Jira.

**Comment by gbif-portal** [comment]
Closed and transferred to  https://github.com/gbif/portal16/issues/439
