### ISSUE TITLE
I don't know if possible but it would be handy to be able to use external polygons, like Ecoregions, to do searches. Thanks

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2348]
**I don&#39;t know if possible but it would be handy to be able to use external polygons, like Ecoregions, to do searches. Thanks**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/bff857c63dfdcb3553102547b6a8204b:90e29f97d9d714a94fd07b5fd28dd34542cb26b448c0be8deeb2ab087c79788228af8ccadb5896ae269d05c8570dde4c3670c635718f4f4c78d132cda73c8c10)
System: Chrome 79.0.3945 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download/0028182-191105090559680
Window size: width 1536 - height 700
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-12-21T16:28:02.696Z',mode:absolute,to:'2019-12-21T16:34:02.696Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2019-12-21T16:28:02.696Z',mode:absolute,to:'2019-12-21T16:34:02.696Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Thank you for your feedback

It is partly possible already (see screenshot), though there is a limit to the complexity of the polygon. Secondly we have recently rewritten large part of our infrastructure, so that we in the future can better support searching by named polygons in external datasets (like Ecoregions or protected areas).

Thanks

![Screenshot 2020-01-03 at 13 27 24](https://user-images.githubusercontent.com/6759267/71723420-dc703000-2e2c-11ea-9d73-1fef21f9aca1.png)

> send per email
