### ISSUE TITLE
link for Node Managers Committee terms of reference not showing properly

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2418]
**link for Node Managers Committee terms of reference not showing properly**

Seems to be a Markup problem so this is not showing as a hyperlink

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/73b44b135be5ce79779a748c317e2cdb:638dac375c9dd85f779e221c7a500fbb3404232a86fefe42240441b4c116df0e37cc78cc86cb44f405ce9ae608dbc4ec357f027f9f81cf7ddac604b15e9fa6b2)
System: Chrome 79.0.3945 / Mac OS X 10.14.6
Referer: https://www.gbif.org/contact-us/directory?group=nodesCommittee
Window size: width 1309 - height 649
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-10T09:01:24.461Z',mode:absolute,to:'2020-02-10T09:07:24.461Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-02-10T09:01:24.461Z',mode:absolute,to:'2020-02-10T09:07:24.461Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
That translation is 6 months old and only now the issue is spotted. That is a shame.

@dnoesgaard not all fields support markdown. When introducing markdown syntax in a translation, then we need a procedure to check that it renders correctly. It is likely that I will have to introduce compilation and sanitisation before it displays correctly.

The problem is of course that you - as a translator - do not know before seeing it live. So for now the principle will have to be "if you introduce markdown in a field where it isn't already there, then let Morten and Thomas know" - we can then check in code or deploy so you can test. 

Alternatively we can create an environment where your english translations is deployed to automatically
