### ISSUE TITLE
"100% with taxon match" links to unintuitive search result

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#243]
**&quot;100% with taxon match&quot; links to unintuitive search result**

It links to a search for records with no taxon match which is the inverse of what you&#39;d expect.  

Without the ability to do negative filtering I can&#39;t suggest an alternative better search to link to.  Perhaps it could be designed around by offering a notification based on a referrer?  &quot;You are viewing only the records which did not match the GBIF backbone.  Would you like to clear this filter?&quot;

-----
fbitem-dataset282d0ccb-4fa0-40f9-8593-105c77e88417

System: Chrome 58.0.3029 / Mac OS X 10.11.5
Referer: https://demo.gbif.org/dataset/282d0ccb-4fa0-40f9-8593-105c77e88417
Window size: width 1402 - height 799
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-10T17:06:58.405Z',mode:absolute,to:'2017-07-10T17:12:58.405Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-10T17:06:58.405Z',mode:absolute,to:'2017-07-10T17:12:58.405Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Yes it is a real shame. Maybe remove it al together? Make it the inverse on the dataset page? So unlike the other percentages it shows no matched. I chose this annoying compromise because i believed it to be useful information and wanted them all to be positive statements. But i completely agree, that it is an odd unintuitive feeling. The info as you mention is also an option. Neither solution seems really good to me.

The best solution would of course be to add the negative filter to search.
Thanks

**Comment by gbif-portal** [comment]
Closed and transferred to  https://github.com/gbif/portal16/issues/438
