### ISSUE TITLE
Question about maps

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2486]
**Question about maps**

How accurate are the markers on maps that show where a species has been found? Thank you

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/b79aa8169f3f2d55e49e55e760220cdf:b1f0f3e009b40f2a438be6017adb69bab8f51485be5872e9d0827debb97a9528d6fd59a4a793fb033c004653269a7c729dfc55d71e56350be20523ae3ba11408)
System: Chrome Mobile 80.0.3987 / Android 0.0.0
Window size: width 412 - height 756
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-03-17T14:56:06.351Z',mode:absolute,to:'2020-03-17T15:02:06.351Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-03-17T14:56:06.351Z',mode:absolute,to:'2020-03-17T15:02:06.351Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by MattBlissett** [comment]
Replied by email.

> How accurate are the markers on maps that show where a species has been found? Thank you

There are two types of maps on GBIF.org.

The first are the maps on individual occurrences, such as on https://www.gbif.org/occurrence/1802794710 .  Where the data publisher gives us a "Coordinate uncertainty in metres" this is shown on the map, as on this observation. Many other occurrences do not include this information, so we don't know how accurate they are. Sometimes, the remarks or location fields will have information.

A small number of observations include a polygon rather than a circle for the uncertainty, this is also shown on the map, and in the table as "Footprint WKT".


The second type of map is found on species pages, dataset pages and so on.

For example, here: https://www.gbif.org/species/8080199

These show the points from the occurrence data, but don't attempt to show uncertainties or wider ranges.

A common issue with these is where the data is grid-based. For example, on this map: https://www.gbif.org/species/2481174 (ensuring you choose the style "Classic points" from the paint icon) you can see a grid if you zoom in to France, and a different grid over Wales.  It's likely the dataset containing these points is arranged on a 10km grid, but we do not show this.
