### ISSUE TITLE
Papua New Guinea is showing up as 'former participant'. It has never been a GBIF participant so this must be an error in the directory. Also, we should not be using the former participant description on the country pages.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#258]
**Papua New Guinea is showing up as &#39;former participant&#39;. It has never been a GBIF participant so this must be an error in the directory. Also, we should not be using the former participant description on the country pages.**

-----
fbitem-c8353dd72030e769a6037ffea89207748b19774d
Reported by: @timhirsch
System: Chrome 59.0.3071 / Mac OS X 10.12.4
Referer: https://demo.gbif.org/country/PG/summary
Window size: width 1920 - height 909
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-25T23:28:19.221Z',mode:absolute,to:'2017-07-25T23:34:19.221Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-07-25T23:28:19.221Z',mode:absolute,to:'2017-07-25T23:34:19.221Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by cgendreau** [comment]
It seems they signed the 2001 MOU (in 2004)

**Comment by MortenHofft** [comment]
Thanks.
Notice that this is in line with what we do on the current site.

![screen shot 2017-07-26 at 13 18 29](https://user-images.githubusercontent.com/6759267/28618545-0b24968e-7205-11e7-97bb-fcb347aa7db5.png)

Should we remove the description for former participants only or are the other examples?

**Comment by timhirsch** [comment]
Thanks Morten – I thought we decided a while ago to drop that from the country pages but seems I was wrong. There is also an issue around observers, as the current wording is confusingly suggesting they are still participating countries. Rather than mess you around more, I think it is best if I speak with Anne Mette once I am back next week and we can decide once and for all how these cases should be represented on the new portal. So it can be added to our content check discussion when we meet. No need to take action before then. Sorry to mess you around.

Best

Tim
