### ISSUE TITLE
This is a cover.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2609]
**This is a cover.**

This is a cover.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d3213f8bd9f00da279546f7147ab2e44:263bdbd8b4417a9fa40b6d479f58fa19cc7b6401ba146a9466605a221b3e3070cee331d1389169a9c7bed8ae8a2ff5617897a5b8217df8e6d9c809c239752d16)
System: Safari 9.1.3 / Mac OS X 10.9.5
Referer: https://www.gbif.org/occurrence/453659713
Window size: width 1148 - height 802
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-03-31T07:27:29.937Z',mode:absolute,to:'2020-03-31T07:33:29.937Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-03-31T07:27:29.937Z',mode:absolute,to:'2020-03-31T07:33:29.937Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by jholetschek** [comment]
User contacted by data owner with following mail:

Dear Davide,

thanks for your feedback on our specimens on GBIF! Indeed these are covers for specimens in historical folders. Since these folder covers often contain useful labels, they’re digitized as well. Unfortunately, this relation between the scans isn’t visible on GBIF, we’re thinking about ways how to change that.

If you want to see the real specimens for a given cover, just click on the “Reference” link below the image. This will get you to this specimen on our herbarium’s page, which views all associated scans: https://ww2.bgbm.org/herbarium/specimen.cfm?SpecimenPK=134114.

Hope that helps! If you have more questions, I’m happy to help.

Best wishes,
Jörg
