### ISSUE TITLE
Unreadeable French characters

### ISSUE THREAD

**Issue by leo-buitrago** [gbif/portal-feedback#2714]
[This dataset](https://www.gbif.org/publisher/3ead5cf3-2840-482e-bbd9-76380825be63) has fields with French characters and some of them are showing empty/blank in the portal. When the DwC-A is downloaded from the IPT all those fields look complete in the file but not in the portal, even trying with different encodings in the IPT. It looks ok in our database as well, so it seems like a front-end issue.

Some examples (**occurrenceID**) in the dataset:

- **NMR997900000320**
locality: "Côtes-d'Armor, Pléneuf-Val-André, Îlot du Verdelet"  -> now empty (https://www.gbif.org/occurrence/search?q=NMR997900000320&dataset_key=a307e4d7-1de2-4adc-95d5-a0a8d5f57236)
- **NMR999900000416**
vernacular name: "Valse ridderspoor | Larkspur | Dauphinelle d'Ajax | Gartenrittersporn | Sommer-ridderspore"  -> now empty (https://www.gbif.org/occurrence/search?q=NMR999900000416&dataset_key=a307e4d7-1de2-4adc-95d5-a0a8d5f57236)
- **NMR999900002685** 
vernacular name "Wilde herfsttijloos | Meadow Saffron | Colchique d'automne | Herbstzeitlose | Høst-tidløs" -> now empty (https://www.gbif.org/occurrence/search?q=NMR999900002685&dataset_key=a307e4d7-1de2-4adc-95d5-a0a8d5f57236)

**Comment by jeroencreuwels** [comment]
Some extra remarks. I have tested various records with different characters in this dataset with different encodings. They all seem to be OK, except the <d'> and the <l'> which is common in various French names. To me it seems that the apostrophe causes the problems. 
E.g. the record NMR997900000320 is a good example: the <ô>, <é>, <Î> is not the problem as I first assumed, because these characters are shown in other fields. But it appears that only fields where a <d'> or a <l'> is used are blank. In earlier versions of the export of the same dataset we see the same, but it was not noticed before.  
Jeroen Creuwels, Datamanager NLBIF

**Comment by MattBlissett** [comment]
The locality is in the API response: https://api.gbif.org/v1/occurrence/2570354107

This is a fairly recent problem with the portal, @MortenHofft / @thomasstjerne, since the prod ES portal shows it correctly.

**Comment by MortenHofft** [comment]
It looks like the problem is bad escaping of `'` as we now bind sanitized html to fields to allow italics and links in field values on occurrences. Clearly that wasn't tested well enough (I implemented that too quickly clearly)
