### ISSUE TITLE
Ixodes is not a bird genus

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2732]
**Ixodes is not a bird genus**

This issue was reported on Helpdesk.

This genus is likely not a bird. Something odd though is that the taxonomy coming from the Catalogue of Life is correct: https://www.gbif.org/species/156954499

Where does this issue come from?

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/9252ab72ae8aa27083a47dd65ccc76d3:1e5fd7971dbe28a46fe2175bc4e8835a2f990766590c932478cc34d1e13f883b6a7cf029f0ea51118e28833d9c74d7fe1e43d7b4bfe48f5c33d6bb272a3f93ef)
System: Safari 13.1.0 / Mac OS X 10.15.4
Referer: https://www.gbif.org/species/10626309
Window size: width 1372 - height 896
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-20T14:59:12.316Z',mode:absolute,to:'2020-04-20T15:05:12.316Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-20T14:59:12.316Z',mode:absolute,to:'2020-04-20T15:05:12.316Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by mdoering** [comment]
Ixodes is an accepted Acari genus both in the current nub and latest build . The bird genus is listed as a synonym in IRMNG with an unknown accepted name. It becomes doubtfully accepted somehow which is wrong. Bug to be fixed it seems

**Comment by mdoering** [comment]
@myrmoteras, @gsautter Plazi also has some bad data for Ixodes in a ticks paper saying its a bird:
http://tb.plazi.org/GgServer/html/03DD87C4FFC6FFE91EFCDDA7FC20FD14

<img width="1155" alt="Screenshot 2021-02-15 at 20 34 35" src="https://user-images.githubusercontent.com/327505/107986875-3f8b3a80-6fcd-11eb-8efa-0377299a93e9.png">

**Comment by gsautter** [comment]
Fixed the data as well, DwC-A should be updated in 15-30 minutes.

**Comment by mdoering** [comment]
Thanks Guido!
Did you ever think about ways of doing some human validation on Plazi mediated data? I was wondering if the original authors for example would be reachable and often willing to quickly review the data to spot problems early on?

**Comment by myrmoteras** [comment]
Hi Markus
there are three issues: We have not thought about sending out emails to the authors once we processed the data including a link to the data on GBIF or in TB. Until recently, this would not have been possible without manually finding their emails. In some cases, if the email is in the article and we can extract it this would be possible. But it would also come with an addition human resources effort that need to be found.

In the new BiCIKL project there is a feedback mechanism planned, essentially via COL that is supposed to build a UI that allows to check taxonomic data. This might then be the solution.

Otherwise we rely on the users, not necessarily the author, to send us feedback we then immediately fix, both by fixing but also analyzing whether we can inhibit the error in future processing or by reprocessing the data, if the error is a structural issue

**Comment by gsautter** [comment]
To prevent such mishaps in the future, I added QC rules that will check the `order` and `family` attributes for spaces (and non-letters in general) where present, and also added respective rules to the gatekeeper that will block export of treatments with such issues.
