### ISSUE TITLE
Rhamnus alnifolia records aren't catalogued properly

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2749]
**Rhamnus alnifolia records aren&#39;t catalogued properly**

Using your search menu, I can't find all the Rhamnus alnifolia records. If I enter this name in the search box on the front page, the results report 400K records. This does list some R. alnifolia, but they are all flagged as taxonmatcheshigherrank. This result set also includes many records from other taxa.

I can select the genus Rhamnus in the side bar.This reduces the result set to 200K records, but it no longer includes alnifolia. Rhamnus alnifolia is not offered in the taxon hierarchy in the sidebar.

If I select the genus Rhamnus, and limit my search to North America, I can get a data set that includes more than 1000 R. alnifolia records, but also many more records from other species.

If I search for Rhamnus alnifolia in the species search, I can get 85 occurrence records that match this species.

There appears to be no direct way to search for all of the 1000+ records of Rhamnus alnifolia. It looks like something about the way this taxon is coded is incorrect. 

Can someone look into this please?

Best,

Tyler

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/abd8b470bdbd004a7225a40f148ddf11:33a55b6643bf41299fc44b9635489722aa4f8b3d345d28d187d6cb08f881ca18588ec16b3aa46660e8ffb2a47368fec83a72c12c1824fd0d1225b7bdae579480)
System: Firefox 75.0.0 / Linux 0.0.0
Referer: https://www.gbif.org/tools/species-lookup
Window size: width 1280 - height 587
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-28T16:10:12.508Z',mode:absolute,to:'2020-04-28T16:16:12.508Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-04-28T16:10:12.508Z',mode:absolute,to:'2020-04-28T16:16:12.508Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: WARNING

**Comment by ManonGros** [comment]
It seems like the issue is that the backbone contains 3 different species of "Rhamnus alnifolia" (with different authorships): https://www.gbif.org/species/search?q=Rhamnus%20alnifolia
This means that when occurrences are associated with the name "Rhamnus alnifolia" without any authorship, the matching algorithm is unable to find one match (all three species seem as likely). Therefore the occurrence is matched to a higher rank.
We could make a custom download based on the verbatim names. Will contact the user to ask if he is still interested.

**Comment by ManonGros** [comment]
Custom download available here: http://doi.org/10.35000/tedb-qd70

**Comment by ahahn-gbif** [comment]
With R. alnifolia handled as a heterotypic synonym with both author teams, searching for the attached records would likely require to search under both the now accepted names: Frangula purshiana subsp. purshiana  and Endotropis alnifolia (L'Hér.) Hauenschild to find all records. The synonym search will only retrieve names identified under the synonym name, which in this case is difficult due to the two different author teams. Searching at genus level for _Rhamnus_ will not include data for either. This could be handled by asking publishers to supply authorship to help resolve, rather than through the taxonomic backbone.

**Comment by jhnwllr** [comment]
"Rhamnus alnifolia" [search](https://www.gbif.org/species/search?q=Rhamnus%20alnifolia) 

returns 3 synonyms of 
**Endotropis alnifolia (L'Hér.) Hauenschild**
https://www.gbif.org/species/9266494
https://www.catalogueoflife.org/data/taxon/39SNS

1. **Rhamnus alnifolia Pursh**
https://www.gbif.org/species/7774973
2. **Rhamnus alnifolia f. alnifolia**
https://www.gbif.org/species/7274016
3. **Rhamnus alnifolia f. angustifolia D.Löve & J.-P.Bernard**
https://www.gbif.org/species/3877508

And one synonym of 
**Frangula purshiana subsp. purshiana** (subspecies)
https://www.gbif.org/species/6371409
https://www.catalogueoflife.org/data/taxon/5HDCX
**Frangula purshiana (DC.) J.G.Cooper** (species)
https://www.gbif.org/species/8286637
https://www.catalogueoflife.org/data/taxon/6JKWP

1. **Rhamnus alnifolia L'Hér.**
https://www.gbif.org/species/8253025

I am finding it hard to spot the error here...

**Comment by ManonGros** [comment]
As far as I understand, the problem isn't necessarily the taxonomy. Most publishers don't use scientific names authorship when publishing records for this species so our system is unable to find a match (as both possible matches are heterotypic synonyms).
So we have only 58 records matching to a species: https://www.gbif.org/occurrence/search?taxon_key=8253025&taxon_key=7774973

While there are 1,894 Rhamnus alnifolia on GBIF: https://www.gbif.org/occurrence/search?advanced=1&verbatim_scientific_name=Rhamnus%20alnifolia&occurrence_status=present

**Comment by jhnwllr** [comment]
So who should we contact to solve the problem?
