### ISSUE TITLE
glitch in displaying people associated with dataset: boxe appears repeated dozens of times across top of page

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2776]
**glitch in displaying people associated with dataset: boxe appears repeated dozens of times across top of page**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/fb93894de2ee0fe350d9edc412ff7f59:d11c72501443d16d0fbc1559d4f02a3ad7150617625cdf654c4fb0d3d2d541257a766df25bb571aecf83fda83ef4c477e8b06aeb0bcd514414d7943531715812)
System: Chrome 81.0.4044 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/6e4b215e-9019-4934-8433-65d80a35c230
Window size: width 2133 - height 986
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-05-13T06:32:25.083Z',mode:absolute,to:'2020-05-13T06:38:25.083Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-05-13T06:32:25.083Z',mode:absolute,to:'2020-05-13T06:38:25.083Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
The styling on these pages haven't changed for ages, so it must be browser specific. I have retested in Chrome, Safari, Firefox and Opera in latest versions.

**Comment by MortenHofft** [comment]
>sent by email

Thank you for your feedback

Oh not, it is the worst kind of error, the ones you cannot reproduce! Could you possibly take a screenshot and tell me what browser you are using (and what version) and what operating system?

**Comment by MortenHofft** [comment]
It turns out this isn't a GBIF issue, but a Bloodhound browser plugin issue (psst @dshorthouse). From email

> basically the bloodhound attributions box below was repeated dozens of times so that it took up most of the top half of the page view.

> another glitch where the attributions box only appears sporadically rather than consistently at the top of the page next to citations and occurrences

> To get the attributions box to appear I have to click through tabs and often link through to our home page and then back again

**Comment by dshorthouse** [comment]
Oh dear. My apologies. This is like a complaint fired at Elsevier for the Unpaywall browser extension – although I am not pretending GBIF is Elsevier nor that Bloodhound is Unpaywall. If you can think of a way I can make these DOM injections from the extension less like GBIF so as to prevent similar feedback, I'm open to suggestions. My original goal was for these to blend-in and be unobtrusive, but this was evidently short-sighted.

To make matters even more interesting, both these issues are very difficult to reproduce. The exploding attributions I *thought* was fixed in an earlier version – the extension is now at 3.0.7 updated March 22, 2020.

The intermittent appearance of DOM elements from Bloodhound is an interesting one and actually touches on the shortcoming in how browser extensions work in the face of dynamically-generated websites like GBIF. There are minimally 20 HTTP requests on a typical occurrence page after the DOM is interactive, https://webpagetest.org/result/200519_2V_ab08ad107865288ab1e62f705a46d3bd/1/details/#waterfall_view_step1. As you know, these produce all sorts of page elements, including the banner in which I'm attempting to inject yet other elements from within the extension. However, all extensions work via listening to DOM load events. I have tried all kinds of hacks including setTimeouts to detect the presence of DOM elements on an occurrence page even well after DOM load events. I'll keep digging.
