### ISSUE TITLE
Misspelled name, author wrong?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#2839]
**Misspelled name, author wrong?**

This subspecies is listed in IPNI as 
Phragmites australis subsp. berlandieri (E.Fourn.) Saltonst. & Hauber
J. Bot. Res. Inst. Texas 1(1): 387 (2007).
See https://www.ipni.org/n/77093164-1

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/953c434959944eb17131df8f83342c95:4ce2bdbdd2b03fabbfc733d4290a761da76b515a9168906cae114119ebd75fe64813875e62c7037732959f6674e7ebf2fa37c50e312a9f0f2758cdb8763ff079)
System: Chrome 83.0.4103 / Windows 10.0.0
Referer: https://www.gbif.org/species/5677970
Window size: width 1680 - height 917
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-19T22:33:28.889Z',mode:absolute,to:'2020-06-19T22:39:28.889Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-06-19T22:33:28.889Z',mode:absolute,to:'2020-06-19T22:39:28.889Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by ahahn-gbif** [comment]
The entry at https://www.gbif.org/species/5677970
is based on https://www.ipni.org/n/urn:lsid:ipni.org:names:953774-1, where the name is given as "Phragmites australis var. berlanderi (E.Fourn.) C.F.Reed". 
However, the page header marks it as "doubtful". No GBIF occurrences are matched against this name, which is maintained in the backbone only because it does appear in one of the sources.

The subspecies that you are referring to, on the other hand, is listed at https://www.gbif.org/species/8351723: Phragmites australis subsp. berlandieri (E.Fourn.) Saltonst. & Hauber. The reference for this entry is http://www.catalogueoflife.org/col/details/species/id/e42865c439e202e655307abbc46249e2/synonym/99f36357316c975268fe8d8916975cc6, where the name is appearing as a synonym of Phragmites australis subsp. australis.

**Comment by ahahn-gbif** [comment]
contacted by email. closing
