### ISSUE TITLE
Improve content on R GBIF

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#284]
**Improve content on R GBIF**

The current content is sparse, and we know this to be a high visibility page.

An example of some content to include was prepared here
https://s3-eu-west-1.amazonaws.com/gbif-demo/r.html

@sckott should be aware of this and given the opportunity to also comment.

-----
fbitem-e7a25bb2e552c3dc6e919aa61b14f74789d9f96e
Reported by: @timrobertson100
System: Chrome 59.0.3071 / Mac OS X 10.11.5
Referer: https://demo.gbif.org/tool/81747/rgbif-an-interface-to-the-gbif-api-for-the-r-statistical-programming-environment
Window size: width 1896 - height 1099
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-04T12:39:15.902Z',mode:absolute,to:'2017-08-04T12:45:15.902Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-04T12:39:15.902Z',mode:absolute,to:'2017-08-04T12:45:15.902Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by sckott** [comment]
thanks for pinging me.

The material at https://s3-eu-west-1.amazonaws.com/gbif-demo/r.html looks mostly good, but a few thoughts on it:

- Is the thought that the content in that file will replace the content at https://demo.gbif.org/tool/81747/rgbif-an-interface-to-the-gbif-api-for-the-r-statistical-programming-environment ?
- can we do `rgbif` instead of `rGBIF` ? don't want to confuse users as case matters when within an R session
- i like the screencast being included - i should probably make an updated one soon, but that's good for now
- in https://demo.gbif.org/tool/81747/rgbif-an-interface-to-the-gbif-api-for-the-r-statistical-programming-environment `spocc` is mentioned, which incorporates `rgbif`  + other pkgs including for idigbio, inaturalist, BISON, etc. - Maybe also mention https://github.com/ropensci/scrubr - a package for cleaning occurrence data. (but not super important)

We do have a manuscript in prep https://github.com/sckott/msrgbif describing rgbif and pygbif - but not out yet - will let you know when so a citation for that can be included

Is there anything you'd like to see on this page that I can help prepare?

---

should there be a page also for [pygbif](https://github.com/sckott/pygbif)? up to you (plural) of course

**Comment by timrobertson100** [comment]
Thanks Scott.  Yes, this was just to share some ideas about expanding the placeholder content we have on https://demo.gbif.org/tool/81747/rgbif-an-interface-to-the-gbif-api-for-the-r-statistical-programming-environment.

The other suggestions all see good, and we should accommodate them.  I don't think there is anything you need to do.

**Comment by dnoesgaard** [comment]
I think this one can be closed as the rgbif page on gbif.org has been improved a great deal...

https://www.gbif.org/tool/81747/rgbif
