### ISSUE TITLE
New occurrence view doesn't display most interesting information

### ISSUE THREAD

**Issue by rdmpage** [gbif/portal-feedback#29]
This is subjective, but the old portal gives a much more visually informative summary of an occurrence than the new portal. Compare old portal https://www.gbif.org/occurrence/1415971567

![old](https://s19.postimg.org/a5nk3kcar/Screenshot_2017_01_10_19_42_20.png)

with new portal https://demo.gbif.org/occurrence/1415971567

![new](https://s19.postimg.org/axq82rghv/Screenshot_2017_01_10_19_42_09.png)

The old portal shows a clear map, the word "New Zealand" is easily visible, and the image of the specimen is prominent. The new portal has a more obscure map (zoomed in too much), the specimen image is relegated to the bottom, and there is a big block of text about the data set, which is the least interesting things about the specimen.

I think if you gave this to people and asked them to tell you about the occurrence, they'd be able to do so much more successfully from the old portal.

**Comment by dnoesgaard** [comment]
I would second this and add:

- indeed annoying that the mapped is zoomed in that much (impossible to recognize geographical features and get quick impression of where we are).
- the dataset description takes up a too prominent place, considering there is a dataset page where this is available.
- we could show image(s) in a more interesting way, perhaps pull them up under the map

**Comment by mdoering** [comment]
I would even consider to remove the entire dataset description and show images there instead. Or maybe even a small preview at the very top?

**Comment by mdoering** [comment]
Has it been considered to show 2 different layouts depending on the basis of record? Observations and specimens have a few  properties and it would be good to quickly see the difference. Specimen have all the physical collection properties like catalog number which is of importance for specimens. Fossil specimens have the geological context.

**Comment by MortenHofft** [comment]
Hi Rod. Thank you for your feedback and honesty.

Being the main culprit behind this page I am sad to hear that the page has gotten worse. Especially since I know you really didn't like the old one either! 

I'm not sure where to go from here I must admit, as I find it to be much better and having more potential - not to say that there isn't things I would like to change as well. But if there is general consensus that we are regressing, we should obviously change it back some way or another. But then I probably need some more guidance if I'm the one to do so.

This is very much related to [this Jira issue](http://dev.gbif.org/issues/browse/PF-2534) where the two of us discussed among other things the images. And to https://github.com/gbif/portal16/issues/7 where general outstanding issues and ideas for the occurrence page is also discussed.

That being said - here is my take on the issues mentioned above:

__zoom level__
I agree, it is too high. I have set it to be zoomed our further. And added the globe as have been the intention all along. I hope that helps getting a faster overview. AS I see it the preferred zoom level depends very much on where on earth we are and who you are. Oceans generally needs to be further out. If it is a neighbourhood that one knows well, close is nice. And zoom level means different things depending on the latitude. Some more logic could also be an option. For now I have simple decreased it.

__New Zealand__
The location (New Zealand) is written twice on the screenshot you sent. I am unsure of wether this has to do with you being such an expert user of the existing site that change is confusing or there is genuinely something about the presentation that makes it disappear. Could well be me that is going blind from having seen the new one too much.
 
![screen shot 2017-01-12 at 10 46 21](https://cloud.githubusercontent.com/assets/6759267/21894069/23039216-d8de-11e6-831a-bae3950d2ee4.png)


__images__
I liked this idea when we last talked about it and I still do. It has been captured in [Jira](http://dev.gbif.org/issues/browse/PF-2534), and [Github](https://github.com/gbif/portal16/issues/7) and at the meeting we had in September. Yes: the presence images should be more prominent. Thank you for the reminder. I will make it so and agree that it would be a large improvement.

__dataset description__
The idea was that the description would or could add relevant context to the how the occurrence came about. I'm not settled on how many words and where, but I would think it adds value.
fx: https://demo.gbif.org/occurrence/1338530263 you can see that it is a citizen science project.
Or: https://demo.gbif.org/occurrence/1234530907 about the collection method

__different layouts depending on the occurrence__
I like this idea very much. It has been discussed in [Jira](http://dev.gbif.org/issues/browse/PF-2534), and captured in [Github](https://github.com/gbif/portal16/issues/7). And we talked quite a bit about it in September as well. We all agreed that it would be a very nice addition. It would be useful if someone with more knowledge about the domain could suggest some rules - I'm looking at you @rdmpage  ;)

Thanks
Morten

**Comment by gbif-portal** [comment]
Closed and transferred to  https://github.com/gbif/portal16/issues/225

**Comment by rdmpage** [comment]
@MortenHofft Thanks for the response, I know that this stuff is not easy, and there's lots about the new portal that I like (especially now that I've upgraded to Safari 10 so that the image gallery works).

** Visibility**
the "New Zealand" example is probably more about the effect of colour and whitespace. In the old portal "New Zealand" is a link and so is in blue. It also occurs beside the map, so it seems to stand out more than in the new portal.

**Zoom**
Zooming is going to be tricky, but one thing which might help inform the discussion is if there was a way to record what users did when viewing a map. If the first thing they do is zoom out, then the map zoom needs to be adjusted (likewise if people zoom in overtime they first view the map). I'm guessing there is a away to capture Leaflet events to get some data on this.

**Layout**
For comparison here is a iNaturalist observation http://www.inaturalist.org/observations/3794532 that is also in GBIF https://demo.gbif.org/occurrence/1291162947 iNaturalist displays image and map side-by-side, and instead of displaying metadata as tables it presents information more compactly. I think there's scope for doing something like this, so that "above the fold" we see map, image, geological timescale, text summary, then we get the option to view all the information as a table. Just a thought.

![screenshot 2017-01-12 21 16 40](https://cloud.githubusercontent.com/assets/83306/21908811/51c368b8-d90d-11e6-9486-7724dafb9e94.png)

**Feedback**
I wonder whether something like [Silverback](http://silverbackapp.com) could be useful to get some feedback from users (do they, for example, zoom the map, can they quickly extract key information, etc.). I guess it would also be useful to know what percentage of time people spend on occurrence pages. I tend to look at them a lot, but I'm probably atypical.

**Comment by MortenHofft** [comment]
That is really useful feedback - thank you

**Comment by kcopas** [comment]
Without any additional fiddling or refining of the query (I know one of our statistical anomalies was a call for, like, every species page), [average time on pages with /species/ in URL](https://analytics.google.com/analytics/web/#report/content-pages/a42057855w71692566p73962076/%3F_u.date00%3D20160101%26_u.date01%3D20161231%26_u.date10%3D200101%26_u.date11%3D20151231%26explorer-table.filter%3D%2Fspecies%2F%26explorer-table.plotKeys%3D%5B%5D) is 2:35.

**Comment by MortenHofft** [comment]
For [occurrences](https://analytics.google.com/analytics/web/#report/content-pages/a42057855w71692566p73962076/%3F_u.date00%3D20160101%26_u.date01%3D20161231%26_u.date10%3D200101%26_u.date11%3D20151231%26explorer-table.filter%3D%2Foccurrence%2F%5B0-9%5D%26explorer-table.plotKeys%3D%5B%5D/) it is 1:40

Ideas for interesting things to track is captured here in case anyone has good ideas for this or other pages: https://github.com/gbif/portal16/issues/119

**Comment by rdmpage** [comment]
@MortenHofft 

> Things is a bit tricky in that we have practically no information that we can count on being present

Yep, that makes life a little tricky. However our ignorance is often less than it seems. For example, if a record doesn't have coordinates but does have a country, then we could show a map with a polygon overlay highlighting the country (or identifiable subregion such as province).

If there's no image we could have a placeholder (e.g., from PhyloPic, see https://github.com/gbif/portal-feedback/issues/35 ) so the user has some sense of what they are looking at.

**Comment by rdmpage** [comment]
@MortenHofft Re zooming here's a JSFiddle http://jsfiddle.net/rdmpage/5v9wr2g6/ that I forked to add an alert to show zoom level changes when user clicks on zoom control. Instead of showing an alert this could fire a Google Analytics event so you would have data on how many times people zoom in versus out on a map.

**Comment by rdmpage** [comment]
@MortenHofft @kcopas Sorry I wasn't being clear, what I was after is this: "what percentage of total time spent on the GBIF site by all users is spent on a page which is an occurrence page"

**Comment by MortenHofft** [comment]
of the last 516,265 page views the average time on a page is 2:07 min.
Out of those 34,429 is on occurrence pages and average time is 1:31 min.

That is 52217 min on occurrence pages and 1092757 in total
that is 0.047 ≈ 5% of the total time is spent on occurrence pages. Unless I miscalculated :)

**Comment by kcopas** [comment]
Getting a maths badge ready for you @MortenHofft

**Comment by mdoering** [comment]
I very much like Rods idea to use a placeholder image and the country for sparse records

**Comment by MortenHofft** [comment]
That could well work with place holder image for occurrences.

The country outline idea is captured somewhere - possible with the option for people to suggest a more precise location using the feedback. But there is still the issue that sometimes we have neither. In those cases there is little else to do than showing a picture of the moon or hiding the area altogether.

Either way good and useful ideas. Thanks
