### ISSUE TITLE
Cerastium falcatum (Gren.) Bunge ex Fenzl.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#290]
**Cerastium falcatum (Gren.) Bunge ex Fenzl.**

Cerastium falcatum (Gren.) Bunge ex Fenzl.
= 
Cerastium falcatum Bunge
Synonym of Cerastium maximum L.

?

-----
fbitem-species7439322
Reported by: @bartoszmajcher
System: Chrome 59.0.3071 / Windows 7 0.0.0
Referer: https://demo.gbif.org/species/7439322
Window size: width 1280 - height 918
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-07T14:07:40.674Z',mode:absolute,to:'2017-08-07T14:13:40.674Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-07T14:07:40.674Z',mode:absolute,to:'2017-08-07T14:13:40.674Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by mdoering** [comment]
Not sure what to say about this one. We have
accepted: `Cerastium falcatum (Gren.) Bunge ex Fenzl.`
accepted: `Cerastium maximum L.`
with synonym: `Cerastium falcatum Bunge`

It looks strange to have the invalid earlier name published by Bunge to be a synonym of a different species instead of the Fenzl one (which the nub build usually [automatically creates synonyms](https://www.gbif.org/species/search?origin=EX_AUTHOR_SYNONYM&advanced=1) for), but I am missing evidence to treat this differently.
