### ISSUE TITLE
Issue with display of images

### ISSUE THREAD

**Issue by langeveldNMR** [gbif/portal-feedback#2972]
Dear GBIF,

We recently uploaded more photos to GBIF in our existing dataset https://www.gbif.org/occurrence/search?dataset_key=a307e4d7-1de2-4adc-95d5-a0a8d5f57236 Some of them are with records that previously did not have an image. These are displayed correctly.

However, some of the records did previously have images, but these have been updated with better images with other text in the images, different lighting, colors etc. on our image server. For example: https://www.gbif.org/occurrence/2570169104 This specimen has been reidentified to Chicoreus akritos, but its image on GBIF still shows the incorrect identification, although on our server it is now correct: http://www.nmr-pics.nl/PICTURES/NMR993000096045A.jpg

The thumbnail in gallery view and the image in record view however still generate based on the old version of the picture, e.g. with other lighting or incorrect text within the picture, although the source image has been changed on our server, with the link staying intact. It should refresh on GBIF, but it does not. We suspect GBIF does not recognize that the image has changed and thus does not refresh its thumbnail. Can you solve this?

A related problem concerns e.g. this record: https://www.gbif.org/occurrence/2570122751 Here, the image has been changed on our server, but maintaining the old link and we have not done an upload since. Here as well, the old picture is still displayed instead of: http://www.nmr-pics.nl/PICTURES/NMR993000049647A.jpg Here, GBIF should reindex this picture, but does not have a cue (through uploading or anything) that it may have changed. Can you also solve this?

Furthermore, in a previous issue, we understood that GBIF does not copy the images to their server, but just generates a thumbnail/view based on our link. This now appears not to be the case. Can you explain?

Sincerely and many thanks in advance,

Bram Langeveld
curator Natural History Museum Rotterdam

**Comment by MattBlissett** [comment]
Dear Bram,

Thank you for reporting this. I have removed these images from our cache, so the updated images will be retrieved as users of GBIF.org view the occurrence pages and search gallery.

In order to efficiently provide thumbnailing services at different resolutions, we do hold a copy of the original for a period of time. This also helps us keep load from institutional servers which we know can be very costly (i.e. bandwidth charged at per-MB rates) for some. Our web pages always provide click through to the original images on your server.

Does this pose concerns for you?  Please let us know, and we'll be happy to explore alternatives.

Best regards,

Matthew Blissett

**Comment by MattBlissett** [comment]
Dear Bram,

I cleared all images from `www.nmr-pics.nl` from the cache, which was several thousand.  If this needs to be done again, please either make a new issue in portal-feeback, or send an email to helpdesk@gbif.org.

Thanks,

Matthew

**Comment by jlegind** [comment]
This issue has become pertinent again. Please flush the cache again please.
