### ISSUE TITLE
Feedback link to Pl@ntNet

### ISSUE THREAD

**Issue by ManonGros** [gbif/portal-feedback#3088]
This is a request coming from Pl@ntNet: https://www.gbif.org/publisher/da86174a-a605-43a4-a5e8-53d484152cd3
They have their own feedback system and they would like us to link to the system as we do for iNaturalist.
![Screenshot_2020-11-12 iNaturalist Research-grade Observations](https://user-images.githubusercontent.com/7677271/98927708-30ca4e80-24d9-11eb-8338-1331cc441f20.png)

The links to the original records on their system are available in the "reference" field. For example: https://identify.plantnet.org/the-plant-list/observations/1005331032.

**Comment by ManonGros** [comment]
Sorry @MortenHofft, could we make it so that it applies only to this dataset: https://www.gbif.org/dataset/7a3679ef-5582-4aaa-81f0-8c2545cafc81?
The reference links aren't available for the other dataset published by Pl@ntNet.

**Comment by CecSve** [comment]
Is this implemented?

**Comment by MortenHofft** [comment]
Looks like the config applies to all dataset from the publisher. It looks like we do not have anything in place to do so for individual datasets. But we could look into that.

That said I see that it doesn't show on
https://www.gbif.org/occurrence/3951370398
but do show on
https://www.gbif.org/occurrence/3948965906

presummably because the first doesn't supply a reference. So it seem to do as expected, but I expect it would starting linking to the feedback system if they started to add references to the automatic dataset as well.

**Comment by CecSve** [comment]
@ManonGros what do you think of this - would we still need to look into whether it can be applied for specific datasets? Or do you know if Pl@ntnet would be ok with this fix?

**Comment by ManonGros** [comment]
It looks fine actually. We could double check with Pl@ntnet but I assume it would be ok to close the issue. Thanks!
