### ISSUE TITLE
Monkey classified as fly

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3110]
**Monkey classified as fly**

According to the source for this record, Midas leucogenys Gray, 1866 should be a monkey but it is classified under an insect genus: Mydas Fabricius, 1794

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/8b1cec7b8e8189165edb44238374ae17:82c1bd7d5dedb0aba658f1c1748cdc3ca9cc8426ee207390e78ff6eaff463ab0e443712efc54cc7a67d156c8fccb40921c5be10260b2e4b7ff4972999dee68e2)
System: Safari 14.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/species/8796788
Window size: width 2167 - height 1108
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-25T08:54:25.385Z',mode:absolute,to:'2020-11-25T09:00:25.385Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2020-11-25T08:54:25.385Z',mode:absolute,to:'2020-11-25T09:00:25.385Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by jhnwllr** [comment]
@mdoering 
I think this is a **fuzzy matching issue**. Since genus Midas -> genus Mydas (insect). 

Mydas (insect)
https://www.gbif.org/species/1566547

ZooBank (the source dataset) **does not have any higher taxonomy**, so it cannot be corrected at source so easily. 
https://www.gbif.org/species/141144617
http://zoobank.org/NomenclaturalActs/05f25834-042c-4a64-a4e3-f3c5efc7b595

**Comment by ManonGros** [comment]
Fixed in the new backbone
