### ISSUE TITLE
Display recommended citation for the download in question at the Free of cost - not free of responsibilities

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#315]
**Display recommended citation for the download in question at the Free of cost - not free of responsibilities**

E.g. 

It is imporant for crediting data publishers and for reputation of the data users to cite data correctly. By using the recommended GBIF citation with DOI you will comply to best practice in transparent science. Note that if you are analysing the data you will download, please consider placing the download DOI into your Materials and methods section.

[citation]

[click to copy text citation]

[click to add the reference to the reference management system]

-----
fbitem-8b16037cf12b5f958bf6d374db1c1429764c1b51
Reported by: @dschigel
System: Firefox 52.0.0 / Windows 10 0.0.0
Referer: https://demo.gbif.org/occurrence/download?dataset_key=c05b97bc-e172-40e9-9d42-9df0f93a6e65
Window size: width 1694 - height 819
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-15T09:55:35.108Z',mode:absolute,to:'2017-08-15T10:01:35.108Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-15T09:55:35.108Z',mode:absolute,to:'2017-08-15T10:01:35.108Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kcopas** [comment]
Let's keep this in sync with the email and registration-thank-you messages, please.

+1 for the specific direction of 'placing the download DOI into your Materials and methods section.'

**Comment by dschigel** [comment]
Yes, and one more: when this download actually comes, it reads:

When using this dataset please use the following citation:
    GBIF.org (15th August 2017) GBIF Occurrence Download http://doi.org/10.15468/dl.rfelfv

To match the earlier debated and agreed dataset citation style, need to change to:

   GBIF Occurrence Download http://doi.org/10.15468/dl.rfelfv accessed via GBIF.org on 2017-08-15.

NOTE! We use YYYY-MM-DD in the citation. This is possibly ok, as long as it is uniform, but I would prefer non-ambiguous, though longer DD Month YYYY, or a bit exotic and old school, but also clear Roman numerals for month, 15.VIII.2017.

**Comment by kcopas** [comment]
I worked with @cgendreau last week while you were away to update the post-registration message—so, yeah, that's the point. There shouldn't be any daylight between any of these, and they should reinforce each other as and where possible.

**Comment by MortenHofft** [comment]
Thanks @dschigel 
Unfortunately the DOI doesn't exist before the download, so downloading the showing and downloading the citation is an option in the popup.

Reason: adding the citation string at that point isn't an option as the download hasn't been created yet and hence doesn't have a DOI. We could initiate the download, but it would mean that the download is initiated before the user accepts. And opening the popup twice would initiate the download again. 
To do it properly an API change is needed as far as I can see. One that allows for minting a citation for a download that doesn't exist yet.

I've updated the sentence format on the occurrence download page.

I'm marking this as an API issue, unless anyone have a good idea for how to show citations before downloading.

BUT: we could change the remaining text of course

Currently 
```
The data in GBIF is the work of thousands. Proper attribution helps ensure that data like this will also be available in the future. Thank you for your understanding.
```
@kcopas  let me know if i should replace the text and with what (I assume that it will have to be changed a bit since showing the citation string isn't an option)

NB: I have updated the citation string on the occurrence download pages as described above.

**Comment by dschigel** [comment]
A fix is to add something like:

It is imporant for crediting data publishers and for reputation of the data users to cite data correctly. You will receive the recommended GBIF citation, including DOI, together with your requested data. By citing data correctly you will comply to best practice in transparent science.

Note that if you are analysing the data you will download, please consider placing the download DOI into your Materials and methods section.

**Comment by kcopas** [comment]
[One more moving part](https://demo.gbif.org/citation-guidelines) to consider...

**Comment by MortenHofft** [comment]
the text is updated - thanks dschigel

**Comment by MortenHofft** [comment]
I've moved the remainder of this into this API request https://github.com/gbif/portal16/issues/485
