### ISSUE TITLE
Literature topics

### ISSUE THREAD

**Issue by alycejenni** [gbif/portal-feedback#3160]
Could anyone tell me how topic tags are assigned to literature resources on GBIF?
i.e. the topics [here](https://www.gbif.org/resource/search?contentType=literature):

![image](https://user-images.githubusercontent.com/23579762/102488581-2b29d080-4064-11eb-9776-227bb3441bcd.png)

Are they sourced from somewhere else, manually categorised, etc? They don't appear to match up with sources like Crossref/ASJC so I'm just wondering how they're determined.

Thanks!

**Comment by kcopas** [comment]
They’re manually curated. 

It’s been a while since we explored it again, but we’ve never found an existing taxonomy that’s sufficiently fine-grained to capture the range of most common uses. We’d be open to suggestions, recognizing that we’d have 10k+ citations to retrofit.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
