### ISSUE TITLE
Strange locations on sea for plantae

### ISSUE THREAD

**Issue by yvanlebras** [gbif/portal-feedback#3171]
Dear GBIF colleagues,

Hope all is ok for you on this end of 2020!

It seems to me strange to see some plantae occurrences from CBN dataset in the middle of biscay bay :https://www.gbif.org/fr/occurrence/search?dataset_key=75956ee6-1a2b-4fa3-b3e8-ccda64ce6c2d&geometry=POLYGON((-7.80474%2045.43594,-5.46877%2045.43594,-5.46877%2047.07113,-7.80474%2047.07113,-7.80474%2045.43594))&has_coordinate=true&has_geospatial_issue=false&occurrence_status=present . 

Is there an explanation ?

Whishing you an happy end of year.

Kind Regards,

Yvan

**Comment by jhnwllr** [comment]
All of the records you highlight have the issue "PRESUMED_NEGATED_LONGITUDE" attached to them.

It appears that the records are close to the border of France, and then GBIF geocodes them as being within Switzerland: 
http://api.gbif.org/v1/geocode/reverse?lat=46.4104&lng=6.19032

The records fill in the the countryCode = FR. 

Because flipping the sign of the longitude puts them within the EEZ waters of France, GBIF negates the longitude, so the records end up in the ocean: 
http://api.gbif.org/v1/geocode/reverse?lat=46.4104&lng=-6.19032

I am not sure how the fix the issue at this point, but that is what is going on.

**Comment by timhirsch** [comment]
Looking at a couple of these records, I see that they have relatively large coordinate uncertainty values (5000m) which presumably is the explanation for why at least some of them are interpreted as occurring the 'wrong' side of the border. It looks like this is a bug resulting in false positives for the 'presumed_negated_longitude' issue, and perhaps our informatics team could adjust this issue flag so that the coordinates are not flipped in cases where the coordinate uncertainty is greater than the distance from an international border? I realise this may not be simple to fix.
