### ISSUE TITLE
FAQs incomplete: only 3 occurrence download formats ???

### ISSUE THREAD

**Issue by abubelinha** [gbif/portal-feedback#3188]
I only see 3 possible download formats mentioned [in the FAQs](https://www.gbif.org/faq?question=download-formats), but I found at least 8 different values returned by occurrence download API:

SIMPLE_CSV
DWCA
SPECIES_LIST
**_BIONOMIA
MAP_OF_LIFE
SIMPLE_AVRO
SIMPLE_WITH_VERBATIM_AVRO
SQL_**

Can you provide descriptions for the last **five** formats?
Where can we see/produce examples of those download formats?

Thanks a lot in advance

**Comment by MattBlissett** [comment]
* BIONOMIA: This is a custom export format to support the [Bionomia](https://bionomia.net/) project.
* MAP_OF_LIFE: This is a custom export format to support the [Map of Life](https://mol.org/) project.
* SIMPLE_AVRO: This has the same columns as a SIMPLE_CSV format, but instead of using tab-delimited text files, it uses Apache AVRO format.  That's useful for working with big data tools, e.g. querying using a Hadoop cluster, Google BigQuery, Amazon/Azure/etc services.
* SIMPLE_WITH_VERBATIM_AVRO: This extends the SIMPLE_AVRO format and adds the verbatim data, similar to the DWCA format which has the interpreted occurrence.txt and the verbatim verbatim.txt files.  Again, the purpose is for better integration with big data tools.

The Bionomia and Map of Life formats aren't intended for general use, since they may be changed as required by those projects.

The Avro formats will be documented when they're stable, and ready for general use.  We are still testing integrations with various big data systems, and might need to adjust the format for wide compatibility.

The SQL format was abandoned during development. There are no longer any SQL downloads.

**Comment by jlegind** [comment]
Question was answered.
