### ISSUE TITLE
Font decoding issue

### ISSUE THREAD

**Issue by myrmoteras** [gbif/portal-feedback#3191]
https://www.gbif.org/species/176568180

this treatment has font decoding issues 

![image](https://user-images.githubusercontent.com/4609956/104245702-0824ed80-5465-11eb-8b27-d367f3aa6d05.png)
that are not in the original treatment in TB.

![image](https://user-images.githubusercontent.com/4609956/104245733-16730980-5465-11eb-9d47-98e854cd846f.png)

**Comment by gsautter** [comment]
I did see this ... but the DwC-A is encoded properly ... looks like GBIF is experiencing trouble properly displaying UTF-8 characters outside the basic ASCII range ...

**Comment by MattBlissett** [comment]
Thanks Donat, Guido for reporting this.  It was a strange situation -- if a developer using a Mac with a specific language configuration restarted our ingestion processes, the Mac's language/Unicode settings "leaked" into the Linux VM and caused the corruption.

I've improved the Java code, prevented the "leak" of settings, and re-ingested the affected datasets.

**Comment by gsautter** [comment]
> I've improved the Java code, prevented the "leak" of settings, and re-ingested the affected datasets.

@MattBlissett Just out of curiosity, what exactly was going on there? As Plazi is running pretty much completely on Java, I'd me interested to know what kind of pitfalls there might be in this regard ...

**Comment by MattBlissett** [comment]
All the Linux servers default to Unicode, like anything Linux from the last 15+ years or so.  This is done with the `LANG` environment variable; in our case set to LANG="en_GB.UTF-8" (I prefer the day-month-year date order this gives).  There are `LC_*` variables that can override particular bits, so I could set `LC_MONETARY=da_DK.UTF-8` if I cared to have the default currency in Danish crowns (see `locale`).

When Java starts up, it reads these variables to determine the default character encoding, e.g. for `System.out.println("€5")` and input/outputstreams without a specified encoding.  `Charsets.defaultCharset()` shows the default the JVM has chosen.

Mac OS uses the same set of environment variables, but the values are structured differently.  It sets `LC_CTYPE=UTF-8`, which Linux doesn't recognize — OpenJDK falls back to ASCII, and that `System.out.println("€5")` would print `?5`.

OpenSSH's default configuration on CentOS and Ubuntu allows the client to set the `LANG` and `LC_*` variables, so the unrecognized Mac OS value was being brought over to Linux.  Someone restarted one of our interpretation services with this environment variable set, and the DWCA library had a place where the default character encoding was used.

It's gone unnoticed for so long because only one path in the DWCA library was affected (sorting extension files where the sort key is not the first column), and the people who normally deploy/restart this service use Linux, or a Mac that doesn't set LC_CTYPE -- it seems to depend on the particular terminal program in use on the Mac.

**Comment by MattBlissett** [comment]
We already had e.g. 
```java
new InputStreamReader(fis, StandardCharsets.UTF-8));
```
pretty much everywhere, but in this case there was a `FileWriter`, which is an old convenience class using the default encoding.

I did wonder if a Java linter would have picked this up.

**Comment by gsautter** [comment]
@MattBlissett Thanks you very much for the details, this is really good to know ...
Fortunately, I've pretty much always been using `InputStreamReader` and `OutputStreamWriter`, as `UTF-8` vs. `Cp1252` always was an issue ... also gives more flexibility regarding were IO happens from and to, as you can wrap them around generic `InputStream`s and `OutputStream`s no matter where the latter connect to ...

Not sure about "Java linter", never actually used it ... but the "Call Hierarchy" search in Eclipse comes in pretty handy to track down such legacy code as well.

The really astounding part is how environment variables from the session that restarts a service leak over into the session the service proper runs in, though ... not a Linux expert, but I know a person who should be able to shed some light.

**Comment by gsautter** [comment]
> Not sure about "Java linter", never actually used it ... but the "Call Hierarchy" search in Eclipse comes in pretty handy to track down such legacy code as well.

Meaning the call hierarchy of JRE convenience class constructors that use the JRE standard encoding ... could be you need a JDK installed for this functionality ...

**Comment by MattBlissett** [comment]
> as UTF-8 vs. Cp1252 always was an issue

Yes, that use of the default encoding would have been noticed long ago if at least one developer used Windows, but none of us do.

> The really astounding part is how environment variables from the session that restarts a service leak over into the session the service proper runs in, though

The CLI services are just deployed as background processes, not system services or anything like that.  We can easily start more processes on the same VM when required, but this issue is a disadvantage.

**Comment by gsautter** [comment]
> The CLI services are just deployed as background processes, not system services or anything like that. We can easily start more processes on the same VM when required, but this issue is a disadvantage.

Ah, OK, that explains a lot, thank you.
