### ISSUE TITLE
Resource failed to appear in the portal after publishing it through our IPT

### ISSUE THREAD

**Issue by EstebanMH-SiB** [gbif/portal-feedback#3192]
I did a publication through our IPT (ParquesNacionales-SiB Colombia) in november, but when I access the portal it shows this message "*The system is currently not able to process your request. Try to refresh the page and please report the issue if it continues*". Today I did another attempt to check if maybe the problem solve by itself, but is still not working.

![image](https://user-images.githubusercontent.com/63795703/104372950-339fea80-54ee-11eb-929c-9dc2524e23ca.png)

I don't see any problem with the content (data or metadata) in the resource, the only abnormal thing is the name in the URL of our IPT, in this case is really long. But I don't know if this can be a problem.

**Link IPT**:https://ipt.biodiversidad.co/parquesnacionales/resource?r=area_chingaza_demografia_y_propagacion_de_palmas_andinas_con_potencial_ornamental_en_colombia_2019_diciembre-datos_completos_2020_8_18_15_39_2
**Link GBIF**:https://www.gbif.org/dataset/b2b259a4-a7c7-49f5-87a0-d298bddf747a

Thanks in advance,
Esteban SiB Colombia @RicardoOrtizG @camiplata @SiBColombia

**Comment by MortenHofft** [comment]
It tries to format the urls, but since the dataset contains (what it consider to be) malformed urls the parser failed. It will now fail more gracefully and just show the raw text when it cannot parse the urls.

This was the url it didn't like
www.meta.gov.co/san_juanito/$contigog3n3ramoso$portunidad%3

if you follow the link the console also report that it is malformed
```
The attempt to bind "/san_juanito/$contigog3n3ramoso$portunidad%3" in the workspace failed as this URI is malformed.
```
