### ISSUE TITLE
Species with species element empty in SIMPLE download

### ISSUE THREAD

**Issue by RicardoOrtizG** [gbif/portal-feedback#3217]
Hi,

When a Download is made, I found that some species have not the species element documented in the download (SIMPLE Download), even when taxonRank is documented as SPECIES.

The species are.

- Basileuterus tristriatus
- Aconitum napellus
- Phlegopsis barringeri
- Anemone alba Juss
- Scytalopus sanctamartae

Please let me know if this is a mistake or maybe there is a reason and I need to take that always into count.

Thanks

Image of the download for Basileuterus tristriatus
![image](https://user-images.githubusercontent.com/15789737/105775362-b71cfb00-5f34-11eb-838a-c241764d88d8.png)

@camiplata @SiBColombia

**Comment by MattBlissett** [comment]
Thanks for reporting this.  It seems to be a bug in our taxonomic backbone, where there is incomplete data for some names.  We're currently working on an updated backbone, and have an issue for this problem here: https://github.com/gbif/checklistbank/issues/161

The `taxonKey` column does have the correct value in it, but `speciesKey` is empty -- it should be the same for these records.

**Comment by RicardoOrtizG** [comment]
Yes, it seems the same. We will be attentive to changes in the taxonomic backbone. For now, we will have this in mind for our biodiversity data consolidations.

**Comment by jlegind** [comment]
Hi, 
The issue persists for downloads of these five species. Currently there are 1.119 records in the download with a blank species field.
Those records are in the HIVE table _jan.download3217_

Download link: 
https://www.gbif.org/occurrence/download/0004092-210819072339941

**Comment by jlegind** [comment]
After backbone update:
The download had no blank scientific_names with filter:rank==species
Download: https://www.gbif.org/occurrence/download/0006131-210914110416597
@RicardoOrtizG
