### ISSUE TITLE
Hedera hibernica (G.Kirchn.) Bean - Hedera hibernica Poit.

### ISSUE THREAD

**Issue by damianooldoni** [gbif/portal-feedback#3225]
Based on opinion of two expert botanists (@qgroom and @woutervanlanduyt) and based on the importance of detecting emerging alien species worldwide, @timadriaens and I find very important and urgent mentioning that these two taxa should be linked as one is synonym of the other:

- [Hedera hibernica (G.Kirchn.) Bean](https://www.gbif.org/species/8410115)
- [Hedera hibernica Poit.](https://www.gbif.org/species/8168344)

I did a fast check and it seems no occurrence dataset mentions both taxa: this is a sign they are never judged as different species.
What do you think about it? Is it something can be discussed internally by GBIF or is something should change somewhere else?
We appreciate of course how GBIF Backbone links a lot of synonyms to these two taxa already. This would be a last step forward, we think.

**Comment by damianooldoni** [comment]
Did you have time to check this already? Or is there any update planned in the near future? Thanks a lot.

**Comment by ManonGros** [comment]
The name [Hedera hibernica (G.Kirchn.) Bean](https://www.gbif.org/species/8410115) comes from the [Checklist Dutch Species Register - Nederlands Soortenregister](https://www.gbif.org/dataset/4dd32523-a3a3-43b7-84df-4cda02f15cf7) while the name [Hedera hibernica Poit.](https://www.gbif.org/species/8168344) comes from the [World Checklist of Selected Plant Families](https://www.gbif.org/dataset/92562ba8-21af-4836-a80a-c31237efe3c5) which is one of the CoL partner.

I suppose that one way to solve this issue is to ask if Hedera hibernica (G.Kirchn.) Bean could be added as a synonym in the CoL. What do you think @mdoering?

**Comment by mdoering** [comment]
We have the following in GBIF:


> [Hedera hibernica (G.Kirchn.) Carrière](https://www.gbif.org/species/3036157) [Dyntaxa]
> ≡ Hedera helix f. hibernica G.Kirchn. [GRIN]
> ≡ Hedera hibernica (G.Kirchn.) Bean [Dutch Register]
> = Hedera canariensis Hibberd, 1864 [TaxREF]


Largely from WCVP:
> [Hedera hibernica Poit.](https://www.gbif.org/species/8168344) [WCVP]
> = Hedera canariensis var. maculata (Hibberd) Hibberd  [WCVP]
> = Hedera grandifolia var. maculata Hibberd  [WCVP]
> ≡ Hedera helix f. hibernica (Poit.) P.D.Sell  [WCVP]
> = Hedera helix f. maculata (Hibberd) Tobler  [WCVP]
> ≡ Hedera helix subsp. hibernica (Poit.) D.C.McClint.  [WCVP]
> ≡ Hedera helix var. hibernica (Poit.) G.Kirchn.  [WCVP]
> = Hedera helix var. maculata (Hibberd) Rehder  [WCVP]
> = Hedera hibernica subsp. aureomarginata Carrière  [WCVP]
> = Hedera hibernica subsp. marginata Carrière  [WCVP]
> = Hedera hibernica var. maculata (Hibberd) Bean  [WCVP]
> = Hedera vegeta G.Nicholson  [WCVP]
> = Hedera vitifolia G.Nicholson  [WCVP]


[IPNI](https://www.ipni.org/?q=Hedera%20hibernica) has various, with Hedera hibernica Carrière listed as an invalid name:

> Hedera helix var. hibernica G.Kirchn., Arbor. Muscav. [Petzold & Kirchner] 419 (1864). POWO 
> Hedera helix f. hibernica (G.Kirchn.) P.D.Sell, Fl. Gr. Brit. Ireland 3: 518 (2009). POWO 
> Hedera helix subsp. hibernica (G.Kirchn.) D.C.McClint., Suppl. Wild Flow. Guernsey 23 (1987): (1987). POWO 
> Hedera hibernica (G.Kirchn.) Bean, Trees & Shrubs Brit. Isles 1: 609 (1914).
> Hedera hibernica Poit., Bon Jard. 1835: 731 (1835). BHL  POWO 
> Hedera hibernica Carrière, Rev. Hort. [Paris]. 62: 163 (1890), nom. inval.

The basionym form seems agreeable all over and the heterotypic synonyms in WCVP can also be found in Wikipedia. The only potentially doubtful synonym I can see is `Hedera canariensis Hibberd` from TaxREF.

Are we sure what the currently accepted name is if we merge these names into a single concept?
 - Hedera hibernica (G.Kirchn.) Bean (accepted by [Dutch](https://www.nederlandsesoorten.nl/linnaeus_ng/app/views/species/nsr_taxon.php?id=186365) & [Wikipedia](https://en.wikipedia.org/wiki/Hedera_hibernica))
 - Hedera hibernica Poit. (accepted by [Kew/WCVP](https://wcsp.science.kew.org/namedetail.do?name_id=96738) and therefore COL)

I would propose to make Hedera hibernica (G.Kirchn.) Carrière and Poit both a synonym of Hedera hibernica (G.Kirchn.) Bean ???

**Comment by mdoering** [comment]
To make things worse, [WFO](http://www.worldfloraonline.org/taxon/wfo-0000979815 ) lists the according to IPNI invalid name `Hedera hibernica (G.Kirchn.) Carrière` as the accepted.

**Comment by mdoering** [comment]
The [Leipzig catalogue also has Hedera hibernica (G.Kirchn.) Carrière](https://data.catalogueoflife.org/dataset/2262/taxon/Hedera_hibernica) as the accepted name.

**Comment by mdoering** [comment]
From the 3 usages to pick from:

> Hedera hibernica (G.Kirchn.) Bean, Trees & Shrubs Brit. Isles 1: 609 (1914).
> Hedera hibernica Poit., Bon Jard. 1835: 731 (1835). BHL POWO
> Hedera hibernica Carrière, Rev. Hort. [Paris]. 62: 163 (1890), nom. inval.

Looking at these 3 names in chronological order including the basionym:

> Hedera hibernica Poit., Bon Jard. 1835: 731 (1835). BHL POWO
> Hedera helix var. hibernica G.Kirchn., Arbor. Muscav. [Petzold & Kirchner] 419 (1864). POWO
> Hedera hibernica Carrière, Rev. Hort. [Paris]. 62: 163 (1890), nom. inval.
> Hedera hibernica (G.Kirchn.) Bean, Trees & Shrubs Brit. Isles 1: 609 (1914).

I cannot judge which is the best to pick. Unfortunately I will have to select one to setup a synonymy.

EuroMed has Hedera hibernica (G. Kirchn.) Carrière as the accepted name:
http://ww2.bgbm.org/EuroPlusMed/PTaxonDetail.asp?NameCache=Hedera%20hibernica&PTRefFk=8000000

Summary so far:
 - Bean: Wikipedia, Dyntaxa, GRIN, ITIS, UKSI, TaxREF
 - Carrière: EuroMed, Leipzig, WFO, Artsnavnebasen, Denmark National List, TPL
 - Poit: Kew/WCVP -> COL, GRIIS, [WikiSpecies](https://species.wikimedia.org/wiki/Hedera_hibernica)

Not an easy one. But it is better to pick the wrong one and get the synonymy right than keeping 2 accepted species.
As Poit. is at least the earliest and used in COL I will setup that one unless I am informed otherwise.
