### ISSUE TITLE
Institution code wrongly interpreted

### ISSUE THREAD

**Issue by DimEvil** [gbif/portal-feedback#3227]
In https://www.gbif.org/dataset/5ca32e22-1f1b-4478-ba7f-1916c4e88d67 the institutionCode "VMM" is wrongly interpreted ("Institution match fuzzy") as Vanderbilt Marine Museum. It should be Flanders Environment Agency (VMM)  , which is a Dutch abbreviation, but official.

Can this be corrected?

VMM Vanderbilt Marine Museum | VMM | Institution match fuzzy
-- | -- | --

**Comment by ManonGros** [comment]
Hi @DimEvil 
These flags are our attempt to link GBIF records to GrSciColl: https://www.gbif.org/grscicoll
I created an entry for the VMM on GrSciColl: https://www.gbif.org/grscicoll/institution/fc782d88-9d65-4e41-add2-013bfa447539
But since two institutions now use the same Code, I suggest to provide an institutionID as well.
More information on the topic here: https://www.gbif.org/faq?question=how-can-i-improve-the-matching-of-occurrence-records-with-grscicoll

I am closing the issue for now, let me know if you have any question and email scientific-collections@gbif.org to request updates on GrSciColl. Thanks!
