### ISSUE TITLE
Possible coordinate mistake

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3264]
**Possible coordinate mistake**

I spotted these records originally by noticing a mountain lion out at sea on a species page which looked suspicious.

While there are islands in the area, I think the coordinates for these may be wrong at source (or at least some of them).

Thanks

-----

Github user: @timrobertson100
User: [See in registry](https://www.gbif.org/api/feedback/user/9cb49d279b400923663ae3755e46ce73:eb51b1ce58bf900404f703f0adf3489294dbb22eb97db456996ae789f9d03ba11f5a58b9aac923a3aefdca1f64b5f9dd9a98f79fa409c60586e7a53ffa3cc60d)
System: Chrome 88.0.4324 / Mac OS X 10.15.7
Referer: https://www.gbif.org/dataset/a6058f47-15ae-412e-b316-912dd6e2ec9b
Window size: width 2327 - height 1338
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-02-16T12:38:34.610Z',to:'2021-02-16T12:44:34.610Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-02-16T12:38:34.610Z',to:'2021-02-16T12:44:34.610Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by timhirsch** [comment]
@timrobertson100 on a quick look at this, I think the error is probably our own interpretation of an assumed coordinate flip due to the position falling slightly across the border in Brazil or Uruguay, due to coordinate rounding, while the 'flipped' position falls within Argentina's EEZ. This has come up before when occurrences are close to national boundaries, and should probably be investigated before returning this to the publisher for correction.

**Comment by timrobertson100** [comment]
Thanks @timhirsch 
You are correct. Closing and reopening as a bug in the correct place.
