### ISSUE TITLE
Mallomas: conflation of fungal parasite with host, Index Fungorum 

### ISSUE THREAD

**Issue by ahahn-gbif** [gbif/portal-feedback#3284]
context: backbone release test 2.3.21
https://www.gbif-uat.org/species/8372273
Genus Mallomonas
source: Index Fungorum - "tridentata parasite" of Mallomonas teilingii logged under fungi, but with the M. species in the scientific name
check: other similar cases (systematic I.F. issue?)
occurrences belong to the algae genus

**Comment by ManonGros** [comment]
The classification is correct in the CoL: https://www.catalogueoflife.org/data/taxon/7PDTH
The issue came from [Index Fungorum](https://www.gbif.org/dataset/bf3db7c9-5e5d-4fd0-bd5b-94539eaf9598).
This is unexpected as IF has a lower priority than CoL on [this list](https://hosted-datasets.gbif.org/datasets/backbone/backbone-config.yaml).
The question is why wasn't Mallomonas matched to https://www.gbif.org/species/3195066?

**Comment by ahahn-gbif** [comment]
IF version of the genus: https://www.gbif.org/species/113450270/verbatim
with one "accepted" species: https://www.gbif.org/species/113451833/verbatim
The linked occurrence records (https://www.gbif.org/occurrence/search?taxon_key=8372273) appear to be matched on the basis of a) species name not in the backbone (type specimens) and/or b) genus name not having an author team; at least b) needs verification (@mdoering?)

**Comment by ahahn-gbif** [comment]
also see comments trail to #398

**Comment by ahahn-gbif** [comment]
Species Fungorum (https://www.speciesfungorum.org/) presently contributes through the CoL, and does not contain this genus any more. Need to verify whether a separate checklist contribution is still meaningful and requires an update, or whether the rather stale Index Fungorum dataset (https://www.gbif.org/dataset/bf3db7c9-5e5d-4fd0-bd5b-94539eaf9598) should rather be retired.

**Comment by ahahn-gbif** [comment]
The outdated version of "Index Fungorum" (https://www.gbif.org/dataset/bf3db7c9-5e5d-4fd0-bd5b-94539eaf9598) is currently a hosted dataset, with an endpoint at https://hosted-datasets.gbif.org/datasets/index_fungorum.zip. If fixing this issue is important enough, GBIF could update and re-zip the dataset locally before the next backbone build, though a dynamic, fully refreshed version would be very much preferred.

**Comment by mdoering** [comment]
IF is indeed outdated on GBIF. COL has newer versions from January 2020 of both Index and Species Fungorum (which gets used in COL):

https://data.catalogueoflife.org/dataset/2073/imports
https://data.catalogueoflife.org/dataset/2034/imports

We could use these copies, but I also wonder what gain there would be. We would also have to create a dwc archive from it first as the source files are ColDP. COL CLB can do a generic dwca download though, so that isn't very difficult for manual one offs.

**Comment by mdoering** [comment]
COL uses 305,893 names from SF. All of Fungi and come groups from Chromista but not all:
https://www.catalogueoflife.org/data/dataset/2073

The entire dataset has 306,252 names, just 359 names missing.

**Comment by mdoering** [comment]
I am inclined to remove IF from our source list. There are 110.000 names from IF in our backbone currently though:
https://www.gbif.org/species/search?dataset_key=d7dddbf4-2cf0-4f39-9b2a-bb099caae36c&constituent_key=bf3db7c9-5e5d-4fd0-bd5b-94539eaf9598&advanced=1

108.000 for Fungi, only 603 for Chromista. Checking the first 3 manually:

 - [Rozella longicollis Karling](https://www.gbif.org/species/2512777) classified as incertae sedis all over in IF
 - [Ceracea corticioides (Ellis & Everh.) Pat.](https://www.gbif.org/species/2512834) a homotypic synonym of Dacrymyces corticioides which only exists in [IF](http://www.indexfungorum.org/names/NamesRecord.asp?RecordID=242431) but misses in SF
 - [Exidia pedunculata](https://www.gbif.org/species/2512897) exists as types in harvard
 
Mallomonas was probably not matched because in IF it is in the incertae sedis kingdom
 
Maybe we should just update to the COL version of IF in GBIF

**Comment by ahahn-gbif** [comment]
> Maybe we should just update to the COL version of IF in GBIF

Agree

**Comment by ManonGros** [comment]
Fixed in the new backbone: https://www.gbif.org/species/8372273
