### ISSUE TITLE
Why is Amanita muscaria (L.) Lam., 1783 deleted ?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3319]
**Why is Amanita muscaria (L.) Lam., 1783 deleted ?**

Hello,

The species Amanita muscaria (L.) Lam., 1783 (id 8671098) has been deleted and replaced by Amanita muscaria (L.) Lam. (id 8168319).

Why ?

How could I know if other taxa have been deleted/replaced ? 

Best regards.

Félicien

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/348f07b22e87d7b3768d54dbac900e35:57136ef52ccf7bead918ed5839664f1bf7930649cca5ade5467a051d53f95bafaacf1b1581768570890247e6f4d059a8c11dae51799059305227e519a322ec73)
System: Safari 14.0.3 / Mac OS X 10.15.6
Referer: https://www.gbif.org/species/8671098
Window size: width 1280 - height 642
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-11T23:37:22.471Z',to:'2021-03-11T23:43:22.471Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-11T23:37:22.471Z',to:'2021-03-11T23:43:22.471Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Replied by email:

The GBIF backbone taxonomy is constructed and updated semi-automatically. We use various taxonomic sources and try to assemble them in a larger taxonomy (see [this blogpost](https://data-blog.gbif.org/post/gbif-backbone-taxonomy/) for more details). Whenever possible, our system reuses the same identifiers for the same names. However, sometimes backbone building might require to delete some taxa.

I suspect that the taxon https://www.gbif.org/species/8671098 could have been deleted because it had a duplicate (probably because the Genera had different authorship).
Unfortunately, there is no easy way to find out the deleted taxa and the ones that have replaced them.

**Comment by feliciencorbat** [comment]
Thank you for your answer.

I solved the problem with a python script to get the list of deleted taxa (with GBIF API). There were quite a few in the fungi.

Best regards.
