### ISSUE TITLE
Different content of downloaded DwC-archive depending on route of downloading.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3329]
**Different content of downloaded DwC-archive depending on route of downloading.**

When downloading a sampling-event dataset as a DwC-archive I get different csv-files depending on how I download it.
1) If I choose "Source archive" straight from the box with three alternatives that appears when you click "download", I get 5 files in total: the three csv-files event, occurrence, extendedmeasurementorfact, and the two xml-files EML and meta. And these contain exactly the same info as in the DwC-archive we produce and upload through the IPT.
2) If I instead first choose the first option in the "download-box", i.e. I click "GBIF annotated archive Recommended", and then choose the middle option "Darwin Core Archive" I get 7 files + 1 folder (called "dataset"): the seven files consisting of 5 csv-files (citations, multimedia, occurrence, rights, verbatim) and 2 xml-files (meta, metadata).

In option 2, I can see that all the DwC-terms (fields) that we included in the Event and Occurrence tables in the DwC-archive that we created have been "joined" in the csv-file "verbatim" (along with millions more!). However, I can't find the information that we supplied in the eMoF-table. Why is that not included here? According to the description of the three download options ("Simple", "DwC-archive" and "Species list"), this alternative should include the raw data... Why do you not get the event and occurrence tables separately like they're produced?

Also, in option 2, in the downloaded occurrence-file, the content of one field has been altered compared to our original and the verbatim-file. (This is in the dataset Swedish Bird Survey: Swedish coastal bird... with DOI: 10.15468/sg5spw.) In the lifeStage-field we have the alternatives "adult", "pulli" or blank, but all the occurrences that should have "pulli" in that field are now blank. Why? And how does a user know which version to get data from?

Many thanks in advance!
/Annelie Jönsson, Lund University

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/bf5de6089ec1d4d2176c6bc607f29a67:2c4c3d75c55462038f85194f0ce9e9f9f9506583fc25018059abf30caa898d8ee97d3704982f13f604b74358c684011d6bc43eb67c602254a3a8da41108648d031d0140da3b2d8e8a0033f8630f4f443)
System: Chrome 89.0.4389 / Windows 10.0.0
Referer: https://www.gbif.org/faq
Window size: width 1920 - height 969
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-17T17:00:36.855Z',to:'2021-03-17T17:06:36.855Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-17T17:00:36.855Z',to:'2021-03-17T17:06:36.855Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by anneliejonsson** [comment]
Any thoughts on this? 

All the best,
A

**Comment by jlegind** [comment]
Hello AM,

So this is about the differences between the published archive and the GBIF interpreted user download of https://www.gbif.org/dataset/093d659d-99e1-4bd0-9de7-6330b361ea54.

The issue here is that the GBIF index/occurrence database does not support the 'extended measurement or fact' extension. The fields in the extension (https://tools.gbif.org/dwca-validator/extension.do?id=http://rs.iobis.org/obis/terms/ExtendedMeasurementOrFact) do not exist in the DB.

The source archive is the 'raw' data submitted to GBIF and the annotated download is data that has gone through a number of consistency checks, taxonomic backbone matching, flagging of potential issues.
The GBIF data model caters to (at any given time) a fixed number of concepts, which is why the eMoF extension is currently not ingested. 
GBIF will over time take on more concepts into the whole process and make that available to users, but it is time consuming due to the complexities involved.

**Comment by anneliejonsson** [comment]
Thank you for the explanation! 

Perhaps I'm being a little bit lazy when I ask this, but, is this made clear to users somewhere obvious on the GBIF-page? That there may be data missing when downloading data through the "Recommended" route?

Also, how can one find out how the data in the "occurrence"-file (from the recommended download route) is adjusted (i.e. what the consistence checks etc include, and what are the allowed values in certain fields)? I'm referring to the fact that some of the content in one of our fields has been deleted once it's gone through the GBIF consistency checks etc. I mentioned it in my original question (the last paragraph), i.e. the stuff about the word "pulli" being deleted but the word "adult" is still there.

**Comment by anneliejonsson** [comment]
I understand that one could use the DwC-term dynamicProperties instead of the eMoF, but I haven't done so since I find the eMoF easier to understand.

But, does GBIF support the use of dynamicProperties? Would data be included in the output from a "Recommended" download if we were to put it in dynamicProperties instead?

Many thanks in advance!

**Comment by jlegind** [comment]
> Thank you for the explanation!
> 
> Perhaps I'm being a little bit lazy when I ask this, but, is this made clear to users somewhere obvious on the GBIF-page? That there may be data missing when downloading data through the "Recommended" route?
> 


Regarding GBIF interpretation of the 'raw' data, I recommend reading this blog post which deals with issues according to GBIF: https://data-blog.gbif.org/post/issues-and-flags/ 
The blog post table is divided into themes: Geospatial, taxonomic, date issues, vocabulary issues, GRSciColl related issues, and 'other' issues.

**Comment by jlegind** [comment]
> 
>... I'm referring to the fact that some of the content in one of our fields has been deleted once it's gone through the GBIF  
> consistency checks etc. I mentioned it in my original question (the last paragraph), i.e. the stuff about the word "pulli" being
>  deleted but the word "adult" is still there.

The terms in the 'lifestage' concept are limited to those you can see here:  https://registry.gbif.org/vocabulary/LifeStage/concepts

You would have to translate 'pulli' into one of these concepts.

GBIF is in the process of improving the way in which we manage vocabularies, so that we have more flexibility for data managers to get involved in the process which has historically been slow.

**Comment by MattBlissett** [comment]
@anneliejonsson, Jan:

> I understand that one could use the DwC-term dynamicProperties instead of the eMoF, but I haven't done so since I find the eMoF easier to understand.

Even though GBIF doesn't yet support the eMoF extension, it's probably still the better choice -- the structure of the data is much better suited for reuse, since it's easier to understand for users of the data as well as publishers.

> You would have to translate 'pulli' into one of these concepts.

I have added "pulli" and "pullus" as alternative labels of "nestling", and reprocessed this dataset.  The occurrences (like [this one](https://www.gbif.org/occurrence/3047972625)) now show "Nestling".

**Comment by ManonGros** [comment]
@anneliejonsson I hope this answers your questions. I will close the issue now, please let us know if it should be reopened.
