### ISSUE TITLE
I don't understand the numbers in the Species browser

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3344]
**I don&#39;t understand the numbers in the Species browser**

In the gbif web portal's Species browser (https://www.gbif.org/species/search), when I look under "Rank," I see the number 4,668,426 after "Species." I assume that's the number of identified species on Earth. But if I look under "Higher Taxon," I see the number 4,023,110 after Animalia and the number 1,827,213 after Plantae, which add up to 5,850,323. That number is larger than the number for all Species in under "Rank." Shouldn't all the numbers under "Higher taxon" add up to 4,668,426? Please let me know what I'm missing, thanks!

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/3f524776157e5dc51ad94d02a30cfd9c:67e923dfbfe12f73cf7dd9c74f80f4cc54127fc83aa38f87715ea6b2e8bd28b209f6fab568fe33c2f197cc1694f038023857ea32ea680066849c54edc2d825ce)
System: Safari 14.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/species/search
Window size: width 1635 - height 939
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-26T01:31:50.043Z',to:'2021-03-26T01:37:50.043Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-03-26T01:31:50.043Z',to:'2021-03-26T01:37:50.043Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
I think the reason why this is confusing is because the numbers here are for **names**, not just **species** (although the page is called "species").
<img width="357" alt="Screenshot 2021-04-14 at 15 35 19" src="https://user-images.githubusercontent.com/7677271/114719446-60ef7500-9d37-11eb-9b7e-975dcb9420df.png">

But if you click on [Animalia](https://www.gbif.org/species/1) and [Plantae](https://www.gbif.org/species/6), the number of SPECIES (in the upper right corner) are 1,737,334  and 534,305. Which adds up.

(Replied by email)
