### ISSUE TITLE
Link between Inat and GBIF broken

### ISSUE THREAD

**Issue by akristensen** [gbif/portal-feedback#3363]
Hi 
the picture is no longer linking between Inat (https://www.inaturalist.org/observations/63598934) and GBIF: 
https://www.gbif.org/occurrence/2963863953

**Comment by MattBlissett** [comment]
The iNaturalist user has changed the record license, so it is no longer eligible for iNat's export to GBIF.  

I don't know how often iNaturalist update their links to GBIF.

**Comment by ManonGros** [comment]
Yes the [photo](https://www.inaturalist.org/photos/102096927)'s license is: `Photo 102096927, (c) Su Snyder, some rights reserved (CC BY-NC-SA)` which we don't support.
Did you want to use the picture @akristensen ? We can contact the user on iNat to ask if they would like to change the license or let us use the picture.

**Comment by akristensen** [comment]
Hi Marie,

it is weird, it must have happened over night that Sue, changed / or inat changed the setting for this picture.

I used it for GB28<https://www.gbif.org/event/74SJpWSTMVxZaoPLKmtfez/gb28-28th-meeting-of-the-gbif-governing-board> and as I was checking if all was OK, it had all of a sudden changed. I am totally in love with the picture and use it as my back ground now….I have changed the ref to inat now (instructed by Daniel) so it isOK with comms. but yeah a shame I can no longer link to the gbif occurrence, so if not too much hassle it could be great, so we can link to the occurrence, maybe she doesn’t know how her records work together with GBIF.

***@***.***D7350D.B369C7A0]


But what I don’t really understand is that it still says featured on 1 site, is that then only the data and not the picture or is it just that it takes a while for inat to update this part, when a person changes their copyright info?

Annie

***@***.***D7350D.B3B37AD0]

**Comment by ManonGros** [comment]
@akristensen I wrote to Sue (just in case)
Yes this is odd, the link to GBIF from iNat is the link to the occurrence (which doesn't exist). Perhaps they didn't take into account these cases. It would be worth contacting them

**Comment by akristensen** [comment]
yes, but the point is, it did work and then either Sue or inat changes something, cause less than 24 hours after I had posted the picture, the link to gbif was broken. I thought I had made a mistake when entering the code in Contentful, but when I realized it wasn’t a typo I created the issue here.

Annie

**Comment by MattBlissett** [comment]
Hi,

The record was published to us under a CC-BY-NC license on 30 March, with the image also having a CC-BY-NC license.  We can continue to use record and media under those terms (it's legally completely fine), but it's also reasonable to respect the publisher's wishes and stop using it.

By the 6 April, the record's license had changed to one GBIF does not support (probably the current CC-BY-NC-SA license).

We can continue to use record and media under the original terms, but it's also reasonable for us to respect the publisher's wishes and stop using it, or use the new terms.  (And the new terms are fine for an image on the website. Strong Attribution is excluded from the occurrence index since it's not possible to attribute millions of different people on a download etc.)

It's pretty clear what happens when a particular license is chosen on iNaturalist:

![image](https://user-images.githubusercontent.com/583320/115219812-25bebe80-a108-11eb-97e2-77c993cb67d2.png)

I don't know how often iNaturalist update their "This observation is featured on" links, but I'm not surprised that it takes at least a few days.

**Comment by ManonGros** [comment]
I suppose we can close this issue now since we know why it happened.
