### ISSUE TITLE
How do I download custom metrics data?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3365]
**How do I download custom metrics data?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/377b2df9a8b39b840d3ac81286303032:37226dc5a561341efa92a6d06e531aaf7235f258995c67c03f7dc1241f4ebbd46e195e349df86b68a5d353e2dbf77827b93043f353b9aade51a50001e46860f1)
System: Chrome 89.0.4389 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/download?taxon_key=2607519
Window size: width 1260 - height 667
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-12T22:45:07.598Z',to:'2021-04-12T22:51:07.598Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-04-12T22:45:07.598Z',to:'2021-04-12T22:51:07.598Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
The short answer is: you cannot download a chart. You have to download the data behind it to get the citation DOI and then you can do charts based on that data subset.

----

The charts have an exploratory purpose. All metrics are driven of our public APIs documented here
https://www.gbif.org/developer/occurrence

All metrics are driven by facets. E.g.
http://api.gbif.org/v1/occurrence/search?taxonKey=5&country=DE&limit=0&facet=month&facetLimit=12&year=2018
will get you how many fungi `taxonKey=5` in Germany `country=DE` in year 2018 `year=2018` was collected per month `facet=month`.

```
"counts": [
{
"name": "10", // october
"count": 2007 // 2007 fungi recorded
},
{
"name": "9",
"count": 1651
},
...
]
```

But the best approach is probably to download the data you need for the charts - because that will get you the DOI you need to cite when using the data. That also gives you the freedom to generate the charts in a style consistent with your project along with the appropriate chart descriptions.

> user informed per email

**Comment by jlegind** [comment]
Question answered.
