### ISSUE TITLE
Backbone download and UI still not matching

### ISSUE THREAD

**Issue by Jegelewicz** [gbif/portal-feedback#3371]
See #3346 

"Opisodasys rubustus" is completely missing from the "New" backbone download and yet there is a page for it on the GBIF web front end listing it as "accepted". https://www.gbif.org/species/1416592

I am spending a lot of time trying to work through a vetted list of Siphonaptera and little things like this mean that my analysis will appear incorrect to anyone who can search species names on the GBIF site. I'd really like to know if the backbone download is different from that in use in the UI (or what the timing of refresh is). I fully expect that there will be changes over time, but we just downloaded yesterday. How often are updates made? Documentation seems to indicate they aren't made often, but our recent issues suggests it is happening daily or even more frequently.

**Comment by njdowdy** [comment]
I will add the following observations I made:

"Opisodasys rubustus" (taxonID: 8865978) was present in the backbone, accessed on March 24, 2021 (the version that had a last modified date of September, 2019). However, the "scientificNameAuthorship" in that dataset for that taxon seems to be incomplete ("Jordan", rather than "Jordan, 1925") in the most recently modified backbone, accessed on April 13, 2021 (with a last modified date of March 9, 2021).

There also appears to be many cases where names have been completely removed from the taxonomic backbone, in cases where the primary literature suggests they should have instead been retained and had their "taxonomicStatus" changed to 'synonym' (or some other non-accepted status) and had the accepted "taxonID" added to the "acceptedNameUsageID" field. This has resulted in many lost names from what I can tell. Perhaps more than 200 synonyms lost just within Siphonaptera. A few example lost synonyms include: Rhopalopsyllus sigmodoni, Typhlopsylla alpina, Leptopsylla hamifer longiloba, Citellophilus atallahi, Pulex keeni. 

In addition, there is also at least one case where the "taxonomicStatus" of a genus changed from 'accepted' to 'doubtful' and all the species that were once in that genus are completely absent from the newer backbone. Not listed as 'doubtful'. Not synonymized. Apparently deleted.

This strikes me as the wrong approach if true. These are names that are used in the primary literature, but now do not have a presence within the GBIF taxonomic backbone (but they once did!).

**Comment by thomasstjerne** [comment]
> "Opisodasys rubustus" is completely missing from the "New" backbone download and yet there is a page for it on the GBIF web front end listing it as "accepted". https://www.gbif.org/species/1416592

The species name is spelled _Opisodasys r**o**bustus_  not _Opisodasys r**u**bustus_ 
If you are you doing exact string matching when searching in the download, this could explain it?

It seems that the spelling variant https://www.gbif.org/species/127069483 has not been included in the backbone.

**Comment by njdowdy** [comment]
> > "Opisodasys rubustus" is completely missing from the "New" backbone download and yet there is a page for it on the GBIF web front end listing it as "accepted". https://www.gbif.org/species/1416592
> 
> The species name is spelled _Opisodasys r**o**bustus_ not _Opisodasys r**u**bustus_
> If you are you doing exact string matching when searching in the download, this could explain it?
> 
> It seems that the spelling variant https://www.gbif.org/species/127069483 has not been included in the backbone.

Yes, in that particular case that does appear to be the problem. However this is not the case for other examples. I will expand on this.

The taxon "Typhlopsylla alpina" (id: 8949835) is present in the previous version of the GBIF backbone as an accepted species, accessed on March 24, 2021 (the version that had a last modified date of September, 2019). It was listed there as "Typhlopsylla alpina Baker", missing the year of the citation. This name is absent from the recent backbone (accessed on April 13, 2021 (with a last modified date of March 9, 2021). This name is missing from the GBIF web portal search. 

Based on this document: [An Annotated  Catalog  of Primary  Types  of  Siphonaptera  in the National  Museum  of Natural  History, Smithsonian Institution](https://repository.si.edu/bitstream/handle/10088/5433/SCtZ-0560-Lo_res.pdf), on page 2, this taxon is listed (spelling matches), but as a synonym of "Stenistomera alpina (Baker, 1895e)", a taxon that is present in both the previous and current versions of the GBIF backbone (id: 1419263). 

What seems to be happening in some cases is that incomplete taxon records in the previous backbone were listed as 'accepted', but (at least some of them) were actually synonyms. Many (but not all) of these examples are incomplete with respect to the author citations that were assigned to them within the GBIF backbone. The problem seems to be that these names were destructively removed from the backbone, rather than resolved to their synonyms using the 'acceptedNameUsageID' field for example. In the case of "Typhlopsylla alpina" (id: 8949835), I believe it should be present in the GBIF backbone, but listed as a synonym of "Stenistomera alpina (Baker,  1895e)" (id: 1419263). As it stands, Typhlopsylla alpina doesn't exist as a name from GBIF's point of view, having been removed completely from the backbone in the newest version. 

"Hoplopsyllus tenuidigitus Stewart, 1940" (id: 8847953) is another example of a taxon that has gone missing. In the previous backbone, it was listed as a synonym and "originalNameUsageID" of "Euchoplopsyllus tenuidigitus (Stewart, 1940)" (id: 1419345). "Euchoplopsyllus tenuidigitus (Stewart, 1940)" is itself a synonym of "Euchoplopsyllus glacialis (Taschenberg, 1880)" (id: 1419340). All 3 names and their appropriate relationships were present in the previous backbone. However, in the newer version of the backbone, "Hoplopsyllus tenuidigitus Stewart, 1940" (id: 8847953) is completely absent and the 'originalNameUsageID' field of the taxon "Euchoplopsyllus tenuidigitus (Stewart, 1940)" (id: 1419345) has been overwritten to a value of 'null'. The name "Hoplopsyllus tenuidigitus Stewart, 1940" (id: 8847953) now no longer appears in searches through GBIF's web portal. 

There seems to have been a lot of synonyms that were deleted from the newest version of the GBIF backbone. This is a problem, because many of these names appear in the literature and will also likely appear within collections, but the ability to resolve them to the correct taxon seems to have unfortunately been compromised in the newest GBIF backbone.

**Comment by njdowdy** [comment]
There are 252 names within Siphonaptera alone which appear to be missing in the newest backbone. I can't speak for the reason behind each case, but I'm guessing many fall into some kind of synonym-linking problem as described above which somehow led to their deletion from the newest backbone.

**Comment by ManonGros** [comment]
This is probably more a question for @thomasstjerne and @mdoering but I don't think that this is due to some kind of synonym-linking problem.
As far as I can see, all the examples of missing species came from the [GBIF Type Specimen Names](https://www.gbif.org/dataset/6cfd67d6-4f9b-400b-8549-1933ac27936f) checklist. We decided to remove this checklist from the latest version of the backbone because it seemed to generate more issues than it helped.
More information on the backbone changes here: https://github.com/gbif/checklistbank/blob/master/docs/backbone-builds/2021-03-03.md

**Comment by ManonGros** [comment]
We would need a new checklist or update the existing ones to fill the gaps left by the GBIF Type Specimen Names checklist.
It looks like most of the Siphonaptera data in the current backbone comes from the [Parhost World Database of Fleas](https://www.gbif.org/dataset/c7536fe1-0d0b-4e68-9c93-1963ffe2241c).
We can forward them your suggestions @njdowdy

**Comment by mdoering** [comment]
just a quick note, the _metadata last modified date_ is only about the metadata and pretty much unrelated to data content. 
The date of publication for the data content is at the very bottom of the page and called _Publication date_ March 3, 2021 in the case of the latest backbone, some date in 2019 for the previous one:
https://www.gbif.org/dataset/d7dddbf4-2cf0-4f39-9b2a-bb099caae36c

I have filed an [issue to display the data publication date of the data at the top](https://github.com/gbif/portal-feedback/issues/3393), please add a comment there if you feel the same.

**Comment by mdoering** [comment]
@ManonGros is correct with the removal of the GBIF Type Specimen Names checklist and it's consequences.

Any recommendations on taxonomic sources that cover Siphonaptera better are highly welcome, ideally even directly for the [Catalogue of Life](https://www.catalogueoflife.org/data/taxon/43J) which uses [Parhost World Database of Fleas](https://www.catalogueoflife.org/data/dataset/1022). @yroskov for your attention.

**Comment by Jegelewicz** [comment]
Parhost was apparently last updated in 2005 and apparently is no longer being maintained. We are working to create an updated list for Siphonaptera. Once we have it published, how would we go about requesting that it be used by Catalogue of Life?

**Comment by njdowdy** [comment]
@ManonGros @mdoering, I see from the link on the decision to remove the GBIF Type Specimen Names:

> We also decided to remove the GBIF Type Specimen Names dataset from the Backbone sources. It is a derived dataset from all GBIF occurrences that represent type specimens. But even though it goes through some cleaning it has been the number one source for reported problem in the backbone, often due to mispellings. There is no source in the backbone now that draws names from occurrences.

Unfortunately, this was not a one size fits all solution, and has resulted in the loss of many taxa and synonymic links between names, at least within Siphonaptera. Maybe most problematic is that, because the lost names came from the type specimen list, these are some of the oldest names modern taxa were once known by. There will surely be many specimens in collections still curated under those names due to lack of curatorial activity since their initial description. Those specimens will now be more difficult to link up to their modern concepts (via GBIF, anyway). 

We (me, @Jegelewicz, @vijaybarve) are working on the taxonomy of arthropods that include terrestrial parasites and will try to push these corrections to places that will filter down into GBIF. I am concerned about the groups that we aren't looking at though. As @Jegelewicz said,

> Once we have it published, how would we go about requesting that it be used by Catalogue of Life?

Do you have any suggestions on how we can ensure these corrections make their way back to GBIF?

**Comment by yroskov** [comment]
Request for a new version of Parhost World Database of Fleas for CoL was sent to Sergey Medvedev.

**Comment by Jegelewicz** [comment]
> Request for a new version of Parhost World Database of Fleas for CoL was sent to Sergey Medvedev.

This may or may not work. If it does and there is a real update, that is fantastic. If not, what then?

**Comment by ManonGros** [comment]
> If not, what then?

Perhaps your checklist could still be integrated to the GBIF backbone? It should be possible if the data is published as a checklist on GBIF.
(Let's see what the Parhost World Database of Fleas answers.)

The types specimens are still available on GBIF ([here](https://www.gbif.org/occurrence/search?taxon_key=1366&type_status=TYPE_SPECIES&type_status=TYPE_GENUS&type_status=ALLOLECTOTYPE&type_status=ALLONEOTYPE&type_status=ALLOTYPE&type_status=COTYPE&type_status=EPITYPE&type_status=EXEPITYPE&type_status=EXHOLOTYPE&type_status=EXISOTYPE&type_status=EXLECTOTYPE&type_status=EXNEOTYPE&type_status=EXPARATYPE&type_status=EXSYNTYPE&type_status=EXTYPE&type_status=HAPANTOTYPE&type_status=HOLOTYPE&type_status=ICONOTYPE&type_status=ISOLECTOTYPE&type_status=ISOPARATYPE&type_status=ISONEOTYPE&type_status=ISOSYNTYPE&type_status=ISOTYPE&type_status=LECTOTYPE&type_status=NEOTYPE&type_status=PARALECTOTYPE&type_status=PARANEOTYPE&type_status=PLASTOHOLOTYPE&type_status=PLASTOISOTYPE&type_status=PLASTOLECTOTYPE&type_status=PLASTONEOTYPE&type_status=PLASTOPARATYPE&type_status=PLASTOSYNTYPE&type_status=PLASTOTYPE&type_status=SECONDARYTYPE&type_status=SUPPLEMENTARYTYPE&type_status=SYNTYPE&type_status=TOPOTYPE&type_status=ORIGINALMATERIAL&type_status=PARATYPE&type_status=TYPE&occurrence_status=present) is the link to all the types of Siphonaptera in GBIF). But they probably shouldn't be integrated to the backbone without any review. Feel free to use these data to help you work on your taxonomic checklist.

**Comment by ManonGros** [comment]
It seems that this issue could be closed. Please let me know if not, thanks!
