### ISSUE TITLE
filter species by extinction status

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3432]
**filter by species by extinction status**

Would it be possible to include a filter in the UI for the isExtinct boolean?

-----

Github user: @dnoesgaard
User: [See in registry](https://www.gbif.org/api/feedback/user/ac7d470e9ac850f0d7c6decef43cc8dc:872d9e081beba04961b2a363f2abd8995f5bd7b12f057bef7b52830cfdde744f0eff5995ca57d2d709f56ebb2e65f79c6df79e7a46b19e8a4ec58d4cf8c2251e)
System: Chrome 90.0.4430 / Mac OS X 10.15.7
Referer: https://www.gbif.org/species/search?rank=SPECIES&highertaxon_key=2687913&status=ACCEPTED&isExtinct=true
Window size: width 1651 - height 1221
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-05-26T12:51:00.835Z',to:'2021-05-26T12:57:00.835Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-05-26T12:51:00.835Z',to:'2021-05-26T12:57:00.835Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
Yes, but we should perhaps evaluate if we think that our data quality supports it. If I remember correctly, then some of those filters were left out because the results were odd. As in: showing as extinct, because it was extinct in that area of a french forrest. I do not have a specific example, just a vague recollection that we left it out on purpose. But the data etc could since have changed. Perhaps you could help evaluate the results? 

@mdoering what is your feeling, do you remember why we do not expose it? Was it part of the previous Drupal/Struts website? We generally ported everything unless we had specific reasons to change it.

**Comment by mdoering** [comment]
It is one of the best managed species properties, but still there is no complete coverage and some datasets might be really wrong. But without exposure obviously there is also no push for quality.

We do expose `extinct` as the only species property in the COL API and UI. I agree it is probably worth doing it for GBIF also.

**Comment by MortenHofft** [comment]
searching the backbone for extinct taxa
http://api.gbif.org/v1/species/search?isExtinct=true&datasetKey=d7dddbf4-2cf0-4f39-9b2a-bb099caae36c

first results are
[Prasinophyta](https://www.gbif.org/species/104) 1,214 observations since 2019 - no fossils
[Cephalaspidomorphi](https://www.gbif.org/species/239) 4,722 observations since 2019 - no fossils
[Bryopsida](https://www.gbif.org/species/327) 301,932 observations since 2019 - no fossils

It looks to me like the filter at least deserves an explanation if we are to add it. I get that data quality typically improves with exposure, but it can also make us look silly. From briefly looking at above my feeling is that this belongs to the second category.

I've added it in [a branch](https://github.com/gbif/portal16/tree/extinct) and put it on [staging environment](https://www.gbif-staging.org/species/search)

**Comment by dnoesgaard** [comment]
That seems really odd. I can't see that any of these taxa have an extinction flag in the source checklists.

**Comment by MortenHofft** [comment]
Might be that I'm doing something wrong. But I think we should evaluate data quality first - we might be able to write a disclaimer/explainer that makes it fine. But it would be nice to know a bit more first I find. Do you have time to evaluate the data quality @dnoesgaard ?

**Comment by mdoering** [comment]
This seems indeed really bad. There probably have been good reasons to exclude it.
I could change the nub build in the future to only copy extinct from some trusted source like COL. Or we could even consider to only ever apply it to genera and below.

A useful filter, but we might indeed need to improve data quality.

**Comment by dnoesgaard** [comment]
Just from looking at the first 3 examples, I don't think we should expose it at the moment.

Why would this taxon be listed as extinct?

```
"key": 327,
"datasetKey": "d7dddbf4-2cf0-4f39-9b2a-bb099caae36c",
"constituentKey": "7ddf754f-d193-4cc9-b351-99906754a03b",
"nubKey": 327,
"parentKey": 35,
"parent": "Bryophyta",
"kingdom": "Plantae",
"phylum": "Bryophyta",
"kingdomKey": 6,
"phylumKey": 35,
"classKey": 327,
"scientificName": "Bryopsida",
"canonicalName": "Bryopsida",
"authorship": "",
"nameType": "SCIENTIFIC",
"taxonomicStatus": "ACCEPTED",
"rank": "CLASS",
"origin": "SOURCE",
"numDescendants": 30470,
"numOccurrences": 0,
"extinct": true
...
```

**Comment by Andreas-Bio** [comment]
possibly related to  #https://github.com/CatalogueOfLife/backend/issues/837
