### ISSUE TITLE
the is a collection from a zoo, not sure how to flag that

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3457]
**the is a collection from a zoo, not sure how to flag that**

-----

Github user: @wcornwell
User: [See in registry](https://www.gbif.org/api/feedback/user/3e57fa428968d0b01deb4f86e8dc1028:9ea9017529b5a75abf27bdb8a55789ce0adeb7703322d892e9184faea70b7e4727a2cf25e9086dfc928b044875c5a5220604754b3cb6d53b4dde8df6718f6bea)
System: Chrome 91.0.4472 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/476844837
Window size: width 1596 - height 930
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-10T05:13:34.550Z',to:'2021-06-10T05:19:34.550Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-06-10T05:13:34.550Z',to:'2021-06-10T05:19:34.550Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING
datasetKey: 4bfac3ea-8763-4f4b-a71a-76a6f5f243d3
publishingOrgKey: b4640710-8e03-11d8-b956-b8a03c50a862

**Comment by jhnwllr** [comment]
There is **not any good way to flag collections as coming from a zoo currently**. 

I have seen some publishers fill in the **establishmentMeans** column as “MANAGED”.  

This seems to be the best solution so far, but it is not widely used. 

There is also basisOfRecord = LIVING_SPECIMEN but since this specimen was/is not really "living", I can see why there would be some reluctance to use that as well. https://data-blog.gbif.org/post/living-specimen-to-preserved-specimen-understanding-basis-of-record/

Most users wanting to filter zoo records have to rely on imperfect solutions such as the R function CoordinateCleaner::cc_inst(). This will not remove all of the zoo and botanical garden records, but it will get very close.
