### ISSUE TITLE
hello, how can we download all the images of the otolith in the Mediterranean sea?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3513]
**hello, how can we download all the images of the otolith in the Mediterranean sea?**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/1928d7a91488cea4dbb918c66091510d:37a87e0e528c22fe115c823341815818bc94fb4b9ca483f47b3cab71a84d45558fd4f23f692ba1ee147322575648ba42907bd11739ba80e7984c7fbf46db688f)
System: Chrome 91.0.4472 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/1851772565
Window size: width 1366 - height 568
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-12T17:27:30.405Z',to:'2021-07-12T17:33:30.405Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-07-12T17:27:30.405Z',to:'2021-07-12T17:33:30.405Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: e95d0010-b3f1-11de-82f8-b8a03c50a862
publishingOrgKey: ad2c7028-26fd-49c6-88d2-457c207c387b

**Comment by ManonGros** [comment]
There is no easy way to download all the images of otolith in the Mediterranean sea. That being said, here is how to download as many as possible:
* The first step is to select a dataset containing otolith images and use the polygon map tool to select the area of interest: https://www.gbif.org/occurrence/map?dataset_key=e95d0010-b3f1-11de-82f8-b8a03c50a862&media_type=StillImage&geometry=POLYGON((-5.64697%2033.79395,18.52295%2028.47656,32.01416%2030.98145,33.33252%2030.71777,36.23291%2032.25586,36.3208%2037.5293,29.68506%2040.7373,16.58936%2047.41699,5.8667%2046.58203,-5.69092%2037.88086,-5.64697%2033.79395))
* Then, click on “DOWNLOAD” and select the “DARWIN CORE ARCHIVE” format,
* Once you download is ready, download and open the folder,
* The URL to the images are included file named “multimedia.txt”. You will have to use those URL to download the images.

There could be some missing images. The problem is that there is no way to specifically filter for otoliths, we have to rely on the names of datasets.
This should give you most of the relevant images though.

> Replied by email
