### ISSUE TITLE
This taxon (subgenus Vertebrata in Crustacea) does not exist...

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#360]
**This taxon (subgenus Vertebrata in Crustacea) does not exist...**

This name (Bodotria (Vertebrata) in order Cumacea) does not exist. It originates from an erroneous record in WoRMS, copied to IRMNG in 2013, latter deleted just now. Also note, 3,527 GBIF distribution records are erroneously associated with this name (!)... I copy below the messge I sent to WoRMS just now regarding this name. Regards - Tony Rees
---------
"Vertebrata" (subgenus in Crustacea in WoRMS) does not exist...
http://www.marinespecies.org/aphia.php?p=taxdetails&id=182675

present usages:

Bodotria (Vertebrata) 
AphiaID: 182675

Bodotria (Vertebrata) vertebrata Day, 1978 
AphiaID: 181649 

I believe the correct subgenus name for this taxon is Atlantobodotria Petrescu, 1998, however subgenera of Bodotria are not presently represented in WoRMS.

I think the error has entered WoRMS because there is a subspecies of Bodotria vertebrata, B. vertebrata vertebrata Day, 1978, in some systems, and this name has been incorrectly parsed with the specific name interpreted as subgenus.

I will now delete the relevant record from IRMNG too. (copied from WoRMS in 2013).

-----
fbitem-species8028192
Reported by: Tony.Rees@marinespecies.org
System: Chrome 60.0.3112 / Windows 8.1 0.0.0
Referer: https://www.gbif.org/species/8028192
Window size: width 1366 - height 638
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-18T21:55:57.087Z',mode:absolute,to:'2017-08-18T22:01:57.087Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-08-18T21:55:57.087Z',mode:absolute,to:'2017-08-18T22:01:57.087Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by mdoering** [comment]
Thanks Tony. The GBIF Backbone relies on the IRMNG record here:
https://www.gbif.org/species/107623578/verbatim

which is based on the registered Darwin Core Archive of IRMNG:
http://www.cmar.csiro.au/datacentre/downloads/IRMNG_DWC.zip

Is this still the latest URL or should we use sth from irmng.org instead?

**Comment by TonyRees** [comment]
Hi Markus, the CSIRO archive for IRMNG is effectively frozen as at 2014 and will not be updated further. The new location for archived and newer releases from 2016 onwards is at  http://www.irmng.org/export/ with the latest release having the permanent URL http://www.irmng.org/export/IRMNG_genera_DwCA.zip , so you should change to this for the future.

Currently the most recent release is from April 2017 but it will still contain the spurious "Vertebrata" record since that correction to the live version of IRMNG was only made this month (and will therefore not appear until the next release), so maybe it would be preferable to wait for that - although if you utilise the April 2017 release you will get a swag of additional names (around 10,000 genera) plus various other improvements as described in that version's release notes as shown at http://www.irmng.org/download.php .

FYI the new IRMNG release/s comprise genera and higher taxa only since species names from CoL and some other sources are somewhat outdated in IRMNG and may also not be releasable as CC0. I believe the fuller version including species can be requested from the new IRMNG custodians info@irmng.org if you think that would be of value to GBIF (for example it does include quite a lot of species names compiled from sources other than CoL if you still need these). Let me know if this helps - Best - Tony

**Comment by mdoering** [comment]
Thanks Tony. I have updated https://www.gbif.org/dataset/0938172b-2086-439c-a1dd-c21cb0109ed5 to use the latest genus only export. I don't think we need the species even though about 400.000 of them are used in our backbone currently: https://www.gbif.org/species/search?rank=SPECIES&constituent_key=0938172b-2086-439c-a1dd-c21cb0109ed5&advanced=1

Some of these seem to be spelling alternatives, like Axinyssa flaveolivescens for Axinyssa flavolivescens which we get through WoRMS already

**Comment by mdoering** [comment]
There is a hidden null control char (U+0000) in this line of the current IRMNG dwca dump that leads to trouble:
`1144985 urn:lsid:irmng.org:taxname:1144985 1144985 100871 Paratiberioides Paratiberioides Passalidae Elytra 22 (2), Nov 15 Animalia Arthropoda Insecta Coleoptera Passalidae Paratiberioides Genus Iwase, 1994 ICZN accepted 2012-01-01 IRMNG (2012). Paratiberioides Iwase?, 1994. Accessed through: The Interim Register of Marine and Nonmarine Genera at http://www.irmng.org/aphia.php?p=taxdetails&id=1144985 http://www.irmng.org/aphia.php?p=taxdetails&id=1144985`

@TonyRees  maybe this can be removed? I am fixing GBIF code to deal with this gracefully

**Comment by TonyRees** [comment]
Hi Markus,

Yes, I can see it displayed as a bad character in the web version of the
current IRMNG at VLIZ (at the end of the author name) but not in my old
CSIRO copy (or at least does not display as such and cannot see it via my
data dump). Maybe it crept in during the transfer process to VLIZ, I don't
know; at any rate I have removed it from the current master copy although
it will be fixed until the next DwCA export file is generated (also copying
to VLIZ Data Management Team for their information).

Is it possible for you to tell me whether or not this is the sole instance
in the file or whether there are more to fix, since that is a test I cannot
easily do?

Cheers - Tony

**Comment by mdoering** [comment]
Thanks Tony. As far as I can tell this was the only instance in the taxon file so you should be fine!

**Comment by mdoering** [comment]
The genus is still in the GBIF IRMNG copy: https://www.gbif-uat.org/species/107623578

**Comment by TonyRees** [comment]
Hi Markus,

The name concerned was deleted around the time of my email in August 2017,
so will be absent in the latest (December 2017) release, available from
http://www.irmng.org/export/ . However the pre-formatted releases from 2016
onwards contain genera only, no species, since the latter are getting
somewhat out-of date although could still be useful with some caveats (e.g.
CoL-derived content not updated since 2006). You can request a dump with
species from the custodians, though (I am told...)

Hope this helps - Tony


Here is the present IRMNG edit history:

*Vertebrata *

[deleted]
IRMNG_ID

1468858  (urn:lsid:irmng.org:taxname:1468858)
Classification

   1. Biota
   2. Animalia <http://www.irmng.org/aphia.php?p=taxdetails&id=2> (Kingdom)
   3. Arthropoda <http://www.irmng.org/aphia.php?p=taxdetails&id=235>
    (Phylum)
   4. Crustacea <http://www.irmng.org/aphia.php?p=taxdetails&id=11905093>
    (Subphylum)
   5. Malacostraca <http://www.irmng.org/aphia.php?p=taxdetails&id=1190>
    (Class)
   6. Cumacea <http://www.irmng.org/aphia.php?p=taxdetails&id=10295> (Order)

   7. Bodotriidae <http://www.irmng.org/aphia.php?p=taxdetails&id=108875>
    (Family)
   8. *Vertebrata* <http://www.irmng.org/aphia.php?p=taxdetails&id=1468858>
    (Genus)

Status
[image: Unaccepted: synonym, or anything that is not accepted]
unaccepted (Taxon
does not exist (error in source DB - WoRMS, 2013 version)

Taxonomic citation
IRMNG (2013). *Vertebrata*. Accessed through: The Interim Register of
Marine and Nonmarine Genera at
http://irmng.org/aphia.php?p=taxdetails&id=1468858 on 2018-01-30

Taxonomic edit history
*Date*
*action                *by
2013-06-03 22:00:00Z
created               Rees, Tony
<http://www.vliz.be/en/imis?module=person&persid=5043>
2017-08-18 21:50:49Z
deleted               Rees, Tony
<http://www.vliz.be/en/imis?module=person&persid=5043>






Tony Rees, New South Wales, Australia
https://about.me/TonyRees

**Comment by mdoering** [comment]
Thanks Tony. Sth weird must be going on with GBIF indexing then, I checked the archive and its from 1st December and does not contain the genus anymore.

But our indexing claims to have last indexed data on 17th December and since then nothing has changed - which is correct. But it still preserved the Vertebrata record. Needs investigation

**Comment by TonyRees** [comment]
OK - you might want to check the years i.e. it is 17 Dec 2017 not 17 Dec
2016...

Otherwise I have sometimes wondered what happens downstream when a
record/ID is deleted in IRMNG or other data source - considering that the
DwCA file does not explicitly say "record x has been deleted", a user has
to detect this via comparison with previously ingested data. Of course if
the old data are simply purged this is not a problem.

Cheers - Tony

Tony Rees, New South Wales, Australia
https://about.me/TonyRees

**Comment by mdoering** [comment]
Error was on our side. Gone for good now, thanks!
https://www.gbif.org/species/search?q=Vertebrata&dataset_key=0938172b-2086-439c-a1dd-c21cb0109ed5&origin=SOURCE&advanced=1

**Comment by TonyRees** [comment]
Thanks, Markus,

The "real" animal taxon Vertebrata was introduced in IRMNG - with selected
other suphyla - for the first time in April 2017. GBIF now has it as
https://www.gbif.org/species/132930283 , however currently the record
"could not be matched to GBIF backbone". Is this an error or does the GBIF
backbone not include subphyla? I imagine that this is where the original
c.900 records previously assigned in error to the spurious animal
(Crustacean) genus "Vertebrata" should now be reassigned...

- Tony

Tony Rees, New South Wales, Australia
https://about.me/TonyRees
