### ISSUE TITLE
i cant download data

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3604]
**i cant download data**

i need to download various species and i can´t because always display "Download is only supported for structured search - no for free text queries"

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/3ede211df4f176029cc29cc04cd52c17:1fd2d843767f36117aa208f45b716d9007bcdbb67f0dafbb59ab661ad295c1c35f4fc7c885f35b7c7625bbdb439b98ab3fa617cc0dba7d76f212eef5a9423afe)
System: Chrome 93.0.4577 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download?q=mazama%20sanctaemartae&country=CO&has_coordinate=true&has_geospatial_issue=false&occurrence_status=present
Window size: width 1366 - height 657
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-21T21:15:51.008Z',to:'2021-09-21T21:21:51.008Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-21T21:15:51.008Z',to:'2021-09-21T21:21:51.008Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The message you get on our web interface means that you will need to use one of our filters instead of the free-text search box in the upper right corner.

In general, I suggest to use the “Scientific name” filter to look for species names. This filter is tied to our backbone taxonomy.
However, it seems that our backbone taxonomy doesn’t include the name Mazama sanctaemartae. In cases where using the “scientific name” filter doesn’t give you any result, you can use the “Verbatim scientific name” to query the scientific names share by data providers before they are interpreted by GBIF. Here is a downloadable selection for Mazama sanctaemartae: https://www.gbif.org/occurrence/search?country=CO&has_coordinate=true&has_geospatial_issue=false&issue=TAXON_MATCH_HIGHERRANK&advanced=1&verbatim_scientific_name=Mazama%20sanctaemartae&occurrence_status=present

> Replied by email
