### ISSUE TITLE
Looking for numbers on surveys

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3605]
**Looking for numbers on surveys**

I am trying to discover how many survey datasets GBIF has for different taxonomic groups. I have searched Datasets for numbers and country, but would like to add another search term - taxon (e.g, Tracheophyta).  Is there a way to do this?

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/e3156c6ef7a9c4ebc5298242e3d4e534:6557fe655ad281bea6e211d6b1ac3135c0311ed4a29077dc51b93569c4efc675f3ce8de0e1f08031411c56eb8cb2144cdefb49448dcf9574ed2c94d77c87c563)
System: Chrome 93.0.4577 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/search?q=surveys&publishing_country=US
Window size: width 1097 - height 554
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-22T10:45:40.030Z',to:'2021-09-22T10:51:40.030Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-09-22T10:45:40.030Z',to:'2021-09-22T10:51:40.030Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Replied by email

There is no easy way to do that. What you tried by looking at the dataset search interface is one way to proceed but as you noted, there is no way to look for taxa with that system.

Another way would be to use the occurrence search. You can use the keyword “survey” in the free text field. This type of search will look for the word “survey” in the occurrence records, not just the dataset title. It might give you records from datasets that aren’t necessarily survey datasets. For example, this record from the Paris Herbarium: https://www.gbif.org/occurrence/438913165 (the verbatim locality is “Southern California on the Mexican Boundary **Survey**”).
That being said, the advantage is that you can filter the records per country and taxa (and other attributes). For example, here is a selection for all the tracheophyte occurrences, located in the US, and associated with the “survey” keywords: https://www.gbif.org/occurrence/search?q=survey&country=US&taxon_key=7707728
To see the datasets for this selection of records, you can go to the metrics tab and scroll to the bottom.
Given the search query, some manual checking for the dataset would be required. There is a bit less than 200 datasets contributing records in that selection but some of them are paleology datasets (probably selected because of the “geological survey” words), some of them seem to contain only a few records.

These a ways to explore the numbers yourself with our web interface.
But if you need a specific number for a specific country/taxon, you can also write us at helpdesk@gbif.org, we can help you with some custom queries on our side.
