### ISSUE TITLE
Names seem ok but are flagged as partially parsed

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3631]
**Names seem ok but are flagged as partially parsed**

157 names from the "National checklist of all species occurring in Denmark" are tagged with "Name partially parsed".

Using the name parse tool, most of these seem to be parsed with no problem, though.

For instance Trichocerca scipio (Gosse, 1886) and Trichocerca rousseleti (Voigt, 1902) seemingly both parse correctly, but whereas the latter matches GBIF, the former is tagged with "Name partially parsed" on the Danish checklist (https://www.gbif.org/species/168509416).

-----

Github user: @LarsSkipper
User: [See in registry](https://www.gbif.org/api/feedback/user/71e59ac8bd82e40377198dc815cea80c:ae62616651bd5500c165a351f2efe8049e7ba32c04a37d9f6b1ed83c16407c849463b81b31583c15a7356c2def9470c634c35842bb7cd0e97e6fe7f83de51e65)
System: Firefox 92.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/species/search?dataset_key=4b3e4a71-704a-485c-917c-20a89944ea37&origin=SOURCE&issue=PARTIALLY_PARSABLE&advanced=1
Window size: width 1680 - height 936
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-04T10:52:07.989Z',to:'2021-10-04T10:58:07.989Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-10-04T10:52:07.989Z',to:'2021-10-04T10:58:07.989Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by ManonGros** [comment]
Hi @LarsSkipper
This flag is used to signal when the name interpreted/parsed by GBIF is different than the original name provided. This can happen for a number of reasons. In the case of Trichocerca scipio (Gosse, 1886), the interpreted name is only `Trichocerca scipio` because the original name is missing a parenthesis:
<img width="1330" alt="Screenshot 2021-10-04 at 15 30 52" src="https://user-images.githubusercontent.com/7677271/135860454-93dd9019-b526-490f-8650-ca7e74aaf166.png">

The partially parsed names can often be matched correctly to the backbone taxonomy though. This is the case for this species.

In general, when a name is partially parsed, that means that the system couldn't recognise a specific pattern. For example, the name `Panoploea minuta Stebbing, 1906 Chev.& Fage, 1925` (https://www.gbif.org/species/168517526/verbatim).

If you notice some names that are valid but somehow not parsable, please report them. It will help improve our parser.

**Comment by ManonGros** [comment]
@LarsSkipper I am closing this issue now, let me know if we should keep it open or if you have any question.
