### ISSUE TITLE
how do you define an area of interest

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3793]
**how do you define an area of interest**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/b82a5ae6160de5dc55933a7595ed7349:c86bdba18228cb48ea8cdea5057d5f8a083304bd0f7cde40853ec2e140fa4a310f263ad0e301d8d4e5403d36e75d1a94e79ef8107b058d818d2f609f7e96b4c7)
System: Firefox 94.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/search?advanced=1
Window size: width 1680 - height 897
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-03T23:52:00.764Z',to:'2021-12-03T23:58:00.764Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-03T23:52:00.764Z',to:'2021-12-03T23:58:00.764Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Replied by email

If the area you are interested in has administrative boundaries (for example, data with records located in the Yunnan Province in China), you can use the Administrative areas (gadm.org) filters. See this example: https://www.gbif.org/occurrence/search?advanced=1&gadm_gid=CHN.30_1

If you would like to define the area yourself, you can either draw a polygon on the map by clicking on the MAP tab and selecting the polygon tool in the upper right corner of the map. See this example: https://www.gbif.org/occurrence/map?advanced=1&geometry=POLYGON((-72.59766%200.17578,-62.05078%200.17578,-66.62109%209.31641,-72.59766%200.17578))
You can also paste a polygon the Location filter (see screenshot below) and click on add. Note that for very complex polygons, we recommend using [our download API](https://www.gbif.org/developer/occurrence#download) instead of the web interface (we have [an API tutorial for R users](https://data-blog.gbif.org/post/gbif-api-beginners-guide/) if you are interested).

<img width="484" alt="paste_polygon" src="https://user-images.githubusercontent.com/7677271/144821321-247b0425-aa50-4827-997e-314fbf8e88ca.png">
