### ISSUE TITLE
API returns CC-BY-SA results if only CC-BY is requested

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3831]
**API returns CC-BY-SA results if only CC-BY is requested**

I ran the following query "https://api.gbif.org/v1/occurrence/search?taxonKey=3064865&license=CC_BY_4.0&mediaType=StillImage" where I would like to obtain images from GBIF with a CC-BY license. However, the api also returns results with CC-BY-SA In the results.
Here is a snippet where that is the case:

key: 2644283396
license	"http://creativecommons.org/licenses/by/4.0/legalcode"
media [0] license "Dieter Albrecht (cc-by-sa)"

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/1dac9737f254a7e99bbadf5a07c21aeb:bf877b1669dc56aa4783067b40eb66988c30bf4c053f76cba978a0aa164592ecbc139bb7addbecb05c454ff6e104eb6f5083c76a5afe406a45091b52125bf1dc)
System: Firefox 89.0.0 / Ubuntu 0.0.0
Referer: https://www.gbif.org/
Window size: width 1280 - height 577
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-20T17:41:34.842Z',to:'2021-12-20T17:47:34.842Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2021-12-20T17:41:34.842Z',to:'2021-12-20T17:47:34.842Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
As far as I know, there is no filter for media licenses. This query is returning records based on the record license, not the image license. The image license is independent from the record one.

Can someone confirm that there isn't any way to search record based on the license associated with images? @MattBlissett ?

**Comment by muttcg** [comment]
@ManonGros That is correct, currently we don't support media licenses filter, license filter applies only to records

**Comment by andrawaag** [comment]
@ManonGros @muttcg I understand the distinction, but in this specific case, the API call is misleading since it take  both a media type and a license, which suggests the license applies to the media type and not the record.

**Comment by MortenHofft** [comment]
I do not personally feel this is misleading. It is a search for records that 

* have images attached
* is of a specific taxon
* the record has a license of CC BY

a license filter do not change meaning (to apply to the images) just because a mediaType filter is also applied. Just as a country filter do not change meaning if you add a publisher filter (to apply to the publishing country).

The confusing part is in my opinion that the licenses can be different. But it is how the data is (and as such it makes sense).
The API documentation could also be more clear on what the license field applies to. Currently it just says "the record". I would be useful to make this more clear in the documentation.

I would be happy to update the documentation. Does anyone have a text suggestion to make this more clear?

Notice that in the UI it is highlighted that filtering on a specific license do not reflect the image license
https://www.gbif.org/occurrence/gallery?license=CC_BY_4_0&occurrence_status=present

**Comment by MortenHofft** [comment]
We could add mediaLicense as a filter parameter, but doing so we lead to odd results as we do not support queries on objects in arrays - as in filter on records that have media=images and THOSE have a mediaLicense=CC-BY. So we would include results like 
```
media: [
{type: IMAGE, license: CC-NC},
{type: VIDEO, license: CC-BY}
]
```

At least that is the "faulty" behaviour we would see if we just used added the filter as any other. As far as I understand. We could add "imageLicense, videoLicense, audioLicense" of course, but that does not feel elegant IMO.

**Comment by andrawaag** [comment]
I would not have an issue with those three filters. An alternative is to not filter for license at first and then parse the results for a specific license. This however can be demanding on the server-side, since more (paginated) results are returned.

An alternative would be to render GBIF data also as RDF on the semantic web and feed that to tools through SPARQL.
