### ISSUE TITLE
Access restriction of the (pipeline version) data validator

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3844]
**Access restriction of the (pipeline version) data validator**

Current ownership of the validation report prevents sharing.

-----

User: [See in registry](https://www.gbif-uat.org/api/feedback/user/0d7624a04deb48ebcf37feb1cefc833f:044679b1be52d790d373d71552334235b4dacb99d824f3c31d3daf8dc88f0947267afaa4a47456078679e21441bbe5901af96782fcead2f2676fdb1212ce4031)
System: Firefox 95.0.0 / Mac OS X 10.15.0
Referer: https://www.gbif-uat.org/
Window size: width 1504 - height 1582
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-04T03:07:28.618Z',to:'2022-01-04T03:13:28.618Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-01-04T03:07:28.618Z',to:'2022-01-04T03:13:28.618Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ckotwn** [comment]
@muttcg following https://github.com/gbif/portal-feedback/issues/3841#issuecomment-1003996401 I am submitting a new issue for this separate matter.

To make the case stronger:
1. When helping a data publisher solve their data issues, having the validation public is as efficient as it is now on the production site. Any restriction applied without good reason will hurt the efficiency and helpdesk experience.
2. Since GBIF data is public with CC, we want the data quality being open for scrutiny as well.
3. Having the validation report openly accessible actually saves the need to re-run just for the sake of seeing the same result. This reduces energy footprint.

[ ] Another issue is,  it's easy to confuse the UUID of the validation result with other GBIF.org object.
Considering we've already familiar with /dataset/{UUID}, /node/{UUID}, /installation/{UUID}, /organization/{UUID}, I once assume that https://www.gbif-uat.org/tools/data-validator/5f5fc986-e610-458e-9fd9-04874500186e means the validation result of dataset/5f5fc986-e610-458e-9fd9-04874500186e, but it's not (though this can be [a new feature](https://github.com/gbif/portal-feedback/issues/3845)). Not sure why the new validator generate UUID just for the report. The existing numbering already has low collision rate.

Thank you so much for considering.

**Comment by MattBlissett** [comment]
This was implemented.
