### ISSUE TITLE
Anthomyia (Meigen 1803) genera should be in Anthomyiidae, not Tabanidae

### ISSUE THREAD

**Issue by Rmturner24** [gbif/portal-feedback#3905]
Anthomyia (Meigen 1803) genera (https://www.gbif.org/species/1480567) should be in Anthomyiidae, not Tabanidae. GRISALES, D., LOPES, A. C., & DE CARVALHO, C. J. B. (2016). FAMILY ANTHOMYIIDAE. Zootaxa, 4122(1), 803–806. https://doi.org/10.11646/zootaxa.4122.1.68

**Comment by ManonGros** [comment]
It looks like the issue comes from Systema Dipterum via the Catalogue of Life, I see two entries for the genus Anthomyia:
* https://www.catalogueoflife.org/data/taxon/8RZ2S in the [Tabanidae](https://www.catalogueoflife.org/data/taxon/GVW) family (one species associated with this entry)
* https://www.catalogueoflife.org/data/taxon/8ST8Y in the [Anthomyiidae](https://www.catalogueoflife.org/data/taxon/6H7) family (121 species associated with this entry.

**Comment by ManonGros** [comment]
Solved in the new backbone taxonomy.
