### ISSUE TITLE
Dead dataset link

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#3921]
**Dead dataset link**

Annie and I are doing the revision of the Biota dataset and data papers this link https://www.gbif.org/dataset/edd76a7a-64e0-4008-a741-105ecd67e339 is the second dataset in the paper https://bdj.pensoft.net/article/59176/, but apprears to be dead. Is there anything we could do to revive?

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/c3e18dd757031ff34989030126173a38:6637164e5076a8574bc87e6fc05e5e2594c0137bfb5260563b30ef7618e94f912ede8cb6296dfb3964753057590f48230a66c6fe88f73446773a16a4b646e10e)
System: Chrome 98.0.4758 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/edd76a7a-64e0-4008-a741-105ecd67e339%C2%A0
Window size: width 1862 - height 926
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-09T16:30:51.537Z',to:'2022-02-09T16:36:51.537Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-02-09T16:30:51.537Z',to:'2022-02-09T16:36:51.537Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
The dataset link works fine. But you also have a second link where you (or probably someone else) have added additional characters to the dataset UUID
```
https://www.gbif.org/dataset/edd76a7a-64e0-4008-a741-105ecd67e339
https://www.gbif.org/dataset/edd76a7a-64e0-4008-a741-105ecd67e339%C2%A0
```

UPDATE:
most of the links on the paper is correct. But (at least) one of them is pointing to the wrong url.
`[https://www.gbif.org/dataset/edd76a7a-64e0-4008-a741-105ecd67e339](https://www.gbif.org/dataset/edd76a7a-64e0-4008-a741-105ecd67e339%C2%A0)` read this as: they write the correct text, but the link is actually wrong.

This should be fixed in the paper

**Comment by MortenHofft** [comment]
GBIF.org shows a 404 (because the link is dead - invalid uuid), but suggests the dataset as a possible match for what you are looking for. That is about all we can do in our end, but it is a good idea to get it fixed in the paper
<img width="763" alt="Screenshot 2022-02-10 at 14 23 28" src="https://user-images.githubusercontent.com/6759267/153417087-36a08034-5fcd-4847-8f5d-be8d9867dd49.png">
