### ISSUE TITLE
Safe to delete the dataset from IPT if it is marked as deleted on GBIF.org?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4001]
**Safe to delete the dataset from IPT if it is marked as deleted on GBIF.org?**

As title, and, when deleting, should the data manager use `Delete from the IPT and GBIF.org` or `Delete from the IPT only (orphan)`?

-----

Github user: @ckotwn
User: [See in registry](https://www.gbif.org/api/feedback/user/8585eb516e088cd0b21186b5be590caf:01a7302e2d9d897b7f6776d2a6783d73c7dac442fffa8444cbf710aa449e26968f5f17aa260aa82751319681455fe2deecd1642bea9bc854abbe8aa6929469a0)
System: Firefox 98.0.0 / Mac OS X 10.15.0
Referer: https://www.gbif.org/dataset/cb07c8c8-cb48-489c-9a63-2a64fd7f7b27
Window size: width 1504 - height 1582
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-30T03:48:09.617Z',to:'2022-03-30T03:54:09.617Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-03-30T03:48:09.617Z',to:'2022-03-30T03:54:09.617Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
Hi @ckotwn if the dataset is already deleted on GBIF.org, I would recommend to use `Delete from the IPT only (orphan)`. This will avoid any registry issue.

**Comment by abubelinha** [comment]
I would like to understand under which circumstances could this happen.
In both deleting options, dataset would be deleted from IPT. 
So how could a dataset be "deleted" in GBIF portal, but still showing in IPT?
1. Perhaps when the IPT is a new installation which restored an old copy of that dataset?
2. Or maybe it was deleted from helpdesk staff on request by IPT manager?

@ManonGros what's the best way proceed when you want to do that 2nd thing? (#4403)

Thanks
@abubelinha

**Comment by ManonGros** [comment]
The GBIF registry (and registry API) allow people with the proper permissions to delete datasets. Alternatively, the dataset might have been deleted from a previous IPT before it was migrated to a different one.

This particular option was introduced for cases where a dataset was migrated from one IPT to another one. The problem was that in the past, once the dataset was migrated, if a publisher wanted to delete the dataset in the old IPT,[ they would have to use a work around](https://github.com/gbif/ipt/issues/1461) otherwise the dataset would also be deleted on GBIF.
So in order to avoid accidental deletions from GBIF, the option was added to delete the dataset from the IPT only.

Now there can be several reasons why a dataset would be deleted from GBIF but not from an IPT. For example, if there is reason to remove the data urgently (accidental duplication, sensitive data, etc.) or temporarily (the dataset can be restored later one).
