### ISSUE TITLE
Data in download is very different from what was published

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4083]
**Data in download is very different from what was published**

* The value in verbatimScientificName is the same as in the interpreted scientific name. We are not actually keeping the original name. For example, for this record https://www.gbif.org/occurrence/3437209314, the verbatimScientificName should be Nephrosperma vanhoutteana Balf.f. but in the download it is Nephrosperma van-houtteanum (H.Wendl. ex Van Houtte) Balf.f..
* The coordinates are very rounded in the download. We lose about 3 digits.
* The elevation and coordinate are 10 times higher than what was provided

-----

Github user: @ManonGros
User: [See in registry](https://www.gbif.org/api/feedback/user/ece1936465c54749261ceb13e2826f34:2d6fc4e83c783db2f7fb7f66db2bddb76ff863a33fe125d8187194ef023cfb376fd2043658e56c27c38d7348dfe2d962bcf4407dc7406e6d95a2d6dcb5aae19ec792b30b43d6a86f9a1d7599aace61c92d5bd5daefd771be65f8e244f975cd3e1204a72b02073766e5387ec5719542f2a89cfb9c15e89a2546067bab7094407ec4ad8fc1c19f1b12fc71eb9bbf441bd8) - [Send email](https://www.gbif.org/api/feedback/user/mailto/ece1936465c54749261ceb13e2826f34:2d6fc4e83c783db2f7fb7f66db2bddb76ff863a33fe125d8187194ef023cfb376fd2043658e56c27c38d7348dfe2d962bcf4407dc7406e6d95a2d6dcb5aae19ec792b30b43d6a86f9a1d7599aace61c92d5bd5daefd771be65f8e244f975cd3e1204a72b02073766e5387ec5719542f2a89cfb9c15e89a2546067bab7094407ec4ad8fc1c19f1b12fc71eb9bbf441bd8)
System: Safari 15.3.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/occurrence/download/0279325-210914110416597
Window size: width 1571 - height 876
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-16T13:49:18.549Z',to:'2022-05-16T13:55:18.549Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-05-16T13:49:18.549Z',to:'2022-05-16T13:55:18.549Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
The coordinates and verbatim names seem to be from crawl 13-18, published on 1 April.

The download is from 15 May 03:21 UTC.

The updated dataset with more accurate coordinates and different scientific names, published on 14 May, was not ingested until 16 May due to some problem (I'm not sure who looked at this, it wasn't me).

I don't see an issue with the elevation, can you give an example?

**Comment by ahahn-gbif** [comment]
Sorry for that, Matt, that last part about the elevation is likely unrelated. (My installation of) Excel seems to have got less smart in automatically interpreting field types during import since it last updated, and imported all decimal values as integers, silently dropping the decimal point to increase the value by 10. This is an import error though, nothing to do with the export production.

**Comment by muttcg** [comment]
I [repeated query](https://www.gbif.org/occurrence/download/0284091-210914110416597) and everything is correct, also I checked previous version (dwca source) of that record and it has value "Nephrosperma van-houtteanum (H.Wendl. ex Van Houtte) Balf.f."
Dataset source was updated after user made the download.

**Comment by ManonGros** [comment]
thanks @MattBlissett @muttcg ! I was scared for a moment
