### ISSUE TITLE
ERROR: Your filters might be invalid or the servers having issues. //when searching for occurrences using (latitude, longitude)

### ISSUE THREAD

**Issue by shubhleendhaka** [gbif/portal-feedback#4131]
Hello,

I am using latitude and longitude coordinates of a polygon area to find the occurrences in that area.

Using GeoJSON:
{ "type": "Polygon",
"coordinates": [
[ [-56.92935791,-25.20385129],
[-56.92849961,-25.20397749],
[-56.92877856,-25.20506472],
[-56.92793098,-25.20521033],
[-56.92813483,-25.20578306],
[-56.92898241,-25.2055695],
[-56.92887512,-25.20513267],
[-56.92973342,-25.20498706] ]
] }

which translates to: 
POLYGON((-56.92935791 -25.20385129, -56.92849961 -25.20397749, -56.92877856 -25.20506472, -56.92793098 -25.20521033, -56.92813483 -25.20578306, -56.92898241 -25.2055695, -56.92887512 -25.20513267, -56.92973342 -25.20498706))

While this shows the polygon in the map, I am getting the error " Failed- Your filters might be invalid or the servers having issues. Please try again and report the issue if it continues".

I'm not sure what exactly is causing this error. Any input is appreciated.
Thank you.

**Comment by MortenHofft** [comment]
The geometry is invalid

* Geometries need to be closed - meaning ending and starting on the same coordinates. So you should add `-56.92935791,-25.20385129` as the last coordinate to close it.
  * doing that we get `-56.92935791 -25.20385129, -56.92849961 -25.20397749, -56.92877856 -25.20506472, -56.92793098 -25.20521033, -56.92813483 -25.20578306, -56.92898241 -25.2055695, -56.92887512 -25.20513267, -56.92973342 -25.20498706`
* That is still illegal because it is winded clockwise, making it a hole. So you are asking for anything that IS NOT in the enclosed area. So you need to reverse the list order.

There is no data unfortunately

https://www.gbif.org/occurrence/search?has_coordinate=true&has_geospatial_issue=false&geometry=POLYGON((-56.92973%20-25.20499,-56.92888%20-25.20513,-56.92898%20-25.20557,-56.92813%20-25.20578,-56.92793%20-25.20521,-56.92878%20-25.20506,-56.9285%20-25.20398,-56.92936%20-25.20385,-56.92973%20-25.20499))

Here is a fixed one `POLYGON((-56.92973342 -25.20498706, -56.92887512 -25.20513267, -56.92898241 -25.2055695, -56.92813483 -25.20578306, -56.92793098 -25.20521033, -56.92877856 -25.20506472, -56.92849961 -25.20397749,-56.92935791 -25.20385129, -56.92973342 -25.20498706))`
