### ISSUE TITLE
Participant Table Shows Misleading Metrics

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4163]
**Participant Table Shows Misleading Metrics**

The participant table on the GBIF North America page provides metrics for nodes that are not provided anywhere else and are also misleading and do not accurately reflect and even misrepresent the data mobilization activity happening in the network. We would suggest removing Datasets, Occurrences, Hosted occurrences, and Publishers from the table.

-----

Github user: @albenson-usgs
User: [See in registry](https://www.gbif.org/api/feedback/user/78a7e6fe04da8d5327ba3f59c1d7c9a3:344314ac493efe5ec40a1dc8fda3544dd6fe44326f8010d1285a5e3d890d3e10922ad529314f804fa713d28ecfe35481b66afa9f1bbaafd17c8a2d711846d1a78658b64f07e9cf1bfe1466c43f0d439795c811634ad4a60c0209a913d6df70e4a3be5c1c3cb8e89dafe28f7a40a404d47059f576bb0a29e94d6171579eb2687a) - [Send email](https://www.gbif.org/api/feedback/user/mailto/78a7e6fe04da8d5327ba3f59c1d7c9a3:344314ac493efe5ec40a1dc8fda3544dd6fe44326f8010d1285a5e3d890d3e10922ad529314f804fa713d28ecfe35481b66afa9f1bbaafd17c8a2d711846d1a78658b64f07e9cf1bfe1466c43f0d439795c811634ad4a60c0209a913d6df70e4a3be5c1c3cb8e89dafe28f7a40a404d47059f576bb0a29e94d6171579eb2687a)
System: Chrome 103.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/the-gbif-network/north-america
Window size: width 1095 - height 742
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-07-08T17:27:30.315Z',to:'2022-07-08T17:33:30.315Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-07-08T17:27:30.315Z',to:'2022-07-08T17:33:30.315Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by AbbyBenson** [comment]
I'm confused about this ticket being closed. It doesn't appear any changes are visible here https://www.gbif.org/the-gbif-network/north-america. Is it just not in production yet?

**Comment by MortenHofft** [comment]
Looks like it wasn't deployed yet. I can do that

**Comment by MortenHofft** [comment]
@thomasstjerne I can see in the changes that you have kept the logic, but just doesn't apply it for North America. 

The issue reports that it does not make sense for North America - have you investigated if it makes sense for other regions to stick with this logic? I haven't been part of the discussions or implementations for this page, so it might well make perfect sense for other regions. I have no idea.

@leo-buitrago you might be able to help
https://www.gbif.org/the-gbif-network/latin-america

Is this page meaningful or is it the case like for North America that it is 
> misleading and do not accurately reflect and even misrepresent the data mobilization activity happening in the network

**Comment by leo-buitrago** [comment]
Hi @MortenHofft and @thomasstjerne

- Regarding https://www.gbif.org/the-gbif-network/latin-america I can see the number of datasets by country mismatch when you click on each link. For instance, Colombia shows 2,016 datasets

![Screen Shot 2022-07-18 at 3 24 37 PM](https://user-images.githubusercontent.com/61566113/179611578-4d4b13ce-622f-40ed-9edd-fb0cd8ecc440.png)

...but when you click on it, shows a different amount of datasets
![ds_results](https://user-images.githubusercontent.com/61566113/179621086-c12ac2af-1fda-49cb-9c1b-32d745f7c84c.png)

- The number of occurrences for each country looks OK!
- The number of publishers seems out of date in some cases
![Screen Shot 2022-07-18 at 5 39 36 PM](https://user-images.githubusercontent.com/61566113/179629357-2a174a15-dae8-4437-9906-693404309798.png)

...when you go to the publishers of the country, it shows a different number
![Screen Shot 2022-07-18 at 5 40 39 PM](https://user-images.githubusercontent.com/61566113/179629605-cbd5c5c7-e531-4caf-88b2-fb38835590c5.png)

**Comment by timhirsch** [comment]
I am stepping into this as it is more of a policy matter and has been raised separately as an issue to be addressed through the Nodes Steering Group. These tables are especially problematic in regions such as North America where there are many non-country nodes (aka 'Other Associate Participants') because these organizations can be involved in data publishing via a number of roles including endorser, publisher, host or network. This leads to inconsistencies when metrics are standardized based on particular roles and the organizations themselves understandably feel misrepresented. If as @leo-buitrago notes there are even inconsistencies with the country node metrics it begs the question of whether these tables serve any useful purpose as the information is all available via the country/node pages and these network pages are primarily intended to provide institutional and contact information regarding the GBIF network. I would therefore favour @albenson-usgs 's suggestion to remove the listed columns from these tables and simply keep the first three - 'Participant', 'Membership' and 'Member since'
