### ISSUE TITLE
Publisher search not working proprerly

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4223]
**Publisher search not working proprerly**

Filtering for datasets by the publisher Invasive species Specialist group does not return the correct datasets when you search by country.  Currently, the only country is showing Italy.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/afd558bf7e27da1f8043cab1badfcba5:da63f149a22c635cc1edc3f42c17fcb5655f3b6cf66211811d061dd6e97bbd2e1c3067019e02ee2325ccc6d22934e36fe32d7b646598ac8c12e3c6fa31df307807fca0f8a5c8813046179da6fdaa861038821fe5e40b5008ecd14c1669bc0a8de8b18e0baecb5d7a1a9ec883d68a684c5d9ee95f5cb988b7ed9583fe5044f1630d4118bf05a098c4845084b345b8d924) - [Send email](https://www.gbif.org/api/feedback/user/mailto/afd558bf7e27da1f8043cab1badfcba5:da63f149a22c635cc1edc3f42c17fcb5655f3b6cf66211811d061dd6e97bbd2e1c3067019e02ee2325ccc6d22934e36fe32d7b646598ac8c12e3c6fa31df307807fca0f8a5c8813046179da6fdaa861038821fe5e40b5008ecd14c1669bc0a8de8b18e0baecb5d7a1a9ec883d68a684c5d9ee95f5cb988b7ed9583fe5044f1630d4118bf05a098c4845084b345b8d924)
System: Chrome 104.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/6d9e952f-948c-4483-9807-575348147c7e
Window size: width 1293 - height 579
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-23T15:20:44.777Z',to:'2022-08-23T15:26:44.777Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-08-23T15:20:44.777Z',to:'2022-08-23T15:26:44.777Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
The filter says `Publishing country or Area` and the only option is Italy because all the datasets are published from Italy because the [publisher is listed as located in Italy](https://www.gbif.org/publisher/cdef28b1-db4e-4c58-aa71-3c5238c2d0b5).

If you wish to find a GRIIS checklist for a specific country you should use search. e.g.
https://www.gbif.org/dataset/search?q=Ireland&publishing_org=cdef28b1-db4e-4c58-aa71-3c5238c2d0b5

`Publishing country` clearly isn't what you are interested in in this case, but it is useful for other use cases. But I can see why it is confusing at first glance.

I'm afraid we do not have a `country of coverage` filter

Hope that helps

> send per email
