### ISSUE TITLE
你能帮我下载Pseudapocryptes elongatus的世界分布图吗

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4348]
**你能帮我下载Pseudapocryptes elongatus的世界分布图吗**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/9a1b2a1e3e10dd9e3df4e5713e1635a1:7ac80bcae5b1cb177f4fab365f5e5f719995738c75465f9edb392a86e84f2b6483ec9a3ee9d0b835105dde90390c847fd5d5a0d18c7348f9411d10ceaecf710e9ab620c9a712fd429f129a51cd8c4d2481c98da9354772abb5b9d6c913ba3607) - [Send email](https://www.gbif.org/api/feedback/user/mailto/9a1b2a1e3e10dd9e3df4e5713e1635a1:7ac80bcae5b1cb177f4fab365f5e5f719995738c75465f9edb392a86e84f2b6483ec9a3ee9d0b835105dde90390c847fd5d5a0d18c7348f9411d10ceaecf710e9ab620c9a712fd429f129a51cd8c4d2481c98da9354772abb5b9d6c913ba3607)
System: Chrome 106.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/map?q=Pseudapocryptes%20elongatus&year=2022&occurrence_status=present
Window size: width 1986 - height 1017
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-10-17T12:29:55.647Z',to:'2022-10-17T12:35:55.647Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-10-17T12:29:55.647Z',to:'2022-10-17T12:35:55.647Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
google translate: 
> Can you help me to download the world map of Pseudapocryptes elongatus

**Comment by ManonGros** [comment]
There are only three records for Pseudapocryptes elongatus on GBIF in 2022: https://www.gbif.org/occurrence/search?taxon_key=9794053&year=2022&occurrence_status=present
You can download the records by clicking on the DOWNLOAD tab and choosing a download format.

The free text search doesn’t give the same results because each word is used in the search and it will match other species as will (for examples, all the ones with the scientific epithet “elongatus”). See the taxonomy of the free text search result: https://www.gbif.org/occurrence/taxonomy?q=Pseudapocryptes%20elongatus&year=2022&occurrence_status=present
I suggest to use the scientific name field to look for the records associated with a particular species.

> Replied by email
