### ISSUE TITLE
questions about GBIF api dataset timestamps and ingestion limits

### ISSUE THREAD

**Issue by abubelinha** [gbif/portal-feedback#4394]
Hi. I am having a hard time understanding timestamps to consider when trying to automate dataset updates.
My goal is to use a script for:
1. Login our IPT with dataset manager rights, and "**Publish**" it.
2. Record **timestamp** when step 1 is finished (**T1**).  
3. Sleep the script for a few seconds (**W**): **wait** for gbif.org to grab new IPT content.
4. Use [gbif.org registry API](https://www.gbif.org/developer/registry) to **find out** the timestamp (**T2**) when dataset was last "updated" (meaning **the latest time api/portal content incorporated data/metadata from our IPT**). I am assuming api can tell us this.
5. If T2 is more recent than T1, then portal/api are not reflecting the most up to date information, so I should **make this api call:**
    POST `https://api.gbif-uat.org/v1/dataset/<dataset_uuid>/crawl` (Schedules a **new ingestion of the dataset**)

Step 1 alone was not enough in my previous UAT tests: there are chances that after an IPT dataset update (new version published), portal is not aware of it ... after a very long time -I mean several days- (this happened to me several times, so I decided to try something else).

**Questions (for both UAT and production):** 
- Are there any **known limits in dataset ingestions?** So that registry will ignore my ingestion request if it happens before a certain time (after the previous ingestion of the same dataset).
- Should I **better publish and then request** a new dataset ingestion, skipping steps 2-3-4). **If NOT** skipping, then:
  - How long would you recommend to wait in step 3? (**W**)
  - What value should I use for **T2**?  I am looking at two places:
      - `https://api.gbif-uat.org/v1/dataset/<dataset_uuid>` (and get its `modified` value)
      - `https://api.gbif-uat.org/v1/ingestion/history/<dataset_uuid>` (and get its `results[0][crawlInfo][startedCrawling]` value) 
       Should I play any attention to specific `results[0][crawlInfo][finishReason]` values too?
  - **What exactly is that `modified` timestamp above**? In my tests, it seems to reflect the very last dataset version timestamp exposed by IPT ... even when gbif.org still reflects data from an older version. But this does not make sense to me (portal timestamp matches IPT, but data and metadata don't).
- I noticed api reflects dataset changes before portal does. **How long (at most) is this api-portal delay?** (so I can schedule email notifications to people interested in this dataset)

Thanks a lot
@abubelinha

**Comment by MattBlissett** [comment]
Q1: The registry will ignore updates if there's an update in-progress, i.e. an entry in https://registry.gbif.org/monitoring/running-crawls / https://registry.gbif-uat.org/monitoring/running-crawls.  Occasionally (and more often in UAT) processing gets stuck somehow, and updates to the dataset will be ignored until we manually un-stick the dataset.

Q2: The IPT makes the .../crawl request itself.  The registry then waits 1 minute before adding the dataset to the queue for ingestion.  That queue is often handled immediately, but it can sometimes take hours (if a publisher with hundreds or thousands of datasets is updating them all) or a day or more (if we have paused the queue) to be processed.

The `https://api.gbif-uat.org/v1/dataset/<dataset_uuid>` value is when the dataset's metadata (EML etc) was last updated. I think it's updated for any IPT publication, since there's a publication date and version in the EML the IPT produces.

The ingestion/history will show when any ingestion attempt was made, even if the EML is unchanged, though you'd need to check the value to see if it's successful etc, i.e. finishReason. It's possible for metadata to be updated, but the data itself not to be updated, e.g. if the archive has invalid identifiers or similar.

There are caches in front of the API and the portal, and there are different cache times for different parts of the API/portal. I recommend waiting 15 minutes.

**Comment by abubelinha** [comment]
Thanks for all the info @MattBlissett :+1:
