### ISSUE TITLE
species complex data artificially

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4459]
**species complex data artificially**

Spoke to Sam Rund in Mbita who reports that incoming data reported as species complexes is overinterpreted to genus level only, which is biologically inaccurate. Shall we explore if this is still the case, and fix if not? Additionally, an old issue of 1M records exactly should be reopened

-----

Github user: @dschigel
User: [See in registry](https://www.gbif.org/api/feedback/user/1f59712c75652e5ec0d9682d6fcdc776:3ca08d6f39221725e74fd131b82599cf80d8b735975f746dff0344d3e5dbd4067781d0f16e2d7f47b0c5ded32a5e9f1c0626d77f546f858a3a0d5c060bf72a00df8e9186fd578e1475b6ec7c3f3af7f89cf5fdaae64dfe4757ae132a30df289658bb718c926b146bc07daa7e0f02161c681d435392d3927a405a1f99a314535b) - [Send email](https://www.gbif.org/api/feedback/user/mailto/1f59712c75652e5ec0d9682d6fcdc776:3ca08d6f39221725e74fd131b82599cf80d8b735975f746dff0344d3e5dbd4067781d0f16e2d7f47b0c5ded32a5e9f1c0626d77f546f858a3a0d5c060bf72a00df8e9186fd578e1475b6ec7c3f3af7f89cf5fdaae64dfe4757ae132a30df289658bb718c926b146bc07daa7e0f02161c681d435392d3927a405a1f99a314535b)
System: Chrome 108.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/publisher/5db132f5-ce3f-47a3-a32b-6796c159962c
Window size: width 1920 - height 947
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-12-07T07:47:56.332Z',to:'2022-12-07T07:53:56.332Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-12-07T07:47:56.332Z',to:'2022-12-07T07:53:56.332Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by dschigel** [comment]
@samrund could correct and update this as necessary

**Comment by CecSve** [comment]
I looked through the dataset and have maybe found [an example](https://www.gbif.org/occurrence/3030831524)? In this case, no higher taxonomy and the taxonRank was not filled out by the data publisher. GBIF does not handle hybrids, complexes and aggregates - and only handles major ranks, based on the best fit to the backbone based on the information provided by the publisher. 

It is related to these issues https://github.com/gbif/portal-feedback/issues/2935 and https://github.com/gbif/portal-feedback/issues/4014. Please also be aware of this recent discourse [discussion](https://discourse.gbif.org/t/species-aggregates-complex-in-gbif-taxonomy/3719/3) which can provide guidance to @samrund on how to correct the dataset.

Please also be aware that almost [1000 records](https://www.gbif.org/occurrence/search?issue=TAXON_MATCH_HIGHERRANK&issue=TAXON_MATCH_FUZZY&publishing_org=5db132f5-ce3f-47a3-a32b-6796c159962c) are flagged as `taxon match fuzzy` or `taxon match higher rank` . Please see the following [blog post](https://data-blog.gbif.org/post/issues-and-flags/) for more information.

**Comment by dschigel** [comment]
In the case of vector data I understood it will be a critical lack of service for the community, as cryptic species are being detected as we speak, and aggregation to next higher full rank is loosing important level of detail to the community. I suggest this thread stays open and we bring Paloma into discussion once she starts in January. It might be so that to stay in the vectors game GBIF will have to start handling complexes, tbd. I have a few ideas for the backbone implementation - like a toponym, say, Finland, this word has several "shapefile meanings" during the time of Finland's existence. Similary, a taxon, say species has a time limited duration of validity until it is discovered that what was believed to be a single species is now a complex. This way, all data points identified to this species shown from now on be see as Aus bus complex all the way into the past. Future records can be forked into the s.str and newly delimited species. Hope this logic captures the current highly dynamic and turbulent nature of vector taxonomy, and can be in theory coded into the backbone. I can collect opinions from the task group too, many experts there are actually the ones leading units where complexes are detected

**Comment by CecSve** [comment]
> In the case of vector data I understood it will be a critical lack of service for the community, as cryptic species are being detected as we speak, and aggregation to next higher full rank is loosing important level of detail to the community

Please see the information in the above mentioned discourse thread - the information can be captured in the dwc:scientificName, dwc:verbatimIdentification and dwc:taxonRank field so it is possible to register the species aggregate information. However, the backbone does not deal with aggregates, but it is still very much shareable, searchable and findable.

**Comment by MattBlissett** [comment]
Occurrences identified as species complexes now match to the genus, and have the `TAXON_MATCH_HIGHERRANK` issue applied; see https://www.gbif.org/occurrence/3039147347 for an example.

This dataset (at least the example at the top) isn't affected, as taxonRank isn't provided.

**Comment by CecSve** [comment]
Thanks Matt. I will close the issue.
