### ISSUE TITLE
This year around may/june I went on a field trip with college coleagues and I found a specimen of Platycerus spinifer in Serra da Lousã. Although I registered the finding on Biodiversity4All I think it was not included on the data base of the place. How can I "share" the finding in a more broad way? There is not much information available on this species

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4494]
**This year around may/june I went on a field trip with college coleagues and I found a specimen of Platycerus spinifer in Serra da Lousã. Although I registered the finding on Biodiversity4All I think it was not included on the data base of the place. How can I &quot;share&quot; the finding in a more broad way? There is not much information available on this species**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/369e0435a2c90e8c92b303b4f7cef7cc:9abd8fdc401545c5989b17c11c2005019ec8e0a1b9a643e11009cf4a2d309a7ccdcf82eeccda30c7c61cc8effdcaf91d7502a42845b13ffa57d56ac997f0ac23a432bd00d11dbda7f5ed24535c97480c889d34df11ad79622b0c3c5956a3624f8dbc96b46138a9eece8e5b6492af13780a4b398d22e449f8a1fce01e5c2ea50f28e63be8f14c255e491deda0cfa2de3e) - [Send email](https://www.gbif.org/api/feedback/user/mailto/369e0435a2c90e8c92b303b4f7cef7cc:9abd8fdc401545c5989b17c11c2005019ec8e0a1b9a643e11009cf4a2d309a7ccdcf82eeccda30c7c61cc8effdcaf91d7502a42845b13ffa57d56ac997f0ac23a432bd00d11dbda7f5ed24535c97480c889d34df11ad79622b0c3c5956a3624f8dbc96b46138a9eece8e5b6492af13780a4b398d22e449f8a1fce01e5c2ea50f28e63be8f14c255e491deda0cfa2de3e)
System: Chrome 108.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/user/profile
Window size: width 1536 - height 722
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-12-23T02:05:05.536Z',to:'2022-12-23T02:11:05.536Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2022-12-23T02:05:05.536Z',to:'2022-12-23T02:11:05.536Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by CecSve** [comment]
The user has been contacted through help desk with the following message:

GBIF has a [Biodiversity4All research grade observations](https://www.gbif.org/dataset/2bf7b2c0-34dc-4458-8ee4-4f99fac03b33#description) dataset registered, but I can see that the dataset has not been updated for a couple of years. I would encourage you to instead use [iNaturalist](https://www.inaturalist.org/) to share observations data, since we on a weekly basis get updates on their [research grade observations](https://www.gbif.org/dataset/50c9509d-22c7-4a22-a47d-8c48425ef4a7). Observations that meet the following requirements will automatically be shared with GBIF:
* Published under one of the following licenses or waivers: 1) http://creativecommons.org/publicdomain/zero/1.0/, 2) http://creativecommons.org/licenses/by/4.0/, 3) http://creativecommons.org/licenses/by-nc/4.0/
* Achieved one of following iNaturalist quality grades: Research
* Created on or before 2022-12-13 15:00:11 -0800

**Comment by MattBlissett** [comment]
https://www.biodiversity4all.org/observations/118262280

https://www.biodiversity4all.org/observations/118266406

https://www.biodiversity4all.org/observations/118426065

If these are the occurrences concerned, they aren't shared to GBIF due to the copyright.

Maybe we should ask iNaturalist to add something under "This observation is Research Grade!" like "but due to the copyright licence, it cannot be shared to other platforms".

**Comment by CecSve** [comment]
> Maybe we should ask iNaturalist to add something under "This observation is Research Grade!" like "but due to the copyright licence, it cannot be shared to other platforms".

We occasionally get this feedback on helpdesk where people are not aware of the copyright restrictions on sharing so we could ask if it would be possible for iNat to include.
