### ISSUE TITLE
Species name confusion, to check

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#450]
**Species name confusion, to check**

Please, we are searching for information about Xylocopa cearensis, and we found that the X. cearensis has their scientific name as Gaesischia cearensis in the file we downloaded. But when we checked again on the webpage the scientific name was right (X. cearensis), but when looking for Gaesischia cearensis it appears two Xylocopa cearensis from  SEMK museum. 

  Could you check for us?

-----
fbitem-4cd51ab3c35a7b3305c9ec1422d26bc93a21a482
User provided contact info: b.mcerato@gmail.com
System: Chrome 61.0.3163 / Windows 7 0.0.0
Referer: https://www.gbif.org/occurrence/search?offset=180&taxon_key=1342380
Window size: width 1920 - height 974
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-13T21:13:43.047Z',mode:absolute,to:'2017-09-13T21:19:43.047Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-13T21:13:43.047Z',mode:absolute,to:'2017-09-13T21:19:43.047Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by rdmpage** [comment]
I suspect this is an error, in that _Gaesischia cearensis_  (Ducke) https://www.gbif.org/species/1344722 and _Xylocopa cearensis_ Ducke https://www.gbif.org/species/1342380 are almost certainly not the same thing. The page for _Gaesischia cearensis_  https://www.gbif.org/species/1344722 has the flags **basionym relation derived** and **conflicting basionym combination**. As far as I can tell, _Xylocopa cearensis_  was described by Ducke here: http://biostor.org/reference/234514/page/8  The name _Gaesischia cearensis_ is not the original combination, the only place I can find mention of the original combination is http://www.moure.cria.org.br/catalogue/catalogue?id=30522 where the original name is _Eucera cearensis_ (published here http://biostor.org/reference/234514/page/14 ). So I suspect that maybe the basionym algorithm @mdoering came up with that usually works well has linked these two names by mistake (due to Ducke using the same specific name in the same year for two related insects - sigh).

**Comment by mdoering** [comment]
That sounds exactly like the issue. It must also be in the same family to be considered

**Comment by jlegind** [comment]
I did a test download and the issue seems to be fixed 
https://doi.org/10.15468/dl.8z6fb7
