### ISSUE TITLE
Class Actinopterygii being excluded

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4507]
**Class Actinopterygii being excluded**

The valid class Actinopterygii is being excluded from all records in my fish collection.  Any idea why?

-----

Github user: @acbentley
User: [See in registry](https://www.gbif.org/api/feedback/user/3d62fa94af0267430f5597390f0a6584:c4020e6093f01ee8bc1aa3b66e13e133b83ef4bc19295eb8eab6ef309d041feeef32918764dd0018688d6a7a6906aa74c4fa31c413d616c3f2cbc32e7c3f8c8e934849f0e97d28a38294de6f6fe260735c1e3f0d822e031ae2ecdda71de88c52f5a274b7cb63e42c4348e3e53fd3afba55320aa7cb93ce0fea07070e99b956ab) - [Send email](https://www.gbif.org/api/feedback/user/mailto/3d62fa94af0267430f5597390f0a6584:c4020e6093f01ee8bc1aa3b66e13e133b83ef4bc19295eb8eab6ef309d041feeef32918764dd0018688d6a7a6906aa74c4fa31c413d616c3f2cbc32e7c3f8c8e934849f0e97d28a38294de6f6fe260735c1e3f0d822e031ae2ecdda71de88c52f5a274b7cb63e42c4348e3e53fd3afba55320aa7cb93ce0fea07070e99b956ab)
System: Chrome 108.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/dataset/8f79c802-a58c-447f-99aa-1d6a0790825a/metrics
Window size: width 1152 - height 645
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-03T19:51:39.747Z',to:'2023-01-03T19:57:39.747Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-03T19:51:39.747Z',to:'2023-01-03T19:57:39.747Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
@acbentley, this is because Actinopterygii is no longer a class in the GBIF backbone taxonomy. In the Catalogue of Life, [Actinopterygii](https://www.catalogueoflife.org/data/taxon/8VR36) is a gigaclass. Unfortunately, we don't support intermediate taxon ranks. So this means we don't have Actinopterygii any more.

There are some related issues you can check: https://github.com/gbif/checklistbank/issues/79 and https://github.com/gbif/pipelines/issues/850 amongst others.

I will close the issue, let me know if it should be reopened.
