### ISSUE TITLE
Changing apparently empty cells in a download to empty cells

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4524]
**Changing apparently empty cells in a download to empty cells**

I want to delete columns from an occurrence download that contain no data to - using excel. I try using the counta function (counts  ells empty by Excel standards) and it says there are no empty cells in the download. I am sure there is a quick way  of doing this and am hoping that someone there will tell me what it is. 
Thank you.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/170b26cd369ba31977f842dfc5012ed6:aa6d9c20083c4a0b5b361ac8a59da469ab81865a85182e446bfd13eb1d04ca978a11ae96f36d2b0885aa0f9140bed81f5f036224ce99b67f57f5468f1e558cbf562a99ec2a37bb0e3eca9618e8caf084fff47e0e64758bfcc45922f1b152262cfc66d8b108dece580a8b754b666d0877fd06228f8e1f2309ec228aef49f282e20fafbe7da272f74ae8d1cd7273e65ca0) - [Send email](https://www.gbif.org/api/feedback/user/mailto/170b26cd369ba31977f842dfc5012ed6:aa6d9c20083c4a0b5b361ac8a59da469ab81865a85182e446bfd13eb1d04ca978a11ae96f36d2b0885aa0f9140bed81f5f036224ce99b67f57f5468f1e558cbf562a99ec2a37bb0e3eca9618e8caf084fff47e0e64758bfcc45922f1b152262cfc66d8b108dece580a8b754b666d0877fd06228f8e1f2309ec228aef49f282e20fafbe7da272f74ae8d1cd7273e65ca0)
System: Chrome 109.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/resource/search?offset=20&contentType=tool
Window size: width 2131 - height 1030
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-15T15:57:24.277Z',to:'2023-01-15T16:03:24.277Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-01-15T15:57:24.277Z',to:'2023-01-15T16:03:24.277Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by CecSve** [comment]
We have contacted the user through helpdesk with the following explanation:

We have tried investigating a bit and although none of us are Excel wizards and can only provide limited support, it seems like the usual way of importing the data to excel introduces zero-length strings in the cells that otherwise appears blank.
You can use these three functions and they vary a bit in how the work:

**The ISBLANK Function**
The ISBLANK function returns TRUE if the cell is empty and FALSE if a cell is blank.
**The COUNTA Function**
The COUNTA function counts blank cells but does not count empty cells.
**The COUNTBLANK Function**
The COUNTBLANK function counts both blank cells and empty cells.

In this particular case, assuming that [this is the dataset you downloaded](https://www.gbif.org/occurrence/download/0248185-220831081235567), the occurrence file comes as a .txt file. Try to open excel and then drag the occurrence file into excel – this leaves the cells blank and you can use the COUNTA function to filter the data. 
I hope it works out.

**Comment by CecSve** [comment]
I will close this issue as it seems like it has been resolved based on correspondence on helpdesk. Please reopen if the issue persist.
