### ISSUE TITLE
Add my name(Qadry Anthony) to my observations.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4781]
**Add my name(Qadry Anthony) to my observations.**

May you please add my full name to all my observations? 
https://www.gbif.org/occurrence/4076054821
https://www.gbif.org/occurrence/4080672019
https://www.gbif.org/occurrence/4080945906
https://www.gbif.org/occurrence/4080451644
https://www.gbif.org/occurrence/4076112880
https://www.gbif.org/occurrence/4076045876
https://www.gbif.org/occurrence/4076175953
https://www.gbif.org/occurrence/4067556497
https://www.gbif.org/occurrence/4067551519
https://www.gbif.org/occurrence/4054968092

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/622c5b42c93cbc0a5db00da05491b358:f449905b874bb37a01b0ebc63e6001007535d13de662d480c022907ff16963c793d2effa4bc57c5a2f8f63729996dcf5429770c8d1f35d70f081a92b0ae50ac7c89652f6170e08530a5523e2b7381df544c8770f021a76628e5a43dc9981bb373051b558ef9ad1ff17608d5af17ead48b34968d28aa4a40ba30b71fea0ee46c839857f33cf95fe397b49ca13d44a1ce3) - [Send email](https://www.gbif.org/api/feedback/user/mailto/622c5b42c93cbc0a5db00da05491b358:f449905b874bb37a01b0ebc63e6001007535d13de662d480c022907ff16963c793d2effa4bc57c5a2f8f63729996dcf5429770c8d1f35d70f081a92b0ae50ac7c89652f6170e08530a5523e2b7381df544c8770f021a76628e5a43dc9981bb373051b558ef9ad1ff17608d5af17ead48b34968d28aa4a40ba30b71fea0ee46c839857f33cf95fe397b49ca13d44a1ce3)
System: Mobile Safari 16.4.0 / iOS 16.4.1
Referer: https://www.gbif.org/occurrence/4076175953
Window size: width 390 - height 663
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-05-22T06:47:13.629Z',to:'2023-05-22T06:53:13.629Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-05-22T06:47:13.629Z',to:'2023-05-22T06:53:13.629Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL
datasetKey: 50c9509d-22c7-4a22-a47d-8c48425ef4a7
publishingOrgKey: 28eb1a3f-1c15-4a95-931a-4af90ecb574d

Node handles: @albenson-usgs @sformel-usgs

**Comment by chadjones1** [comment]
Oh my God, delete this entire thread!

**Comment by CecSve** [comment]
User has been contacted through helpdesk May 22th 2023.

GBIF cannot add names to observations coming from iNaturalist. Like all other datasets published to GBIF, it is up to the publisher to maintain, adapt and update their datasets. Since iNaturalist is a citizen science portal, GBIF only includes the data that the observer provides. If only a username is supplied to an observation, then this will appear on the GBIF version of the record. If the iNaturalist user adds their name to the profile, then the name should be attributed instead. However, the change may take some time, since the dataset is ingested weekly and may take several days to update due to the high amount of records passing through our pipelines.

**Comment by sformel-usgs** [comment]
Just going through the US tagged issues to see what can be cleaned up and this update appears to have gone through. @ManonGros or @ktotsum, is it presumptuous of me to ask you to close this issue?
