### ISSUE TITLE
Inconsistency between resource agents in the IPT and contacts listed in the portal

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4782]
**Inconsistency between resource agents in the IPT and contacts listed in the portal**

One of the resource contacts (Biomedia) on this dataset page is missing even though it is filled out exactly the same way as Amphi Consult in the IPT/metadata file. 

Can you explain how come @MortenHofft @thomasstjerne ? The publisher would prefer that resource creators **are not** included as contacts if they are not listed under resources contacts as well (which both currently are not), however, all resource agents (should) automatically be added to the contacts list, based on feedback from @mike-podolskiy90 .

@mike-podolskiy90 would it make sense/be possible to include resource creators to the citation, but not include them as contacts unless they were also registered as resource contacts?

-----

Github user: @CecSve
User: [See in registry](https://www.gbif.org/api/feedback/user/acfd1c095e1a6f9de899d9f4f450bc22:c726c6f5ce42328b5500f721ad3f05394c19fce001b4f81e7c3563530982b0b5be410db8e75f87709bf966238a1cb171c4127f1e35911ccdfda24b26083f8e831fde919a6963dc227350bd34f272e15db35cbbb49ff9143bef203fceb93f36fe) - [Send email](https://www.gbif.org/api/feedback/user/mailto/acfd1c095e1a6f9de899d9f4f450bc22:c726c6f5ce42328b5500f721ad3f05394c19fce001b4f81e7c3563530982b0b5be410db8e75f87709bf966238a1cb171c4127f1e35911ccdfda24b26083f8e831fde919a6963dc227350bd34f272e15db35cbbb49ff9143bef203fceb93f36fe)
System: Firefox 113.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/72e23311-b65a-46d0-bc07-ff0a251b47e1
Window size: width 1600 - height 796
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-05-22T10:14:40.844Z',to:'2023-05-22T10:20:40.844Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-05-22T10:14:40.844Z',to:'2023-05-22T10:20:40.844Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
All contacts from the API will be listed. But grouped based on a best guess. This it to avoid repeating the same person 10 times with different roles.
We group on 
userID
OR:  email+ optional firstName+ optional lastName
OR: firstName + lastName (both must be present)
OR: organisation

in this case that clearly isn't a good idea. Since they publish orgName + lastName only. So the identifier becomes the orgName only. And so the 2 become one.
I've changed that and will deploy it shortly. The rule is now to group contacts on:
userID
OR:  email+ optional firstName+ optional lastName
OR: firstName + lastName + orgName.

That said the data looks wrong to me as well.
orgName: NA (I assume that is Not Available?)
lastName: Biomedia
looks odd or wrong to me.

**Comment by AstridBVW** [comment]
@MortenHofft Both Amphi Consult and Biomedia are consulting companies, and we had trouble fitting the IPT format for resource agents when the agent is not a person but an organization. They were added as resource creators because they needed to be the authors in the citation. Because of the format we were forced to fill out lastName, position and orgName, so we chose to put the company name as lastName and "NA" (not applicable) as orgName. We didn't think it would matter that much since only the lastName would be visible in the citation. We were not aware that they would be added to Contacts as well.

But you are right, it does not look good... Do you have a suggestion for how to better add an organization as a resource agent?

**Comment by mike-podolskiy90** [comment]
In case of company/organization you can put its name in the organization field and just skip first name/last name/position fields

**Comment by AstridBVW** [comment]
@mike-podolskiy90 But are lastName and position not mandatory fields? They are marked with a red "*" (as is the organization field).

**Comment by mike-podolskiy90** [comment]
They are required only for person agents. In case of organization you can omit them. That is a bit confusing, I guess we need to remove those asterisks characters.

**Comment by AstridBVW** [comment]
Ok, we were not aware of that but good to know. I think I will then change the agents and do what you suggest. Do orgName then take the place of lastName? Also, I can see that @MortenHofft already deployed the new rule (Biomedia is now on the Contacts list). If I understand correctly the new rule will still work if I change them to organization name in organization field and skipping firstName/lastName/position?

**Comment by mike-podolskiy90** [comment]
Yes, organization name will be used as a title instead of last name/first name

**Comment by CecSve** [comment]
Thanks for the help on this. I will close the issue.

**Comment by MattBlissett** [comment]
I think only using an organization (without a lastName) will omit the organization from the citation.  We should investigate whether that's still appropriate -- @ahahn-gbif ?

**Comment by ahahn-gbif** [comment]
If I understood the case here correctly, inclusion of the two organizations in the citation is not intended, though they should be listed in the contacts section. In that sense, we may still want to reevaluate, but it is not immediately relevant for this case. 

Opening the citation up for including organizations without personal contacts may have some undesired effects for other existing dataset metadata; I would be reluctant to change that without good reason and prior investigation. Do we have known cases where an organization listed in the contacts section should be named in the authorship? If so, I would rather take it out of this issue and open its own.

**Comment by CecSve** [comment]
> inclusion of the two organizations in the citation is not intended, though they should be listed in the contacts section

Actually, it is the other way around. They want the organizations included in the citation, but not under contacts on the dataset page.

**Comment by MattBlissett** [comment]
Astrid wrote:

> Both Amphi Consult and Biomedia are consulting companies, and we had trouble fitting the IPT format for resource agents when the agent is not a person but an organization. They were added as resource creators because they needed to be the authors in the citation.

and the citation is currently:

> Amphi Consult, Biomedia (2023). Nature monitoring data, Amphi Consult and Biomedia, Denmark. Version 1.5. Danish Biodiversity Information Facility. Occurrence dataset https://doi.org/10.15468/92c8yj accessed via GBIF.org on 2023-05-22.

Citations are currently generated following the process described here: https://github.com/gbif/registry/blob/dev/docs/citations.md

**Comment by ahahn-gbif** [comment]
Sorry, I was too hasty there.

Two separate questions then
1) can an agent entity be part of the citation authorship without automatically also being listed in the contacts? (@MortenHofft)
2) should we add the names of organizational agents without personal contacts to the citation generation rules (provided they are in the same role as personal agents are)

to 1): Is the reason for not wanting the two organizations listed in the contacts section still given, now that they can both be shown? The original issue was that they got merged into one, based on the de-duplication of the portal UI. Now that this is solved, is it still true that they should not show at all in the contacts section? Did I misunderstand the reason, @AstridBVW?

to 2): If a company is added to the right agent role, I guess they could be included in the citation. I would just like to check how many existing datasets that would actually cause to change their citation. I don't expect many (if any), but as publishers invest time into getting their citations configured, a rule change may backfire.

**Comment by MattBlissett** [comment]
I think ② would affect ... wow, 14,074 datasets, as it's presumably all of PANGAEA and many others.

Couple of examples: 
* https://www.gbif.org/dataset/132121e7-04ca-4217-b177-7b990e4937c6
* https://www.gbif.org/dataset/6621796c-f762-11e1-a439-00145eb45e9a

```sql
select d.key, c.first_name, c.last_name, c.organization 
  from dataset d, dataset_contact dc, contact c 
  where d.key = dc.dataset_key and dc.contact_key = c.key 
  and d.deleted is null 
  and dc.type in('METADATA_AUTHOR', 'ORIGINATOR') 
  and c.organization is not null 
  and c.last_name is null;
```

**Comment by ahahn-gbif** [comment]
Thanks!
Not ideal. Can we hold it please? This will not be a quick change, in any case - sorry!

**Comment by AstridBVW** [comment]
> to 1): Is the reason for not wanting the two organizations listed in the contacts section still given, now that they can both be shown? The original issue was that they got merged into one, based on the de-duplication of the portal UI. Now that this is solved, is it still true that they should not show at all in the contacts section? Did I misunderstand the reason?

Yes, it is still true that it would be preferred to not have the organizations shown at all in the contacts section. Biomedia is no longer in business and Amphi Consult will not be able to help people in regards to the dataset. I'm going to leave out the lengthy explanation for why they should be in the citation but not in the contacts section, and why other resource agents need to be in the contacts section instead - just know that there is a perfectly good explanation and this solution has been decided on in cooperation with the dataset provider.

However, if it causes too much trouble across GBIF to change it, I think we can live with them being shown in the contacts section. And yes, if they cannot be removed it is better that they are at least both shown. But if they are going to remain in the contacts section, I would like to remove the "NA" from the organization field - is it possible to leave this empty? As you stated, I will not be able to move the organization names to orgName instead of lastName without removing them from the citation which I definitely do not want!

**Comment by MortenHofft** [comment]
@ahahn-gbif asked
> can an agent entity be part of the citation authorship without automatically also being listed in the contacts?

Not as it is now. The website shows all contacts. But we could change that of course. But I would need a rule for what the new logic is. Please open an issue in [portal16](https://github.com/gbif/portal16/issues/new) if we want to change the rules for which contacts show in contacts. So far we have simply strived to reflect the API. But we could easily exclude certain roles if we wanted to

**Comment by ahahn-gbif** [comment]
Thanks @MortenHofft - I don't think we can formulate a general rule for this, it is rather a single-case wish/requirement.

**Comment by ahahn-gbif** [comment]
> I would like to remove the "NA" from the organization field - is it possible to leave this empty?

Apologies for not having tested this, @AstridBVW - would you mind giving it a try? Alternatively, something like '---' or even a repetition of the organization name might be better than NA

**Comment by AstridBVW** [comment]
No problem! And just tried it, thankfully it is possible!

<img width="550" alt="Screenshot 2023-05-23 at 15 19 49" src="https://github.com/gbif/portal-feedback/assets/97025379/b2dcb1af-432c-473a-9355-48e1300f80e8">

I know we didn't solve it but I'm still very glad that I asked. Now I know so much more about how the machinery works - that will come in handy! Thanks everyone!

**Comment by ahahn-gbif** [comment]
Good to hear - thanks for your patience here! I'll close the issue again then.
