### ISSUE TITLE
lista de mamiferos

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#482]
**lista de mamiferos**

solo quiero la lista de mamiferos de tabasco pero no me da opciones de descargas yo o quiero en shape aayuuudaaa

-----
fbitem-8b16037cf12b5f958bf6d374db1c1429764c1b51

System: Chrome 60.0.3112 / Windows 10 0.0.0
Referer: https://www.gbif.org/occurrence/download?country=MX
Window size: width 1366 - height 662
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-24T17:48:21.973Z',mode:absolute,to:'2017-09-24T17:54:21.973Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-09-24T17:48:21.973Z',mode:absolute,to:'2017-09-24T17:54:21.973Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by rdmpage** [comment]
Translation (Google, mostly):

> I just want the list of Tabasco mammals but it does not give me options to download me or I want in shape heeelllppp.

I think this has come up before, but this is probably the most obvious query (give me a list of species in this area) and it's not obvious how to do this...

**Comment by MortenHofft** [comment]
It seem to me to be two issues

**download species lists**
It isn't an option I'm afraid. The user however have correctly found the [view](https://www.gbif.org/occurrence/species?country=MX) it seems but wonders why it isn't available for [download](https://www.gbif.org/occurrence/download?country=MX). It is a great idea and captured here https://github.com/gbif/portal-feedback/issues/122 . The suggestion also came up at GB24. For the download to have a proper citation this need to go into the API.

**Filtering by locations instead of providing polygon**
Not entirely sure if this is what is meant with "want in shape", but it ss captured https://github.com/gbif/portal16/issues/248 and I just created a more elaborate issue https://github.com/gbif/portal16/issues/560

Could also be a desire to download it as a shapefile. @fmendezh maybe you can help explain what is meant better than Google can?
