### ISSUE TITLE
Eliomys quercinus data in Iberia

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#4849]
**Eliomys quercinus data in Iberia**

The data of distribution of Eliomys quercinus conteins some serious problems. E.g. species is indicated to occurs in the sea. I suspect data was downloaded from some grids/atlas and not particular locations are provided. This is not really realistic and useful to include here.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/fb849552f166a79b74a7884310a55063:a4a8c40490a8d662b04bd514384cef2f7d87c36a0a2fdbac4dc47bafee3989e6b4b56474e2d0d0d6cf281fac71c4ae7cc61222d06ff5704f010b5308e809968b3575d8f0f0852eba4df42faecc7ba0f47261ed3edec8c636b4335394a980ebe0373f1fa020af6ec84a4bae77475f3b2c01bb0096c20b4923b946196dafe6945911f28ff2d6b88760a9d7a439714185c2) - [Send email](https://www.gbif.org/api/feedback/user/mailto/fb849552f166a79b74a7884310a55063:a4a8c40490a8d662b04bd514384cef2f7d87c36a0a2fdbac4dc47bafee3989e6b4b56474e2d0d0d6cf281fac71c4ae7cc61222d06ff5704f010b5308e809968b3575d8f0f0852eba4df42faecc7ba0f47261ed3edec8c636b4335394a980ebe0373f1fa020af6ec84a4bae77475f3b2c01bb0096c20b4923b946196dafe6945911f28ff2d6b88760a9d7a439714185c2)
System: Firefox 114.0.0 / Ubuntu 0.0.0
Referer: https://www.gbif.org/species/2439683
Window size: width 1600 - height 805
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-07-03T13:23:00.258Z',to:'2023-07-03T13:29:00.258Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-07-03T13:23:00.258Z',to:'2023-07-03T13:29:00.258Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: WARNING

**Comment by ktotsum** [comment]
We add flags to occurrence data for obvious issues only (see [this blog](https://data-blog.gbif.org/post/issues-and-flags/)).  Publishers are encouraged to provide coordinateUncertaintyInMeters for coodinates as opening exact location is not always the case because of sensitive species and survey methods. 

We found that an example of occurrence for Eliomys quercinus shows coordinates with uncertainty. If you zoom in on the map, you can see a red circle covering both the ocean and the land for this species.
https://www.gbif.org/occurrence/998531381

[This blog](https://data-blog.gbif.org/post/gbif-filtering-guide/) can be useful for dealing with cleaning data downloaded from GBIF if you are familiar with R.
