### ISSUE TITLE
Class/order values incorrect/missing across classes Reptilia and Actinopterygii

### ISSUE THREAD

**Issue by neoformit** [gbif/portal-feedback#4906]
I am using the API to annotate a list of species with a taxonomic hierarchy. I have noticed that there are several classes across which `class` and `order` are incorrectly assigned. This appears to occur in classes Reptilia and Actinopterygii (perhaps others).

**Example 1** _Reptilia_: https://api.gbif.org/v1/species/match?name=Alligator%20mississippiensis

This error was present in all five _Reptilia_ that I queried. See also:
- https://api.gbif.org/v1/species/match?name=Anolis%20carolinensis
- https://api.gbif.org/v1/species/match?name=Chelonia%20mydas
```js
// Expected
{
  "class": "Reptilia",
  "order": "Crocodylia",
}
// Observed
{
  "class": "Crocodylia",
  // order key missing
}
```

**Example 2** _Actinopterygii_: https://api.gbif.org/v1/species/match?name=Clupea%20harengus

This error was present in all 30 _Actinopterygii_ that I queried. See also:
- https://api.gbif.org/v1/species/match?name=Danio%20rerio
- https://api.gbif.org/v1/species/match?name=Esox%20lucius
```js
// Expected
{
  "class": "Actinopterygii",
  "order": "Clupeiformes",
}
// Observed
{
  // class key missing
  "order": "Clupeiformes"
}
```

**Comment by ManonGros** [comment]
Hi @neoformit sorry for the delayed answer.
We follow the classification from the Catalogue of Life in which Reptilia and Actinopterygii are no longer classes ([Actinopterygii is a Giga](https://www.catalogueoflife.org/data/taxon/8VR36) class now). Our backbone doesn't support intermediary ranks so we are unable to provide the higher classification for those.

In order to help users find reptiles, we create an artificial Reptilia class as synonym of the four "reptile" classes. https://www.gbif.org/species/search?q=reptilia

Here are some related issues: https://github.com/CatalogueOfLife/data/issues/484 https://github.com/gbif/portal-feedback/issues/4528 https://github.com/gbif/portal-feedback/issues/4507

**Comment by neoformit** [comment]
Thanks!
