### ISSUE TITLE
Wrong ROR-ID in GrSciColl

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5011]
**Wrong ROR-ID in GrSciColl**

When I looked at https://registry.gbif.org/institution/0e919a55-08d3-4bd2-aec1-200858fafd92/identifier I see the RoR-ID of our institute (Naturalis, The Netherlands) as: https://ror.org/0566bfb96, which is correct.

Looking however at GrSciColl (https://scientific-collections.gbif.org/institution/0e919a55-08d3-4bd2-aec1-200858fafd92 )I see a wrong RoR-ID: 
https://ror.org/https://ror.org/0566bfb96 (the first part of the URL replicated) This URL doesn't resolve and is not correct. I have seen this with other institutes as well e.g. Het Natuurhistorisch  (https://scientific-collections.gbif.org/institution/7bf98185-7f54-47c9-b4fc-486b060bb102), would nice is if this bug could be fixed.

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/04df8c5e98bf181b26280de5ee6ec0b2:4f27f5a9b4f2e8438b2889140925d656612c75f33f57872319f0490f0931f9f8607aac59be6c90036c2465d1008f2f122ede0ff385f33988c248ff5b4f61994288ca1e83fe329205e78f0ea44a2a75433bf708d9dd523b10ab0f520241d2ce9c7379734551bcf8e8c82b5546489984c8d714f3826a61438bed14d71c5a5a350b8a82d5a9cb8731f4bd6d9fd2929c1bdc) - [Send email](https://www.gbif.org/api/feedback/user/mailto/04df8c5e98bf181b26280de5ee6ec0b2:4f27f5a9b4f2e8438b2889140925d656612c75f33f57872319f0490f0931f9f8607aac59be6c90036c2465d1008f2f122ede0ff385f33988c248ff5b4f61994288ca1e83fe329205e78f0ea44a2a75433bf708d9dd523b10ab0f520241d2ce9c7379734551bcf8e8c82b5546489984c8d714f3826a61438bed14d71c5a5a350b8a82d5a9cb8731f4bd6d9fd2929c1bdc)
System: Chrome 118.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/dataset/search
Window size: width 1920 - height 931
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-10-18T12:00:47.801Z',to:'2023-10-18T12:06:47.801Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-10-18T12:00:47.801Z',to:'2023-10-18T12:06:47.801Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
That is because the ID isn't the url, but the ID. At least that has been my interpretation. But it isn't very clear what the inteded usage is, not when filling it in, nor when using it. So I suspect it is used inconsistently.

We should provide clear guidelines on this and ideally enforce it. 
ping @ManonGros and @marcos-lg 

In the UI we could try to parse it and tease out the ID part, but it isn't ideal
example of different formats 
https://registry.gbif-uat.org/institution/0e919a55-08d3-4bd2-aec1-200858fafd92/identifier

**Comment by ManonGros** [comment]
Thanks @MortenHofft I added a lot of ROR ID to GRSciColl entries by following the ROR guidelines which is to use the URLs: https://ror.org/about/faqs/#what-is-a-ror-identifier I think most GRSciColl editors would follow this guidelines and we should assume they do.
I will put an FAQ on the GRSciColl website that links to the FAQ on ROR. Should we also add checks to the identifier input form?

**Comment by MortenHofft** [comment]
The backend could either normalise it or return an error?
Possibly start with cleaning up exiting entries?

**Comment by scooleman** [comment]
How are the formats of ROR ID currently being technically implemented in the GRSciColl pathway?

Although displayed correctly in the institution’s GRSciColl overview, could the short format of ROR ID as institutionID cause the flag 'Institution match fuzzy' for specimen occurrence records?

See these 3 examples from different datasets of RBINS specimens, where the institutionCode is filled in properly:

1. https://www.gbif.org/occurrence/3024456326 
2. https://www.gbif.org/occurrence/2520914208 
3. https://www.gbif.org/occurrence/891848626 
 

![institutionID_Screenshot 2024-06-13](https://github.com/gbif/portal-feedback/assets/114440133/d3557c5f-d634-48d9-bf07-9bb50a0c46a7)

Since the ownerInstitutionCode data field isn’t mapped in this third example, it gives the impression that this issue about the flag 'Institution match fuzzy' is not directly linked to the data field ownerInstitutionCode self.

cf. similar issues earlier described at:
-	https://github.com/gbif/registry/issues/496
-	https://github.com/gbif/portal-feedback/issues/3869 


Subsequently, the only other possible data field that could be causing that flag, appears to be the format of the value of the ROR ID in the data field institutionID. 

At the moment, there’s just "**02y22ws83**" (as the unique 9-character string of the ROR ID without the ROR domain as prefix) saved as identifier for the institution RBINS in its GBIF Registry: 
https://registry.gbif.org/institution/c2bfdeef-9c03-435e-8465-c483dadd6995/identifier 
It appears as "**https://ror.org/02y22ws83**" for ROR ID value in the institution’s GRSciColl overview: 
https://scientific-collections.gbif.org/institution/c2bfdeef-9c03-435e-8465-c483dadd6995

However, if the GBIF system that's creating issued flags, would just take the value that is filled in in the GBIF Registry (and not the value that is displayed in the GRSciColl) into account, we can add the entire value of ROR ID "https://ror.org/02y22ws83" in the GBIF Registry (even if it’d be displayed differently in the institution’s GRSciColl overview, although that would supposedly keep on creating confusion among data managers - what would be another item, ideally yet to solve).

**Comment by scooleman** [comment]
In an example of a specimen record from the Univ. of Bergen, the short format as the unique 9-character string of the ROR ID (without the ROR domain as prefix) is also the only ROR ID in their institution's GBIF Registry:

[University of Bergen](https://registry.gbif.org/institution/955b0e63-c3b5-4d74-8dfa-15b384b9ae77/identifier)

displaying the resolvable ROR ID as url in their institution’s GRSciColl overview:
https://scientific-collections.gbif.org/institution/955b0e63-c3b5-4d74-8dfa-15b384b9ae77

without that flag in their specimen records, for instance:
https://www.gbif.org/occurrence/4430082301

What could cause that flag for RBINS specimen records?

**Comment by ManonGros** [comment]
Thanks for pointing out the issue @scooleman. I think the reason why there is a fuzzy match is because the ROR identifier stored in GRSciColl ("02y22ws83" he unique 9-character string of the ROR ID without the ROR domain as prefix) isn't the same as the identifier provided in the occurrence institutionID.

The fact that we add the prefix on the website makes it confusing.

I think we should display the ROR identifiers as they are provided.

I will try to clean up all the ROR identifiers next week so that they correspond to the full URLs. @MortenHofft, I will let you know when I am done and maybe you could remove the URL prefix from the display?

**Comment by MortenHofft** [comment]
Sure - it would be nice if we cleaned it up, and also made sure that it could only be entered in the correct format in the API. To avoid this being a recurring issue

**Comment by ManonGros** [comment]
Thanks @MortenHofft, I agree and I have now logged an issue https://github.com/gbif/registry/issues/591

I have corrected all the ROR ids that we had, they now all look like URLs. Could you changed the display on the GRSciColl website? Thanks!

**Comment by MortenHofft** [comment]
Does GRID ids need cleaning as well? Or possibly migrating them to ROR?

**Comment by ManonGros** [comment]
@MortenHofft apparently GRID has officially passed the torch to ROR. I couldn't find recommendations for GRID but I assume that they are the same as ROR. I will clean up the entries we have (not that many) and I think we should display them as they are.
