### ISSUE TITLE
Can you help me understand what each of the column name and meaning stands for in EOD – eBird Observation Dataset (India dataset) As that will help me understanding the CR,EN,VU,NT,  species of birds and i can understand which of NE and LC might in future will be listed in IUCN Redlist. I took for this project for my graduate course  of bigdata

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5023]
**Can you help me understand what each of the column name and meaning stands for in EOD – eBird Observation Dataset (India dataset) As that will help me understanding the CR,EN,VU,NT, species of birds and i can understand which of NE and LC might in future will be listed in IUCN Redlist. I took for this project for my graduate course of bigdata**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/3a99f590c4a8db83fb79a558dfc73076:e121da1c3d4b9162c44fd7c500f7a352d3b54c7b4a4a5f4ea0b769560031208739fb9d3ac5a9ef68b5097e6e85c272bb1facc1b3bf5fe2ebf0f2404068c9fde77923b447e9be230be94eaf069b6e50da2f94060cf07755f76258b9f03efe91e055e25055d16b5816164959851fc21b8c) - [Send email](https://www.gbif.org/api/feedback/user/mailto/3a99f590c4a8db83fb79a558dfc73076:e121da1c3d4b9162c44fd7c500f7a352d3b54c7b4a4a5f4ea0b769560031208739fb9d3ac5a9ef68b5097e6e85c272bb1facc1b3bf5fe2ebf0f2404068c9fde77923b447e9be230be94eaf069b6e50da2f94060cf07755f76258b9f03efe91e055e25055d16b5816164959851fc21b8c)
System: Chrome 118.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/search?country=IN&dataset_key=4fa7b334-ce0d-4e88-aaae-2e0c138d049e&publishing_country=IN&advanced=1&iucn_red_list_category=CR
Window size: width 1536 - height 707
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-10-27T02:08:38.149Z',to:'2023-10-27T02:14:38.149Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-10-27T02:08:38.149Z',to:'2023-10-27T02:14:38.149Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ktotsum** [comment]
(replied by email from helpdesk)

The data download of [your search result](https://www.gbif.org/occurrence/search?country=IN&dataset_key=4fa7b334-ce0d-4e88-aaae-2e0c138d049e&publishing_country=IN&advanced=1&iucn_red_list_category=CR) contains both Darwin Core terms and GBIF interpreted terms. Please see definitions for each term below.

Darwin Core terms for occurrences: https://rs.gbif.org/core/dwc_occurrence_2022-02-02.xml
GBIF interpreted terms: https://gbif.github.io/dwc-api/apidocs/org/gbif/dwc/terms/GbifTerm.html

More information on data processing is available [here](https://www.gbif.org/en/article/5i3CQEZ6DuWiycgMaaakCo/gbif-infrastructure-data-processing). Since you are interested in the IUCN Red list, I recommend reading [this news item](https://www.gbif.org/news/3vu7HxLgHTqKtSF69oNqNr/new-feature-enables-search-of-occurrence-data-by-global-iucn-red-list-category) for the implementation of the IUCN Red List filter in occurrence search.
