### ISSUE TITLE
Unknown order

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5092]
**Unknown order**

If i Click on Squamata it Shows only Unknown Order…

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/d6c9861e73e372973e54207e67ca5b54:f326dea9c782a8e958f86dc61988b1fb93c083cf9774d6c80e1385a030cad6a7b58983eba35d8bfbd39fbb8e329b89c52010272c96e201d247b77be57a0d56bea376f5c19146531dc9b260b507ee870025001f1fe4b90f6feef73b476d5eaa01) - [Send email](https://www.gbif.org/api/feedback/user/mailto/d6c9861e73e372973e54207e67ca5b54:f326dea9c782a8e958f86dc61988b1fb93c083cf9774d6c80e1385a030cad6a7b58983eba35d8bfbd39fbb8e329b89c52010272c96e201d247b77be57a0d56bea376f5c19146531dc9b260b507ee870025001f1fe4b90f6feef73b476d5eaa01)
System: Mobile Safari 17.1.2 / iOS 17.1.2
Referer: https://www.gbif.org/
Window size: width 390 - height 663
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-12-12T20:08:54.731Z',to:'2023-12-12T20:14:54.731Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-12-12T20:08:54.731Z',to:'2023-12-12T20:14:54.731Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by MortenHofft** [comment]
I assume the user is refering to 
https://www.gbif.org/occurrence/search?taxon_key=44
<img width="297" alt="Screenshot 2024-01-02 at 11 48 05" src="https://github.com/gbif/portal-feedback/assets/6759267/1381dc26-fb21-4162-b875-56080de68449">

it is annoying, but the best we can do with the current APIs and data. When generating these trees we do a breakdown of the next major linnean rank. And in this case the is no orders in the backbone. As i remember I put a lot of effort into this compromise. It isn't great, but the best we could do if we wanted a tree at all. 

Since then we have argued we should add more fields to the index. So we should be able to do better when gogin straigh to elasticsearch. But not for current iteration of gbif.org where we use apiv1

https://www.gbif.org/species/11592253 family is next rank in this case
