### ISSUE TITLE
Anacardium occidentale Linn.

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5118]
**Anacardium occidentale Linn.**

reetings, 
I'm currently working on my proposal for my final year project for degree. I would like to ask when was the data for Anacardium occidentale Linn published on your website for reference?G

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/11db1549d887b36f2510f941b033a367:9f7e99ac389eb5e7f23cb881d040273d84ad1f374aec2608703216531e3e2211e158956a7139089fa76e2d2acc0c5ef41ba423d04120d241ff10b37ac041d0328e299e3d0efaf7ae63526cf931b72dc9d349687a9ba1bb25696ab4cf5893e68b) - [Send email](https://www.gbif.org/api/feedback/user/mailto/11db1549d887b36f2510f941b033a367:9f7e99ac389eb5e7f23cb881d040273d84ad1f374aec2608703216531e3e2211e158956a7139089fa76e2d2acc0c5ef41ba423d04120d241ff10b37ac041d0328e299e3d0efaf7ae63526cf931b72dc9d349687a9ba1bb25696ab4cf5893e68b)
System: Chrome 120.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/species/5421368
Window size: width 1366 - height 641
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-04T07:25:41.562Z',to:'2024-01-04T07:31:41.562Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-04T07:25:41.562Z',to:'2024-01-04T07:31:41.562Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Sent by email:

The data available on our species pages (like this one: https://www.gbif.org/species/5421368) is aggregated from many different sources: Museums, citizen science initiatives, etc.
For example, the map you see shows the geolocation of the occurrences (observation or collection of a specimen at a given time and location) published on GBIF for that species. You will find those occurrences in our [occurrence search](https://www.gbif.org/occurrence/search?taxon_key=5421368) interface. You can filter the occurrence data by observation/collection date (see the “year” filter in the interface).

Data providers regularly share new data on GBIF. The date of publication depends on the occurrence or checklist concerned. For example, [this occurrence](https://www.gbif.org/occurrence/311129960) belongs to [a dataset](https://www.gbif.org/dataset/51b92d4e-556f-4a05-bc5c-bfe982ee1156) that was first registered on GBIF in 2010 (but has been updated since).
