### ISSUE TITLE
where do I find extinct species

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5131]
**where do I find extinct species**

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/a6e0289d5381713cb105179c4e03914d:4bea1a4d34a9d1efa4759d68133eaa32de7d2515eb7971c05822075fbfb0c66761e50046631a73aa7977d6a1ecf4830c62eff082952e26c336844f370132e9f2232cdfad6ba8abc6fa3dadec642493c88f7239bed16d4023d2c24afc601f9395) - [Send email](https://www.gbif.org/api/feedback/user/mailto/a6e0289d5381713cb105179c4e03914d:4bea1a4d34a9d1efa4759d68133eaa32de7d2515eb7971c05822075fbfb0c66761e50046631a73aa7977d6a1ecf4830c62eff082952e26c336844f370132e9f2232cdfad6ba8abc6fa3dadec642493c88f7239bed16d4023d2c24afc601f9395)
System: Safari 16.5.2 / Mac OS X 10.15.7
Referer: https://www.gbif.org/species/search?advanced=1
Window size: width 1415 - height 930
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-11T12:24:39.589Z',to:'2024-01-11T12:30:39.589Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-01-11T12:24:39.589Z',to:'2024-01-11T12:30:39.589Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
This user also wrote to helpdesk mentioning that they used the species API as well but had issues because of the query limit.

I replied:
> The information available in the GBIF backbone taxonomy when it comes to extinction status is quite limited. The Species search API (https://api.gbif.org/v1/species/search?isExtinct=true) queries the taxa from all the checklists published on GBIF (which are then matched to the GBIF Backbone taxonomy). The information made available in those checklists isn’t checked by anyone else than the data providers (which can be museums, citizen science initiatives, etc). I am mentioning this because the information might not always be the most complete or reliable.
Note that checklistbank allows a similar query in [their interface](https://www.checklistbank.org/nameusage/search?extinct=true&facet=datasetKey&facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&limit=50&offset=0&sortBy=taxonomic) (although the content isn’t downloadable).

And then I sent them this file: a list of the taxonID in the GBIF Backbone taxonomy where at least one matching name in another checklist was associated with the information isExtinct = True.
[id_extinct_species.csv](https://github.com/gbif/portal-feedback/files/13939320/id_extinct_species.csv)
