### ISSUE TITLE
Issue with Data Query for Actinopteri in the GBIF Database

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5273]
**Issue with Data Query for Actinopteri in the GBIF Database**

Dear GBIF Support Team,

I hope this message finds you well. I am writing to report a technical issue I encountered while attempting to access data for the class Actinopteri (ray-finned fishes) through your database. It seems that the query function for this particular class is not returning results as expected.

To provide more context, when attempting to perform a data query for Actinopteri, either through direct search or using the API, the process fails to retrieve any data, or it returns incomplete or inconsistent results. This issue seems to be specific to the Actinopteri class, as I have not experienced similar problems with queries for other taxa.

Understanding the vast amount of data managed by GBIF, I appreciate the complexities involved in maintaining such a comprehensive resource. However, as the data on Actinopteri is crucial for my research (or project), I kindly request your assistance in resolving this issue. If possible, could you please investigate the cause of this problem and provide an estimated timeline for a resolution? Additionally, if there are alternative methods for accessing this data in the meantime, I would be grateful for your guidance.

Thank you for your attention to this matter and for the invaluable service GBIF provides to the research community. I look forward to your prompt response and am happy to provide any further information needed to assist in resolving this issue.

Best regards,

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/dc2b29b080570e4b33b493c435bb38db:b182a4b45868e280799c563b98b30f9c91d57bee007c2f65f3941bb8eb612e25857be1ef73e431d2658c97335eaabc575139d2eadff162331c3f62bbc474be168a22ecda24a659ff49654e01d3930ba1d609ac7e9a238c597a78231dac6f932a) - [Send email](https://www.gbif.org/api/feedback/user/mailto/dc2b29b080570e4b33b493c435bb38db:b182a4b45868e280799c563b98b30f9c91d57bee007c2f65f3941bb8eb612e25857be1ef73e431d2658c97335eaabc575139d2eadff162331c3f62bbc474be168a22ecda24a659ff49654e01d3930ba1d609ac7e9a238c597a78231dac6f932a)
System: Chrome 122.0.0 / Mac OS X 10.15.7
Referer: https://www.gbif.org/zh/species/search?q=Osteichthyes
Window size: width 1725 - height 914
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-03-26T06:30:01.179Z',to:'2024-03-26T06:36:01.179Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-03-26T06:30:01.179Z',to:'2024-03-26T06:36:01.179Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
> Replied by email


As you noted Actinopterygii is no longer searchable on GBIF. This is because it isn’t a class any more in the GBIF backbone taxonomy (see https://github.com/gbif/portal-feedback/issues/4507 for more information).
This means that you will have to select all the orders that were previously under the Actinopterygii class. Here is a selection for you:
 
https://www.gbif.org/occurrence/search?taxon_key=1103&taxon_key=1104&taxon_key=494&taxon_key=495&taxon_key=1105&taxon_key=496&taxon_key=497&taxon_key=1106&taxon_key=498&taxon_key=499&taxon_key=1107&taxon_key=537&taxon_key=538&taxon_key=1153&taxon_key=547&taxon_key=1162&taxon_key=548&taxon_key=549&taxon_key=550&taxon_key=1163&taxon_key=1164&taxon_key=1165&taxon_key=1166&taxon_key=1167&taxon_key=1305&taxon_key=1067&taxon_key=1306&taxon_key=1307&taxon_key=1308&taxon_key=1068&taxon_key=1069&taxon_key=587&taxon_key=1310&taxon_key=588&taxon_key=589&taxon_key=1311&taxon_key=1312&taxon_key=1313&taxon_key=590&taxon_key=708&taxon_key=890&taxon_key=774&taxon_key=889&taxon_key=773&taxon_key=772&taxon_key=888&occurrence_status=present
