### ISSUE TITLE
Have the taxon section located earlier in the filter panel when using "All filters" setting

### ISSUE THREAD

**Issue by tobiasgf** [gbif/portal-feedback#5328]
When using the "All filters option" under occurrence search, the "taxon" section is far down in the list.
https://www.gbif.org/occurrence/search?occurrence_status=present&q=

I suggest to have it as the first section.

non-experts may scroll down and be fooled by the "organism" section, when looking for where to put taxonomic search criteria.

**Comment by MortenHofft** [comment]
I'm happy to rearrange sections. To avoid my personal opinions I decided to strictly follow the ordering of sections of fields as they are provided by tdwg https://dwc.tdwg.org/terms/
at least that was the intention. 

This isn't because I necessarily find it to be ideal, but knowing that whatever I did someone would disagree. I will change the ordering and leave a comment in code that you are the origin of the change. Once I have 10 different opinions I will create an issue to let you all hash it out :)

**Comment by MortenHofft** [comment]
@tobiasgf it would be great if you could help specify the ordering of all the groups. If you would like to?
Based on downloads these filters are the most frequently used: scientific name, year, country/location

But obviously it isn't just a question about what is most used, but also what we want to draw attention to. Which is the reason we have license and occurrenceStatus in the short list, despite no one using them

**Comment by tobiasgf** [comment]
My quick take would be:
taxon
location
event
occurrence
provenance


the rest
...
...
