### ISSUE TITLE
Unable to download occurrences

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5530]
**Unable to download occurrences**

Hello,

I am trying to download occurrences for species Dioscorea bulbifera (air potato). I am searching for the species and the filters I am trying to do is to include coordinates and a specific continent. When I click on download, I get a message that is only supported for structured search- not for free text queries. What am I doing wrong?

Thank you

-----

User: [See in registry](https://www.gbif.org/api/feedback/user/6f8b6f3fe67e7151f38832f6071cf0f5:ef609acd2214cab748de698bc99cbba2067466a6be18ab092ca9410f693d5ba694a9f0be33ebef171085eb829242dd15408516e906272b2a2fc7d635a761011015f328f7f0c22ae430f414b0bf255885e06c883b29503e912609cf5a2ceb8663fc6a61421a8f6e46c3170a701e9b86f9) - [Send email](https://www.gbif.org/api/feedback/user/mailto/6f8b6f3fe67e7151f38832f6071cf0f5:ef609acd2214cab748de698bc99cbba2067466a6be18ab092ca9410f693d5ba694a9f0be33ebef171085eb829242dd15408516e906272b2a2fc7d635a761011015f328f7f0c22ae430f414b0bf255885e06c883b29503e912609cf5a2ceb8663fc6a61421a8f6e46c3170a701e9b86f9)
System: Chrome 130.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download?q=Dioscorea%20bulbifera&has_coordinate=true&has_geospatial_issue=false&occurrence_status=present
Window size: width 1672 - height 926
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-10-25T13:40:49.868Z',to:'2024-10-25T13:46:49.868Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-10-25T13:40:49.868Z',to:'2024-10-25T13:46:49.868Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by ManonGros** [comment]
The reason why you got an error message is because you the scientific name was in the free-text query field. This field cannot be used for downloading records. I suggest using the scientific name field instead, see this selection: https://www.gbif.org/occurrence/search?has_coordinate=true&has_geospatial_issue=false&taxon_key=7964683&taxon_key=7985575&taxon_key=2755489&occurrence_status=present

If you would like a full introduction to GBIF.org, you are welcome to check our [Data Use Club](https://www.gbif.org/data-use-club) recorded webinars ([the introduction to our website](https://www.gbif.org/composition/4Xm5cVB4y9n7U1GlUtKx8Q/data-use-club-practical-session-1-recording-and-resources) might be helpful).

> Replied by email
