### ISSUE TITLE
Add help text on how to open download files to the download page?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#5570]
**Add help text on how to open download files to the download page?**

It might be helpful for some users to see the help text on how to open the files in the download archive in their download page.

> 
> How do I open tab-delimited CSV files downloaded from GBIF.org in Excel?
> If you're using Excel on a Mac
> 
>     Open Excel
>     Create a new empty spreadsheet (File → New)
>     Import text file (Data → Get Data → From File → From Text/CSV)
>     Select the downloaded CSV file (e.g. 0000822-180131172636756.csv)
>     Select "Tab" as Delimiter and "Unicode (UTF-8)" as File Origin
>     Click Load
> 
> If you're using Excel in Windows
> 
>     Open Excel
>     Create a new empty spreadsheet (File → New)
>     Click the Data tab
>     From "Get External Data", click From text
>     Select the downloaded CSV file (e.g. 0000822-180131172636756.csv)
>     Click Import
>     Select "Delimited" as Data Type and "Unicode (UTF-8)" as File Origin
>     Click Finish
>     Click OK to import data into current sheet
> 
> The above procedure also works for occurrence.txt files from Darwin Core Archives.

-----

Github user: @CecSve
User: [See in registry](https://www.gbif.org/api/feedback/user/e4312d601e0fb7ec6df06de642b90605:47224dbf89ecc8c9c6f13a9aa997c0354526b03d313cb31141e5fcd7d0ad4ea3e475dbf8f0a81ec82bcb15ad6044b15b24970a3342fae47f8134665b5bbbd7a81ca64ed01d7bd8228c9b4a0c1da8f4fb7d90f6dc5438c2b94c3fe12e4beee4f5) - [Send email](https://www.gbif.org/api/feedback/user/mailto/e4312d601e0fb7ec6df06de642b90605:47224dbf89ecc8c9c6f13a9aa997c0354526b03d313cb31141e5fcd7d0ad4ea3e475dbf8f0a81ec82bcb15ad6044b15b24970a3342fae47f8134665b5bbbd7a81ca64ed01d7bd8228c9b4a0c1da8f4fb7d90f6dc5438c2b94c3fe12e4beee4f5)
System: Firefox 132.0.0 / Windows 10.0.0
Referer: https://www.gbif.org/occurrence/download/0004796-241107131044228
Window size: width 1918 - height 1027
[API log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-11-11T08:47:40.396Z',to:'2024-11-11T08:53:40.396Z'))&_a=(columns:!(_source),filters:!(),index:'3390a910-fcda-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
[Site log](https://private-logs.gbif.org/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-11-11T08:47:40.396Z',to:'2024-11-11T08:53:40.396Z'))&_a=(columns:!(_source),filters:!(),index:'5c73f360-fce3-11ea-a9ab-4375f2a9d11c',interval:auto,query:(language:kuery,query:''),sort:!()))
System health at time of feedback: OPERATIONAL

**Comment by Mesibov** [comment]
I find this suggestion objectionable. It promotes a commercial product, Microsoft Excel, and ignores the many other ways in which downloaded text files can be inspected, searched, edited and otherwise managed.

Many GBIF data users will be managing downloaded data on the command line with R or shell tools. For them, this advice is irrelevant. The suggestion is presumably directed to those users who want the data in a GUI application.

There are free non-commercial GUI applications for managing CSV data, as well as commercial ones with free versions. Among many others for both Windows and other OSes I can recommend

ModernCSV (free/premium; superior to Excel; Windows, Mac and Linux): https://www.moderncsv.com/
EmEditor (free/premium; superior to Excel; Windows): https://www.emeditor.com/
LibreOfficeCalc (free; Windows, Mac and Linux)
Gnumeric (free; Mac and Linux)
Apache Open Office Calc (free; Windows, Mac and Linux)
WPS Office Spreadsheet (free/premium; Windows, Mac and Linux)

**Comment by MortenHofft** [comment]
For context: "how to open in Excel" is probably the most frequently asked helpdesk question.

**Comment by Mesibov** [comment]
All the more reason to offer advice on free and superior alternatives.

**Comment by MattBlissett** [comment]
The download notification email already includes the text:

>  For help with opening downloaded files, see https://www.gbif.org/faq?question=opening-gbif-csv-in-excel or the FAQ section of the GBIF website: https://www.gbif.org/faq 

so I'm not sure adding even more advice will help.

**Comment by CecSve** [comment]
> The download notification email already includes the text:
> 
> > For help with opening downloaded files, see https://www.gbif.org/faq?question=opening-gbif-csv-in-excel or the FAQ section of the GBIF website: https://www.gbif.org/faq
> 
> so I'm not sure adding even more advice will help.

I missed that. Yes, I agree and will close this issue. 

As for advice on other alternatives to open files, I propose to open a new issue if this is something we would want to promote, however, I do not think we can cover all methods or in a generalized way. We do try to support users when they contact helpdesk and help them with alternative programs, if that is their method of choice.

**Comment by Mesibov** [comment]
@CecSve, good morning (Australian time) and apologies for not replying sooner.

If someone has Excel on their computer but **does not know how to use it**, is it appropriate for GBIF to instruct  them, rather than refer them to Microsoft help or Microsoft user resources?

If the answer is yes, perhaps GBIF could consider making life easier for such users by offering downloads in .xlsx format. For larger downloads, of course, the datasets would need to be split into multiple Excel files. GBIF could also consider giving Microsoft Corporation a permanent seat on the GBIF Governing Board and invite Microsoft to become a corporate sponsor.

GBIF currently makes data available as delimited text files, which for simplicity I will here call CSVs. Surely the FAQ should cover the question "How do I open and manage CSVs?", where the implication is "open in a GUI application".

There are freely available, non-spreadsheet GUI applications optimised for opening and managing CSVs. The best of these applications are ModernCSV and EmEditor. These handle DTFs larger than a spreadsheet can open, and work much faster.

Users of these applications can do all the data management jobs that they can do in a spreadsheet except operate with formulas, although EmEditor allows scriptable macros that can function like formulas. Those "data management jobs that they can do in a spreadsheet" are easier and more flexibly done in a dedicated CSV application.

As large CSVs (such as some GBIF downloads) have become more common in data work, it's become apparent that applications suited to smaller CSVs, like Excel, are simply not the right tools for the job. For a recent review of this larger problem I recommend "[How to Open Big CSV Files – an Ultimate Guide](https://dadroit.com/blog/open-big-csv/#common-challenges-of-opening-large-csv-files)".

There will, of course, be GBIF data users who only know Excel and insist on it. It is always sad when people stop learning, but GBIF can offer better advice to the many others. For users in organisations which do not allow non-Microsoft applications, that advice would at least point users to the wider and more efficient world of computing outside the Microsoft box.
