### ISSUE TITLE
Indexing issue?

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#592]
**Indexing issue?**

Not clear that this dataset has been successfully indexed in 12 tries since being registerd June. Clicking on the endpoint link returns a permissions error—is it simply locked or marked as private as its source?

-----
fbitem-dataset5d06e33b-e884-4369-9a1a-fdc8bfa9471c
User provided contact info: @kcopas
System: Safari 11.0.0 / Mac OS X 10.12.6
Referer: https://www.gbif.org/dataset/5d06e33b-e884-4369-9a1a-fdc8bfa9471c
Window size: width 1314 - height 793
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-26T19:41:35.116Z',mode:absolute,to:'2017-10-26T19:47:35.116Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-10-26T19:41:35.116Z',mode:absolute,to:'2017-10-26T19:47:35.116Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
Hi @kcopas I might be misunderstanding - but the interface doesn't say anything about 12 successful. Contrary it states 100% Aborted.
But the first line is a bit weird. `12 times in total. 12 failed since last successful. ` That line should probably just go if it has never been indexed properly.

![screen shot 2017-10-27 at 08 06 21](https://user-images.githubusercontent.com/6759267/32090056-bfc43c26-baed-11e7-9497-96a66e1adc93.png)

Other that that it is a registration issue i would think

**Comment by kcopas** [comment]
Sorry, I was indeed responding to the 'since last successful' and understating the case. Agreed that it has not been successfully indexed.

Would a registration error included somehow not unlocking or making the DwC-A public? (Fishing for terms here, I don't know that system well enough to know what vernacular is operative...) Because I do get what seems like a permissions-based error when trying to download the archive from the endpoint.

**Comment by MortenHofft** [comment]
This seem similar to https://github.com/gbif/portal-feedback/issues/597
With the difference that it isn't available on VPN either - so i suspect that the file simply isn't there and on top of that there is the issue seen in #597

**Comment by ahahn-gbif** [comment]
Contacted dataset publisher / NBN installation from helpdesk. Looks like a dead endpoint issue.

**Comment by ahahn-gbif** [comment]
Reply from publisher: dataset (https://www.gbif.org/dataset/5d06e33b-e884-4369-9a1a-fdc8bfa9471c) has recently been updated but still needs to be uploaded. May need watching once republished.

**Comment by ahahn-gbif** [comment]
Rechecking with publisher.

**Comment by ManonGros** [comment]
I updated the endpoint for this publisher. The dataset is being ingested again.
