### ISSUE TITLE
Year not properly imported

### ISSUE THREAD

**Issue by andzandz11** [gbif/portal-feedback#598]
GBIF is not importing the year information properly from 
https://www.gbif.org/dataset/e6fab7b3-c733-40b9-8df3-2a03e49532c1
because it is a range of years(?). It would be very imporant to get this information for a lot of people who want to switch to GBIF from floraweb.de but can not do so, because there are no "years" in GBIF.

**Comment by thomasstjerne** [comment]
Hi @andzandz11 thanks!

Yes, this is probably because it is a range. This is currently not supported, see: http://rs.tdwg.org/dwc/terms/#year

To indicate a time interval, use eventDate instead: http://rs.tdwg.org/dwc/terms/#eventDate.
E.g.: `eventDate: "2000-01-01T00:00:00Z/2010-01-01T00:00:00Z"`
would indicate 2000-2010

**Comment by mdoering** [comment]
As far as I can see there is no eventDate information given in the occurrences of that dataset:
raw biocase xml:
https://api.gbif.org/v1/occurrence/1310994156/fragment

transformed but into verbatim DwC:
https://api.gbif.org/v1/occurrence/1310994156/verbatim

Is there anywhere but in the dataset metadata which is not interpreted at all?

**Comment by andzandz11** [comment]
There are dates in the original dataset.
http://floraweb.de/pflanzenarten/download_tkqxml.xsql?suchnr=1
The interval is indicated in <ZEITRAUM_TEXT>

@mdoering If you can't see them, then maybe the information is not forwarded properly? Should I write the maintainer of the dataset?

**Comment by mdoering** [comment]
thanks, that would be appreciated!
