### ISSUE TITLE
Cannot register

### ISSUE THREAD

**Issue by andzandz11** [gbif/portal-feedback#600]
I can not register via the registration form on gbif.org because my official email gets rejected. It is build like this:

name dot name at name number dot name dot name-with-hyphen dot domain

example:
anton.wicher@erd1.geo.uni-potsdam.de

Please check your REGEX.

I have also emailed info@gbif.org, sorry. Please don't fix twice, it may break again :D

**Comment by MortenHofft** [comment]
I just tried registering with nonse.name2398475ksjdhgf@erd1.geo.uni-potsdam.de
It works on dev and uat, but not in production. Christian changed this recently in response to another user bug. https://github.com/gbif/gbif-api/commit/4ed8ae03434b6d2100f6209f462b6d64fe083328
Perhaps it hasn't been deployed since?

**Comment by MortenHofft** [comment]
@andzandz11 thank you for reporting this. Sorry about that. It seems our regex is overly harsh. I believe it is the dash in `uni-potsdam`  - that should be fixed of course.

Thanks

**Comment by andzandz11** [comment]
Thank you!

I just tried 5 minutes ago and it doesn't work.

![clipboard01](https://user-images.githubusercontent.com/19622117/32103174-877d94e8-bb1f-11e7-9726-652c61ceed1b.jpg)

**Comment by andzandz11** [comment]
Thanks, cool!

**Comment by MortenHofft** [comment]
You fixed this I believe @fmendezh - if not please reopen
