### ISSUE TITLE
Update GBIF Backbone

### ISSUE THREAD

**Issue by mdoering** [gbif/portal-feedback#628]
Various issues have been reported that should be fixed by a new backbone based on updated sources. OTU names should be left out and be restricted still to UAT testing.

https://github.com/gbif/portal-feedback/milestone/1
https://github.com/gbif/checklistbank/milestone/4

**Comment by andzandz11** [comment]
If a backbone update stalls anything else, maybe you can switch to a rolling update system that works constantly? Then users could flag species (with a yellow exlamation mark icon) that have some kind of outdated information and that species would be fixed instantly because it could be given priority in the update query. It would save you a ton of work.

**Comment by mdoering** [comment]
gbif/checklistbank#16 captures some of these ideas
