### ISSUE TITLE
Geographic coverage swapped

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#635]
**Geographic coverage swapped**

Dear colleagues! 

There is discrepancy between geographic coverage defined in dataset 
description within IPT and that than we could se via global portal. 
https://www.gbif.org/dataset/b941d3d1-964e-47dc-a3e7-f8edb144e051#geographicCoverages
It looks like that eastern and western boundaries were replaced each other.

-----
fbitem-datasetb941d3d1-964e-47dc-a3e7-f8edb144e051

System: Chrome 61.0.3163 / Mac OS X 10.11.5
Referer: https://www.gbif.org/dataset/b941d3d1-964e-47dc-a3e7-f8edb144e051
Window size: width 1387 - height 799
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-04T08:18:49.306Z',mode:absolute,to:'2017-11-04T08:24:49.306Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-04T08:18:49.306Z',mode:absolute,to:'2017-11-04T08:24:49.306Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
from @jlegind 
While the coordinate box shape looks correct in the IPT, the two coordinate points it passes on to GBIF seem to be interpreted as going from -180 and towards East. That is going from the most Westwards point and moving towards East regardless of the coordinate label.
<westBoundingCoordinate>-18.984</westBoundingCoordinate> <eastBoundingCoordinate>-168.047</eastBoundingCoordinate> <northBoundingCoordinate>78.768</northBoundingCoordinate> <southBoundingCoordinate>-36.031</southBoundingCoordinate>
In that regard our interpretation is ‘stupid’ since it cannot figure out that bounding boxes can cross the antipodal meridian.

http://gbif.ru:8080/ipt/resource?r=raptors
https://www.gbif.org/dataset/b941d3d1-964e-47dc-a3e7-f8edb144e051#geographicCoverages

**Comment by MortenHofft** [comment]
As far as I can see the difference is that the IPT use a different convention than our API, the website and the big mapping libraries Leaflet, Mapbox and Openlayers.

That said, it seems like a small fix for the website to try to compensate for that difference.
