### ISSUE TITLE
Species missing authorship

### ISSUE THREAD

**Issue by andzandz11** [gbif/portal-feedback#641]
Why is there an author here:
http://services.snsb.info/DTNtaxonlists/rest/v0.1/names/DiversityTaxonNames_Plants/1390/
But here it is gone:
https://api.gbif.org/v1/species/9121925
?
It seems some kind of conversion from one format to another fails?

https://www.gbif.org/species/9121925

**Comment by mdoering** [comment]
Looks like the author parsing is failing, presumably because of the space between sensu latu:
https://api.gbif.org/v1/species/116781636/name

Not working as it is:
http://api.gbif.org/v1/parser/name?name=Centaurea%20scabiosa%20L.%20s.%20l.

Works without space:
http://api.gbif.org/v1/parser/name?name=Centaurea%20scabiosa%20L.%20s.l.
