### ISSUE TITLE
Registration form: clicking outside form wipes form

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#643]
**Registration form: clicking outside form wipes form**

All information entered in the form is lost when clicking anywhere outside the form. 

This isn't the same behavior with this feedback dialog, so inconsistent as well as inconveniencing to our new users.

-----
fbitem-ab29ac3a8dcee341f980bfa4f6246a83884060fe
User provided contact info: kbraak
System: Firefox 56.0.0 / Mac OS X 10.10.0
Referer: https://www.gbif.org/terms/data-user
Window size: width 1241 - height 1106
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-07T14:07:41.083Z',mode:absolute,to:'2017-11-07T14:13:41.083Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-07T14:07:41.083Z',mode:absolute,to:'2017-11-07T14:13:41.083Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MortenHofft** [comment]
The idea was that it shouldn't save you password in the browser if you decide not to go through with the registration or sign in. This is different from the feedback in that it doesn't hold sensitive information. 

If you strongly believe that it should remember your password even if you do not login, then I'm open for arguments. It might be hysteric and in reality just be really useful. But that was the thinking. I'm closing as won't fix - but you are welcome to reopen it with arguments for. I guess security is always inconvenient. It is never obvious to me where to draw the line.

I imagine that you discovered this because you logged issue #642 midway. I believe that inconvenience is less important than protecting the users information.
