### ISSUE TITLE
Five failed crawls noted on NHM London specimen collection

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#645]
**Five failed crawls noted on NHM London specimen collection**

Happened to check this dataset knowing that there have been several news items about recent digitization efforts, plus (I think) WeDigBio. Looks like we might be several hundred thousand records out of sync, even accounting for mineralogy.

Probably a good one to keep in sync, no?

-----
fbitem-dataset7e380070-f762-11e1-a439-00145eb45e9a
User provided contact info: @kcopas
System: Safari 11.0.1 / Mac OS X 10.13.1
Referer: https://www.gbif.org/dataset/7e380070-f762-11e1-a439-00145eb45e9a
Window size: width 1309 - height 793
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-07T15:40:13.921Z',mode:absolute,to:'2017-11-07T15:46:13.921Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-07T15:40:13.921Z',mode:absolute,to:'2017-11-07T15:46:13.921Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by kcopas** [comment]
Just to mention, this problem is still lingering— 10 failed crawls since the last successful one. https://www.gbif.org/dataset/7e380070-f762-11e1-a439-00145eb45e9a

**Comment by MattBlissett** [comment]
Duplicate triplets.

Finished validating DwC-A for dataset [7e380070-f762-11e1-a439-00145eb45e9a], valid? is [false]. Full report [DwcaValidationReport{datasetKey=7e380070-f762-11e1-a439-00145eb45e9a, invalidationReason=null, occurrenceReport=OccurrenceValidationReport{checkedRecords=2000000, uniqueTriplets=1733746, recordsWithInvalidTriplets=221329, uniqueOccurrenceIds=1999421, recordsMissingOccurrenceId=0, allRecordsChecked=false, invalidationReason=Archive invalid because [44925 duplicate triplets detected; 579 duplicate occurrence ids detected], valid=false}, genericReport=null}]

**Comment by MattBlissett** [comment]
We are about 500k new records behind now, presumably a lot of updates too.

The problem is the 793 duplicated occurrenceIds in the file:

`csvtool format '%(37)\n' occurrence.csv| sort | uniq -c -d`

And the 458k duplicate triplets, i.e. where institutionCode + collectionCode + catalogNumber is duplicated.

`csvtool format '%(58) %(32) %(47)\n' occurrence.csv| sort | uniq -D | nl`

Possibly @benscott handles the software that exports this (is it https://github.com/NaturalHistoryMuseum/ckanpackager ?). Although it looks more like a data error than a software error.

**Comment by MattBlissett** [comment]
`3f595364-2cae-413e-865a-7f208cef99b9` is an example duplicated occurrenceId: http://data.nhm.ac.uk/dataset/collection-specimens/resource/05ff2255-c38a-40c9-b657-4ccb55ab2feb?view_id=6b611d29-1dcf-4c60-b6b5-4cbb69fdf4fe&q=3f595364-2cae-413e-865a-7f208cef99b9

`NHMUK` `ZOO` `S/2014.43.1` is an example duplicated triplet.

**Comment by benscott** [comment]
Yes, there is currently an issue with our collection GUIDs.  Our data managers are currently working on a fix and we'll start producing a valid & harvestable DWCA again shortly.

**Comment by jrdh** [comment]
We have now resolved this internally and the DwC-A we produce should be correct. Can a crawl be manually triggered or will we have to wait for the next automated crawl to confirm this issue is resolved @MattBlissett ?

**Comment by MortenHofft** [comment]
It is in the queue https://management-tools.gbif.org/crawling-monitor

**Comment by MattBlissett** [comment]
Success!

All the new records have been added, with no problems.

Very minor thing, and I don't know if it's new: in the EML, many URLs have an extra "http://", like http://http://data.nhm.ac.uk/ and http://http://data.nhm.ac.uk/images/logo.png

**Comment by jrdh** [comment]
Good point, I'll look at getting that sorted out, thanks @MattBlissett

**Comment by MortenHofft** [comment]
@jrdh if the email you are registered on GBIF.org is also the one used in either the dataset contacts, publisher contacts or node contacts or host contacts, then you should be able to start the crawl/ingestion yourself on the dataset page. If not please tell me, then I have a bug to fix. 

If you are using ORCiD, that will work as well as the email.

**Comment by jrdh** [comment]
@MattBlissett the repeated "http://" issue has been resolved so the correct URLs should come through next time our DwC-a output is crawled (there's no rush though so we'll just wait for the next automatic trigger). Thanks again for pointing that out.

@MortenHofft thanks for the info, now that I've been added as a contact I can indeed see the ingestion information on the dataset page and can trigger ingestions, thanks for pointing it out!

Can this issue be closed now?

**Comment by MattBlissett** [comment]
Of course! Thanks for handling it.
