### ISSUE TITLE
Camera trap images detected but not displaying in gallery

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#656]
**Camera trap images detected but not displaying in gallery**

I thought I'd flagged this more recently than [JIRA issue DM-210](http://dev.gbif.org/issues/browse/DM-210), but maybe not.

Thing is, we're obviously picking up the references: the system's recognizing that the occurrences have images, both through the filter and the presence of a (blank) gallery. Digging a little further, the image URLs listed in the multimedia extension of the DwC-A also check out, e.g. [this example](http://ibif.gov.in:8080/ipt/camera_trap_images/CTP050612005290A00002a.jpg). 

It's a really interesting dataset with connections to an [IPBES-funded project](https://www.gbif.org/news/82368/capacity-project-generates-new-guide-on-camera-trapping) and publication (which looks like it's missing) as well as one of the very few we have from from WII.

-----
fbitem-datasete61455a4-352d-4c55-83ea-dbca254e3b29
User provided contact info: @kcopas
System: Safari 11.0.1 / Mac OS X 10.13.1
Referer: https://www.gbif.org/dataset/e61455a4-352d-4c55-83ea-dbca254e3b29
Window size: width 1309 - height 793
[API log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-10T07:49:03.752Z',mode:absolute,to:'2017-11-10T07:55:03.752Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499%20AND%20(request:%22%2F%2Fapi.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)
[Site log](http://elk.gbif.org:5601/app/kibana#/discover/UAT-Varnish-403s?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-11-10T07:49:03.752Z',mode:absolute,to:'2017-11-10T07:55:03.752Z'))&_a=(columns:!(request,response,clientip),filters:!(),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E399%20AND%20(request:%22%2F%2Fdemo.gbif.org%22)')),sort:!('@timestamp',desc))&indexPattern=uat-varnish-*&type=histogram)

**Comment by MattBlissett** [comment]
Scroll down the gallery and you'll see that it's the first page of images that are broken (they return 404), but the rest work.

https://www.gbif.org/occurrence/gallery?dataset_key=e61455a4-352d-4c55-83ea-dbca254e3b29

**Comment by jhnwllr** [comment]
I will write to the publisher about the missing images, but perhaps we should also have a GBIF front end fix where we don't display broken image links @MortenHofft? If it is possible...

**Comment by MattBlissett** [comment]
The straightforward option would be to test the image links at download time -- but that could very easily overload the publisher's server.

**Comment by jhnwllr** [comment]
publisher emails bounced, so we are stuck with a front end solution or we ignore this.

**Comment by MortenHofft** [comment]
The front end do not know if an image is broken ahead of time. We can ask for it and detect if it is broken/missing upon arrival. Currently we show that the image is broken, we could also choose to hide it.

In occurrence search gallery we show an explicit broken image. In the dataset view I simply hide it (but fetch far more images than can be shown, so typically there will be enough functional ones that the row will be filled). We should probably show the explicit broken image insteda then (like on occurrence/gallery)

I prefer showing it:
* it shows that there is an issue that should be fixed instead of masking it.
* If broken images is hidden, then we risk showing no images at all and a more button. And when clicking "more" then no images again. I think that would be a bad user experience. Worse than showing a broken image link.
