### ISSUE TITLE
New display

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#707]
**New display**

Dear GBIF Team,
I cannot figure out how to retrieve the occurrence map displayed until last week - yellow dots on dark background - you apparently substituted it by the pinkish/bluish grid on homepage. Sorry but the new display sucks.

-----
fbitem-632937989213bf4e43cb42556216fa1047383e29
User provided contact info: escobargp@yahoo.es
System: Firefox 57.0.0 / Windows 7 0.0.0
Referer: https://www.gbif.org/occurrence/map?has_coordinate=true&has_geospatial_issue=false
Window size: width 1024 - height 480
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-09T17:43:42.845Z',mode:absolute,to:'2017-12-09T17:49:42.845Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-09T17:43:42.845Z',mode:absolute,to:'2017-12-09T17:49:42.845Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: INFO

**Comment by MortenHofft** [comment]
Dear Escobar
Sorry but I'm not sure I understand. The maps haven't changed in 5 months.

For all maps (except one) you can change style using the paint roll button and even customize to your liking. it will remember what you changed it to. So if you change it to "pinkish/bluish grid" it will stay that way most places. If the maps have changed it is because you or someone using your computer have changed the styling.

![screen shot 2017-12-11 at 15 49 48](https://user-images.githubusercontent.com/6759267/33836876-feb40ef0-de8a-11e7-93e1-508e341d989b.png)

The one map where you cannot change styling is the occurrence search map. We would all like it to have more options, but I'm afraid that isn't possible right now. And it hasn't been at any point. That map is different from the rest in that you can filter it as you like (other maps only have `year` and `basis of record` filters). Unfortunately it has a very coarse resolution at this point.

![screen shot 2017-12-11 at 15 52 00](https://user-images.githubusercontent.com/6759267/33836970-42f926e0-de8b-11e7-9ac5-76b203603ce2.png)

I'm still not sure I understand the issue, but it is a shame that you think it sucks.

Remember that all data is freely available for you to download and display with a different mapping tool if you prefer so.

Thanks
