### ISSUE TITLE
Loading speed in East Asia

### ISSUE THREAD

**Issue by ghost** [gbif/portal-feedback#710]
Hi GBIFS developers,

I've been observing the loading performance from this side of the world and have found that in general GBIF.org takes long to load pages relevant to a participant. Attached please have a look at screenshots from the network tab of Firefox Quantum. Other than the TW one, the rest are the 2nd load via a VPN service. 

If there is anything we could help to speed up the performance in Asia, please let us know.

Cheers,
Chihjen, Node Manager at TaiBIF

![tw](https://user-images.githubusercontent.com/31983251/33817447-a5769d90-de7a-11e7-9418-415d8f8d0afc.png)

![jp](https://user-images.githubusercontent.com/31983251/33817500-dcba4bee-de7a-11e7-92bf-6bb1c1d86ce6.png)

![hk](https://user-images.githubusercontent.com/31983251/33817522-f77e600a-de7a-11e7-8075-90cf488370ef.png)

![kr](https://user-images.githubusercontent.com/31983251/33817551-18742a24-de7b-11e7-8b2f-99ad60d7bbb1.png)

![sg](https://user-images.githubusercontent.com/31983251/33817564-25e70988-de7b-11e7-82a9-92998b418c14.png)

**Comment by MortenHofft** [comment]
Hi Chihjen - it will take me a time to get used to your real name :)

Thanks. Yes, lets see if we can get that faster. Slow pages are annoying. 7.5 seconds to load the page i see. That is a long time. 

**Is the performance okay in general?**
As you know we opted for building everything into one file, and then using client routing for most browsing. So the initial page will be slow and subsequent hopefully faster. But that only makes it weirder that the participant pages in particular is slow. Strange.

**Which VPN service are you using?**
I have never found anything i trusted and that worked well.

**examples**

*  I see that this call https://api.gbif.org/v1/occurrence/count?publishingCountry=TW took 2.5 seconds in one of your tests. That is API directly and there is no data in there. 
* and this 1 second https://www.gbif.org/api/occurrence/search?country=TW&facet=kingdomKey&limit=0

In these two cases it seems to be API performance and sending the data across the globe. 

I also see that a few calls is sending results where we only care about the count. Those could easily be eliminated, but only accounts for a small part of it.

**what can we do**
* I'm guessing that to make this faster we could have servers elsewhere than in Denmark. 
* I could also look into bundling requests through dedicated proxies for some pages, though it sounds like a development pain to maintain.
* images also seem to be a big part of it? perhaps lazy loading them on scroll would help as well. 

Can you see if there is any calls that are the big sinners? If you [disable pictures](https://chrome.google.com/webstore/detail/web-developer/bfbameneiokkgbdmiekhjnmfkcnldhhm) does it help? There is a lot of slowish API calls on the participant pages, but since it is reasonable here i guess it is the data amount, the amount of calls and sending the data from DK. 

Thanks
