### ISSUE TITLE
broken publisher logos

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#731]
**broken publisher logos**

Looking at the publisher search there is a lot of broken logos from new publishers. 

* https://www.gbif.org/publisher/0cb06233-9a34-40ca-a4d1-3f882202373f
* https://www.gbif.org/publisher/65789534-4f81-45d7-8f19-e53c3f880c6c
* https://www.gbif.org/publisher/196af968-bf4c-415c-a9c4-7943c7c6cfca
* https://www.gbif.org/publisher/8e3e7b8f-88de-4be0-bdcf-f4524171313a
* https://www.gbif.org/publisher/bd5be4d1-61e8-4928-8289-f89d6126093a
* https://www.gbif.org/publisher/b081673d-44bb-437a-8e69-750950afa49c
* https://www.gbif.org/publisher/13ca1e6e-e120-446f-ad6c-1c40e5368322

-----
fbitem-22de88f76c9d79b8f048b83b3cfbc3036b234366

System: Chrome 63.0.3239 / Mac OS X 10.11.6
Referer: https://www.gbif.org/publisher/search?offset=80
Window size: width 1920 - height 1080
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-18T13:04:05.575Z',mode:absolute,to:'2017-12-18T13:10:05.575Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2017-12-18T13:04:05.575Z',mode:absolute,to:'2017-12-18T13:10:05.575Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
I fixed a few of these. Many people have given a Google Images search result, rather than an image.

**Comment by MattBlissett** [comment]
https://www.gbif.org/become-a-publisher

So maybe this could be a little clearer when the logo isn't working. The preview is a good idea, but people must be overlooking it when it shows a broken image.

**Comment by MortenHofft** [comment]
I guess that they don't care too much since they don't fix it. Should probably just remove the logos from search when the link is broken. We hide them on the actual publisher pages if they are broken.

**Comment by ahahn-gbif** [comment]
When a publisher contacts us because they do not find their logo, we give them guidance. It may not be best use of resources to monitor logos going off-line actively from our side. Agree we should hide them if they are broken. Registry update would then bring them up again, as soon as we get a valid link.

**Comment by jeroencreuwels** [comment]
In the Netherlands we have the problem that broken publisher links exists on the following page:  https://www.gbif.org/publisher/search?country=NL, but not at the NLBIF- IPT page. The URL given by publishers some time ago when they apply for endorsement easily get broken over time and and/or because logos are changing.
The IPTpage is the place where data publishers (and the endorsing node) normally look more frequently and keep the logos updated. Is it an idea to have a link to these URLs, or to somehow use this information?

By the way, for Naturalis the new URL is https://www.naturalis.nl/media/library/2012/07/Naturalis_logo_staand_rood_01.jpg

Jeroen Creuwels, Data manager Naturalis / NLBIF ICTsupport
