### ISSUE TITLE
there is a fault in this article! there is no region in turkey named kurdistan

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#763]
**there is a fault in this article! there is no region in turkey named kurdistan**

-----
fbitem-species113275677

System: Firefox Mobile 57.0.0 / Android 5.0.2
Referer: https://www.gbif.org/species/113275677
Window size: width 360 - height 511
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-13T14:30:44.321Z',mode:absolute,to:'2018-01-13T14:36:44.321Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-13T14:30:44.321Z',mode:absolute,to:'2018-01-13T14:36:44.321Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: CRITICAL

**Comment by rdmpage** [comment]
The Wikipedia page has since been updated (see https://en.wikipedia.org/w/index.php?title=Vulpes_vulpes_kurdistanica&type=revision&diff=808031276&oldid=718789591 ) to remove the reference to Kurdistan, I'm assuming GBIF hasn't crawled Wikipedia more recently. This is a case where politics impacts taxonomy, see https://en.wikipedia.org/wiki/Animal_name_changes_in_Turkey.

**Comment by ahahn-gbif** [comment]
@mdoering: is it possible to reindex that page? A bit of a political issue here.

**Comment by MattBlissett** [comment]
Wikipedia's checklist has updated, and this name is no longer present.
