### ISSUE TITLE
Links to logos of publishers seems broken

### ISSUE THREAD

**Issue by gbif-portal** [gbif/portal-feedback#803]
**Links to logos of publishers seems broken**

It seems tot me that currently logos are not shown
If I look to the publishers in my country, various don't show a logo whereas they all were visible some time ago. I don't know if this has something to do with outages of the last days..

-----
fbitem-465f4ad16ed342b1a2d0972aceb430078ee021ba
User provided contact info: jeroen.creuwels@naturalis.nl
System: Chrome 63.0.3239 / Windows 7 0.0.0
Referer: https://www.gbif.org/health
Window size: width 1920 - height 910
[API log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-31T15:29:36.156Z',mode:absolute,to:'2018-01-31T15:35:36.156Z'))&_a=(columns:!(_source),index:'prod-varnish-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
[Site log](http://elk.gbif.org:5601/app/kibana?#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:'2018-01-31T15:29:36.156Z',mode:absolute,to:'2018-01-31T15:35:36.156Z'))&_a=(columns:!(_source),index:'prod-portal-*',interval:auto,query:(query_string:(analyze_wildcard:!t,query:'response:%3E499')),sort:!('@timestamp',desc)))
System health at time of feedback: OPERATIONAL

**Comment by MattBlissett** [comment]
On https://www.gbif.org/publisher/search?country=NL I see two failed logos, which is because the URL for the logos give a 404.

We had a 15 minute outage of about 50% of images earlier, Google Images searching discovered our images, and seems to be downloading them at about 10 per second. We could cope with this, but the source servers (museum servers etc) sometimes can't, and we run out of available connections on the image server.

Emailed.
